# Embedded file name: scripts/client/_ge_achievements_epic.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy():
    pass


isServerDatabase = False

class AMMO_TYPE():
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy():
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType():
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE():
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE():
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.header = Dummy()
DB.header.activity = []
DB.header.client = Dummy()
DB.header.client.place = 'right'
DB.header.condition = []
DB.header.count = []
DB.header.event = []
DB.header.group = 'epic'
DB.header.markers = Dummy()
DB.header.markers.group = 'epic'
DB.header.modify = []
DB.header.operation = []
DB.header.send = []
DB.header.server = Dummy()
DB.header.server.active = true
DB.header.server.scope = []
DB.header.server.scope.insert(0, None)
DB.header.server.scope[0] = 'player'
DB.header.type = 'achievement'
DB.include = Dummy()
DB.include.activity = []
DB.include.condition = []
DB.include.condition.insert(0, None)
DB.include.condition[0] = Dummy()
DB.include.condition[0].and_ = []
DB.include.condition[0].contains = []
DB.include.condition[0].equal = []
DB.include.condition[0].gt = []
DB.include.condition[0].gte = []
DB.include.condition[0].gte.insert(0, None)
DB.include.condition[0].gte[0] = Dummy()
DB.include.condition[0].gte[0].context = []
DB.include.condition[0].gte[0].context.insert(0, None)
DB.include.condition[0].gte[0].context[0] = 'player.plane.level'
DB.include.condition[0].gte[0].value_ = []
DB.include.condition[0].gte[0].value_.insert(0, None)
DB.include.condition[0].gte[0].value_[0] = '4'
DB.include.condition[0].id = []
DB.include.condition[0].in_ = []
DB.include.condition[0].lt = []
DB.include.condition[0].lte = []
DB.include.condition[0].not_ = []
DB.include.condition[0].or_ = []
DB.include.condition.insert(1, None)
DB.include.condition[1] = Dummy()
DB.include.condition[1].and_ = []
DB.include.condition[1].contains = []
DB.include.condition[1].equal = []
DB.include.condition[1].gt = []
DB.include.condition[1].gte = []
DB.include.condition[1].id = []
DB.include.condition[1].in_ = []
DB.include.condition[1].lt = []
DB.include.condition[1].lte = []
DB.include.condition[1].not_ = []
DB.include.condition[1].or_ = []
DB.include.condition[1].or_.insert(0, None)
DB.include.condition[1].or_[0] = Dummy()
DB.include.condition[1].or_[0].and_ = []
DB.include.condition[1].or_[0].and_.insert(0, None)
DB.include.condition[1].or_[0].and_[0] = Dummy()
DB.include.condition[1].or_[0].and_[0].and_ = []
DB.include.condition[1].or_[0].and_[0].contains = []
DB.include.condition[1].or_[0].and_[0].equal = []
DB.include.condition[1].or_[0].and_[0].equal.insert(0, None)
DB.include.condition[1].or_[0].and_[0].equal[0] = Dummy()
DB.include.condition[1].or_[0].and_[0].equal[0].context = []
DB.include.condition[1].or_[0].and_[0].equal[0].context.insert(0, None)
DB.include.condition[1].or_[0].and_[0].equal[0].context[0] = 'arena.type'
DB.include.condition[1].or_[0].and_[0].equal[0].value_ = []
DB.include.condition[1].or_[0].and_[0].equal[0].value_.insert(0, None)
DB.include.condition[1].or_[0].and_[0].equal[0].value_[0] = 'normal'
DB.include.condition[1].or_[0].and_[0].equal.insert(1, None)
DB.include.condition[1].or_[0].and_[0].equal[1] = Dummy()
DB.include.condition[1].or_[0].and_[0].equal[1].context = []
DB.include.condition[1].or_[0].and_[0].equal[1].context.insert(0, None)
DB.include.condition[1].or_[0].and_[0].equal[1].context[0] = 'arena.source'
DB.include.condition[1].or_[0].and_[0].equal[1].value_ = []
DB.include.condition[1].or_[0].and_[0].equal[1].value_.insert(0, None)
DB.include.condition[1].or_[0].and_[0].equal[1].value_[0] = 'player'
DB.include.condition[1].or_[0].and_[0].gt = []
DB.include.condition[1].or_[0].and_[0].gte = []
DB.include.condition[1].or_[0].and_[0].id = []
DB.include.condition[1].or_[0].and_[0].in_ = []
DB.include.condition[1].or_[0].and_[0].lt = []
DB.include.condition[1].or_[0].and_[0].lte = []
DB.include.condition[1].or_[0].and_[0].not_ = []
DB.include.condition[1].or_[0].and_[0].or_ = []
DB.include.condition[1].or_[0].and_.insert(1, None)
DB.include.condition[1].or_[0].and_[1] = Dummy()
DB.include.condition[1].or_[0].and_[1].and_ = []
DB.include.condition[1].or_[0].and_[1].contains = []
DB.include.condition[1].or_[0].and_[1].equal = []
DB.include.condition[1].or_[0].and_[1].equal.insert(0, None)
DB.include.condition[1].or_[0].and_[1].equal[0] = Dummy()
DB.include.condition[1].or_[0].and_[1].equal[0].context = []
DB.include.condition[1].or_[0].and_[1].equal[0].context.insert(0, None)
DB.include.condition[1].or_[0].and_[1].equal[0].context[0] = 'self.event.type'
DB.include.condition[1].or_[0].and_[1].equal[0].value_ = []
DB.include.condition[1].or_[0].and_[1].equal[0].value_.insert(0, None)
DB.include.condition[1].or_[0].and_[1].equal[0].value_[0] = 'hangar'
DB.include.condition[1].or_[0].and_[1].gt = []
DB.include.condition[1].or_[0].and_[1].gte = []
DB.include.condition[1].or_[0].and_[1].id = []
DB.include.condition[1].or_[0].and_[1].in_ = []
DB.include.condition[1].or_[0].and_[1].lt = []
DB.include.condition[1].or_[0].and_[1].lte = []
DB.include.condition[1].or_[0].and_[1].not_ = []
DB.include.condition[1].or_[0].and_[1].or_ = []
DB.include.condition[1].or_[0].contains = []
DB.include.condition[1].or_[0].equal = []
DB.include.condition[1].or_[0].gt = []
DB.include.condition[1].or_[0].gte = []
DB.include.condition[1].or_[0].id = []
DB.include.condition[1].or_[0].in_ = []
DB.include.condition[1].or_[0].lt = []
DB.include.condition[1].or_[0].lte = []
DB.include.condition[1].or_[0].not_ = []
DB.include.condition[1].or_[0].or_ = []
DB.include.count = []
DB.include.event = []
DB.include.metadata = Dummy()
DB.include.metadata.doneCount = true
DB.include.metadata.event = []
DB.include.metadata.firstDoneTime = true
DB.include.metadata.lastDoneTime = true
DB.include.modify = []
DB.include.operation = []
DB.include.send = []
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].activity = []
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].name = 'finish'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].operation.insert(0, None)
DB.subscriber[0].event[0].operation[0] = Dummy()
DB.subscriber[0].event[0].operation[0].event = []
DB.subscriber[0].event[0].operation[0].id = []
DB.subscriber[0].event[0].operation[0].id.insert(0, None)
DB.subscriber[0].event[0].operation[0].id[0] = Dummy()
DB.subscriber[0].event[0].operation[0].id[0].group = 'epic'
DB.subscriber[0].event[0].operation[0].id[0].name = '*'
DB.subscriber[0].event[0].operation[0].id[0].type = 'achievement'
DB.subscriber[0].event[0].operation[0].rollback = true
DB.subscriber[0].event[0].operation[0].set = Dummy()
DB.subscriber[0].event[0].operation[0].set.completed = false
DB.subscriber[0].event[0].type = 'battle'
DB.subscriber[0].event.insert(1, None)
DB.subscriber[0].event[1] = Dummy()
DB.subscriber[0].event[1].condition = []
DB.subscriber[0].event[1].context = 'player'
DB.subscriber[0].event[1].count = []
DB.subscriber[0].event[1].name = 'day.changed'
DB.subscriber[0].event[1].operation = []
DB.subscriber[0].event[1].operation.insert(0, None)
DB.subscriber[0].event[1].operation[0] = Dummy()
DB.subscriber[0].event[1].operation[0].event = []
DB.subscriber[0].event[1].operation[0].id = []
DB.subscriber[0].event[1].operation[0].id.insert(0, None)
DB.subscriber[0].event[1].operation[0].id[0] = Dummy()
DB.subscriber[0].event[1].operation[0].id[0].group = 'epic'
DB.subscriber[0].event[1].operation[0].id[0].name = '*'
DB.subscriber[0].event[1].operation[0].id[0].type = 'achievement'
DB.subscriber[0].event[1].operation[0].processors = Dummy()
DB.subscriber[0].event[1].operation[0].processors.count = []
DB.subscriber[0].event[1].operation[0].processors.event = []
DB.subscriber[0].event[1].operation[0].processors.transaction = []
DB.subscriber[0].event[1].operation[0].processors.transaction.insert(0, None)
DB.subscriber[0].event[1].operation[0].processors.transaction[0] = 0
DB.subscriber[0].event[1].operation[0].reset_ = true
DB.subscriber[0].event[1].type = 'hangar'
DB.subscriber[0].group = 'epic'
DB.subscriber[0].modify = []
DB.subscriber[0].name = 'reset'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber[0].server = Dummy()
DB.subscriber[0].server.overwrite = true
DB.subscriber[0].server.repeat = true
DB.subscriber[0].server.scope = []
DB.subscriber[0].type = 'achievement.reset'
DB.subscriber.insert(1, None)
DB.subscriber[1] = Dummy()
DB.subscriber[1].activity = []
DB.subscriber[1].client = Dummy()
DB.subscriber[1].client.description = Dummy()
DB.subscriber[1].client.description.locale = 'MEDAL_DESCRIPTION_MARCEL'
DB.subscriber[1].client.history = Dummy()
DB.subscriber[1].client.history.locale = 'MEDAL_HISTORY_MARCEL'
DB.subscriber[1].client.icon = Dummy()
DB.subscriber[1].client.icon.big = 'icons/awards/achievementsInfo/acEpicMarseille.dds'
DB.subscriber[1].client.icon.faded = 'icons/awards/achievements/acEpicMarseille_Outline.dds'
DB.subscriber[1].client.icon.small = 'icons/awards/achievements/acEpicMarseille.dds'
DB.subscriber[1].client.level = Dummy()
DB.subscriber[1].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[1].client.multiple = true
DB.subscriber[1].client.name = Dummy()
DB.subscriber[1].client.name.locale = 'MEDAL_NAME_MARCEL'
DB.subscriber[1].client.order = 1
DB.subscriber[1].client.page = 0
DB.subscriber[1].condition = []
DB.subscriber[1].count = []
DB.subscriber[1].event = []
DB.subscriber[1].event.insert(0, None)
DB.subscriber[1].event[0] = Dummy()
DB.subscriber[1].event[0].condition = []
DB.subscriber[1].event[0].context = 'player'
DB.subscriber[1].event[0].count = []
DB.subscriber[1].event[0].count.insert(0, None)
DB.subscriber[1].event[0].count[0] = Dummy()
DB.subscriber[1].event[0].count[0].id = 0
DB.subscriber[1].event[0].count[0].value_ = 17
DB.subscriber[1].event[0].name = 'kill'
DB.subscriber[1].event[0].operation = []
DB.subscriber[1].event[0].type = 'battle'
DB.subscriber[1].event.insert(1, None)
DB.subscriber[1].event[1] = Dummy()
DB.subscriber[1].event[1].condition = []
DB.subscriber[1].event[1].context = 'player'
DB.subscriber[1].event[1].count = []
DB.subscriber[1].event[1].count.insert(0, None)
DB.subscriber[1].event[1].count[0] = Dummy()
DB.subscriber[1].event[1].count[0].value_ = 1
DB.subscriber[1].event[1].name = 'win'
DB.subscriber[1].event[1].operation = []
DB.subscriber[1].event[1].type = 'battle'
DB.subscriber[1].event.insert(2, None)
DB.subscriber[1].event[2] = Dummy()
DB.subscriber[1].event[2].condition = []
DB.subscriber[1].event[2].context = 'player'
DB.subscriber[1].event[2].count = []
DB.subscriber[1].event[2].name = 'death'
DB.subscriber[1].event[2].operation = []
DB.subscriber[1].event[2].operation.insert(0, None)
DB.subscriber[1].event[2].operation[0] = Dummy()
DB.subscriber[1].event[2].operation[0].event = []
DB.subscriber[1].event[2].operation[0].id = []
DB.subscriber[1].event[2].operation[0].rollback = true
DB.subscriber[1].event[2].operation[0].self = true
DB.subscriber[1].event[2].type = 'battle'
DB.subscriber[1].modify = []
DB.subscriber[1].name = 'marcel'
DB.subscriber[1].operation = []
DB.subscriber[1].send = []
DB.subscriber[1].send.insert(0, None)
DB.subscriber[1].send[0] = Dummy()
DB.subscriber[1].send[0].event = []
DB.subscriber[1].send[0].event.insert(0, None)
DB.subscriber[1].send[0].event[0] = Dummy()
DB.subscriber[1].send[0].event[0].condition = []
DB.subscriber[1].send[0].event[0].context = 'marcel.epic'
DB.subscriber[1].send[0].event[0].count = []
DB.subscriber[1].send[0].event[0].name = 'completed'
DB.subscriber[1].send[0].event[0].operation = []
DB.subscriber[1].send[0].event[0].type = 'achievement'
DB.subscriber.insert(2, None)
DB.subscriber[2] = Dummy()
DB.subscriber[2].activity = []
DB.subscriber[2].client = Dummy()
DB.subscriber[2].client.description = Dummy()
DB.subscriber[2].client.description.locale = 'MEDAL_DESCRIPTION_MACCAMPBELL'
DB.subscriber[2].client.history = Dummy()
DB.subscriber[2].client.history.locale = 'MEDAL_HISTORY_MACCAMPBELL'
DB.subscriber[2].client.icon = Dummy()
DB.subscriber[2].client.icon.big = 'icons/awards/achievementsInfo/acEpicMcCampbell.dds'
DB.subscriber[2].client.icon.faded = 'icons/awards/achievements/acEpicMcCampbell_Outline.dds'
DB.subscriber[2].client.icon.small = 'icons/awards/achievements/acEpicMcCampbell.dds'
DB.subscriber[2].client.level = Dummy()
DB.subscriber[2].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[2].client.multiple = true
DB.subscriber[2].client.name = Dummy()
DB.subscriber[2].client.name.locale = 'MEDAL_NAME_MACCAMPBELL'
DB.subscriber[2].client.order = 2
DB.subscriber[2].client.page = 0
DB.subscriber[2].condition = []
DB.subscriber[2].count = []
DB.subscriber[2].event = []
DB.subscriber[2].event.insert(0, None)
DB.subscriber[2].event[0] = Dummy()
DB.subscriber[2].event[0].condition = []
DB.subscriber[2].event[0].context = 'player'
DB.subscriber[2].event[0].count = []
DB.subscriber[2].event[0].count.insert(0, None)
DB.subscriber[2].event[0].count[0] = Dummy()
DB.subscriber[2].event[0].count[0].value_ = 1
DB.subscriber[2].event[0].name = 'win'
DB.subscriber[2].event[0].operation = []
DB.subscriber[2].event[0].type = 'battle'
DB.subscriber[2].event.insert(1, None)
DB.subscriber[2].event[1] = Dummy()
DB.subscriber[2].event[1].condition = []
DB.subscriber[2].event[1].condition.insert(0, None)
DB.subscriber[2].event[1].condition[0] = Dummy()
DB.subscriber[2].event[1].condition[0].and_ = []
DB.subscriber[2].event[1].condition[0].contains = []
DB.subscriber[2].event[1].condition[0].equal = []
DB.subscriber[2].event[1].condition[0].equal.insert(0, None)
DB.subscriber[2].event[1].condition[0].equal[0] = Dummy()
DB.subscriber[2].event[1].condition[0].equal[0].context = []
DB.subscriber[2].event[1].condition[0].equal[0].context.insert(0, None)
DB.subscriber[2].event[1].condition[0].equal[0].context[0] = 'self.processors.count.0.done'
DB.subscriber[2].event[1].condition[0].equal[0].value_ = []
DB.subscriber[2].event[1].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[2].event[1].condition[0].equal[0].value_[0] = 'no'
DB.subscriber[2].event[1].condition[0].gt = []
DB.subscriber[2].event[1].condition[0].gte = []
DB.subscriber[2].event[1].condition[0].id = []
DB.subscriber[2].event[1].condition[0].in_ = []
DB.subscriber[2].event[1].condition[0].lt = []
DB.subscriber[2].event[1].condition[0].lte = []
DB.subscriber[2].event[1].condition[0].not_ = []
DB.subscriber[2].event[1].condition[0].or_ = []
DB.subscriber[2].event[1].context = 'player'
DB.subscriber[2].event[1].count = []
DB.subscriber[2].event[1].name = 'death'
DB.subscriber[2].event[1].operation = []
DB.subscriber[2].event[1].operation.insert(0, None)
DB.subscriber[2].event[1].operation[0] = Dummy()
DB.subscriber[2].event[1].operation[0].event = []
DB.subscriber[2].event[1].operation[0].id = []
DB.subscriber[2].event[1].operation[0].rollback = true
DB.subscriber[2].event[1].operation[0].self = true
DB.subscriber[2].event[1].type = 'battle'
DB.subscriber[2].event.insert(2, None)
DB.subscriber[2].event[2] = Dummy()
DB.subscriber[2].event[2].condition = []
DB.subscriber[2].event[2].context = 'player'
DB.subscriber[2].event[2].count = []
DB.subscriber[2].event[2].count.insert(0, None)
DB.subscriber[2].event[2].count[0] = Dummy()
DB.subscriber[2].event[2].count[0].by = 'victim.plane.type'
DB.subscriber[2].event[2].count[0].contains = Dummy()
DB.subscriber[2].event[2].count[0].contains.item = []
DB.subscriber[2].event[2].count[0].contains.item.insert(0, None)
DB.subscriber[2].event[2].count[0].contains.item[0] = 'fighter'
DB.subscriber[2].event[2].count[0].contains.item.insert(1, None)
DB.subscriber[2].event[2].count[0].contains.item[1] = 'heavy.fighter'
DB.subscriber[2].event[2].count[0].contains.item.insert(2, None)
DB.subscriber[2].event[2].count[0].contains.item[2] = 'navy'
DB.subscriber[2].event[2].count[0].contains.item.insert(3, None)
DB.subscriber[2].event[2].count[0].contains.item[3] = 'assault'
DB.subscriber[2].event[2].count[0].contains.item.insert(4, None)
DB.subscriber[2].event[2].count[0].contains.item[4] = 'bomber'
DB.subscriber[2].event[2].count[0].id = 0
DB.subscriber[2].event[2].count[0].total = true
DB.subscriber[2].event[2].count[0].value_ = 10
DB.subscriber[2].event[2].name = 'kill'
DB.subscriber[2].event[2].operation = []
DB.subscriber[2].event[2].type = 'battle'
DB.subscriber[2].modify = []
DB.subscriber[2].name = 'maccambell'
DB.subscriber[2].operation = []
DB.subscriber[2].send = []
DB.subscriber.insert(3, None)
DB.subscriber[3] = Dummy()
DB.subscriber[3].activity = []
DB.subscriber[3].client = Dummy()
DB.subscriber[3].client.description = Dummy()
DB.subscriber[3].client.description.locale = 'MEDAL_DESCRIPTION_LANG'
DB.subscriber[3].client.history = Dummy()
DB.subscriber[3].client.history.locale = 'MEDAL_HISTORY_LANG'
DB.subscriber[3].client.icon = Dummy()
DB.subscriber[3].client.icon.big = 'icons/awards/achievementsInfo/acEpicLang.dds'
DB.subscriber[3].client.icon.faded = 'icons/awards/achievements/acEpicLang_Outline.dds'
DB.subscriber[3].client.icon.small = 'icons/awards/achievements/acEpicLang.dds'
DB.subscriber[3].client.level = Dummy()
DB.subscriber[3].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[3].client.multiple = true
DB.subscriber[3].client.name = Dummy()
DB.subscriber[3].client.name.locale = 'MEDAL_NAME_LANG'
DB.subscriber[3].client.order = 3
DB.subscriber[3].client.page = 0
DB.subscriber[3].condition = []
DB.subscriber[3].count = []
DB.subscriber[3].event = []
DB.subscriber[3].event.insert(0, None)
DB.subscriber[3].event[0] = Dummy()
DB.subscriber[3].event[0].condition = []
DB.subscriber[3].event[0].context = 'player'
DB.subscriber[3].event[0].count = []
DB.subscriber[3].event[0].count.insert(0, None)
DB.subscriber[3].event[0].count[0] = Dummy()
DB.subscriber[3].event[0].count[0].id = 0
DB.subscriber[3].event[0].count[0].value_ = 15
DB.subscriber[3].event[0].name = 'destroy'
DB.subscriber[3].event[0].operation = []
DB.subscriber[3].event[0].type = 'battle'
DB.subscriber[3].event.insert(1, None)
DB.subscriber[3].event[1] = Dummy()
DB.subscriber[3].event[1].condition = []
DB.subscriber[3].event[1].context = 'player'
DB.subscriber[3].event[1].count = []
DB.subscriber[3].event[1].count.insert(0, None)
DB.subscriber[3].event[1].count[0] = Dummy()
DB.subscriber[3].event[1].count[0].value_ = 1
DB.subscriber[3].event[1].name = 'win'
DB.subscriber[3].event[1].operation = []
DB.subscriber[3].event[1].type = 'battle'
DB.subscriber[3].event.insert(2, None)
DB.subscriber[3].event[2] = Dummy()
DB.subscriber[3].event[2].condition = []
DB.subscriber[3].event[2].condition.insert(0, None)
DB.subscriber[3].event[2].condition[0] = Dummy()
DB.subscriber[3].event[2].condition[0].and_ = []
DB.subscriber[3].event[2].condition[0].contains = []
DB.subscriber[3].event[2].condition[0].equal = []
DB.subscriber[3].event[2].condition[0].equal.insert(0, None)
DB.subscriber[3].event[2].condition[0].equal[0] = Dummy()
DB.subscriber[3].event[2].condition[0].equal[0].context = []
DB.subscriber[3].event[2].condition[0].equal[0].context.insert(0, None)
DB.subscriber[3].event[2].condition[0].equal[0].context[0] = 'self.processors.count.0.done'
DB.subscriber[3].event[2].condition[0].equal[0].value_ = []
DB.subscriber[3].event[2].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[3].event[2].condition[0].equal[0].value_[0] = 'no'
DB.subscriber[3].event[2].condition[0].gt = []
DB.subscriber[3].event[2].condition[0].gte = []
DB.subscriber[3].event[2].condition[0].id = []
DB.subscriber[3].event[2].condition[0].in_ = []
DB.subscriber[3].event[2].condition[0].lt = []
DB.subscriber[3].event[2].condition[0].lte = []
DB.subscriber[3].event[2].condition[0].not_ = []
DB.subscriber[3].event[2].condition[0].or_ = []
DB.subscriber[3].event[2].context = 'player'
DB.subscriber[3].event[2].count = []
DB.subscriber[3].event[2].name = 'death'
DB.subscriber[3].event[2].operation = []
DB.subscriber[3].event[2].operation.insert(0, None)
DB.subscriber[3].event[2].operation[0] = Dummy()
DB.subscriber[3].event[2].operation[0].event = []
DB.subscriber[3].event[2].operation[0].id = []
DB.subscriber[3].event[2].operation[0].rollback = true
DB.subscriber[3].event[2].operation[0].self = true
DB.subscriber[3].event[2].type = 'battle'
DB.subscriber[3].modify = []
DB.subscriber[3].name = 'lang'
DB.subscriber[3].operation = []
DB.subscriber[3].send = []
DB.subscriber[3].send.insert(0, None)
DB.subscriber[3].send[0] = Dummy()
DB.subscriber[3].send[0].event = []
DB.subscriber[3].send[0].event.insert(0, None)
DB.subscriber[3].send[0].event[0] = Dummy()
DB.subscriber[3].send[0].event[0].condition = []
DB.subscriber[3].send[0].event[0].context = 'lang.epic'
DB.subscriber[3].send[0].event[0].count = []
DB.subscriber[3].send[0].event[0].name = 'completed'
DB.subscriber[3].send[0].event[0].operation = []
DB.subscriber[3].send[0].event[0].type = 'achievement'
DB.subscriber.insert(4, None)
DB.subscriber[4] = Dummy()
DB.subscriber[4].activity = []
DB.subscriber[4].client = Dummy()
DB.subscriber[4].client.description = Dummy()
DB.subscriber[4].client.description.locale = 'MEDAL_DESCRIPTION_GOLUBEV'
DB.subscriber[4].client.history = Dummy()
DB.subscriber[4].client.history.locale = 'MEDAL_HISTORY_GOLUBEV'
DB.subscriber[4].client.icon = Dummy()
DB.subscriber[4].client.icon.big = 'icons/awards/achievementsInfo/acEpicGolubev.dds'
DB.subscriber[4].client.icon.faded = 'icons/awards/achievements/acEpicGolubev_Outline.dds'
DB.subscriber[4].client.icon.small = 'icons/awards/achievements/acEpicGolubev.dds'
DB.subscriber[4].client.level = Dummy()
DB.subscriber[4].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[4].client.multiple = true
DB.subscriber[4].client.name = Dummy()
DB.subscriber[4].client.name.locale = 'MEDAL_NAME_GOLUBEV'
DB.subscriber[4].client.order = 4
DB.subscriber[4].client.page = 0
DB.subscriber[4].condition = []
DB.subscriber[4].count = []
DB.subscriber[4].event = []
DB.subscriber[4].event.insert(0, None)
DB.subscriber[4].event[0] = Dummy()
DB.subscriber[4].event[0].condition = []
DB.subscriber[4].event[0].condition.insert(0, None)
DB.subscriber[4].event[0].condition[0] = Dummy()
DB.subscriber[4].event[0].condition[0].and_ = []
DB.subscriber[4].event[0].condition[0].contains = []
DB.subscriber[4].event[0].condition[0].equal = []
DB.subscriber[4].event[0].condition[0].equal.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[4].event[0].condition[0].equal[0].context = []
DB.subscriber[4].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[4].event[0].condition[0].equal[0].value_ = []
DB.subscriber[4].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0].value_[0] = 'rocket'
DB.subscriber[4].event[0].condition[0].gt = []
DB.subscriber[4].event[0].condition[0].gte = []
DB.subscriber[4].event[0].condition[0].id = []
DB.subscriber[4].event[0].condition[0].in_ = []
DB.subscriber[4].event[0].condition[0].lt = []
DB.subscriber[4].event[0].condition[0].lte = []
DB.subscriber[4].event[0].condition[0].not_ = []
DB.subscriber[4].event[0].condition[0].or_ = []
DB.subscriber[4].event[0].context = 'player'
DB.subscriber[4].event[0].count = []
DB.subscriber[4].event[0].count.insert(0, None)
DB.subscriber[4].event[0].count[0] = Dummy()
DB.subscriber[4].event[0].count[0].id = 0
DB.subscriber[4].event[0].count[0].value_ = 3
DB.subscriber[4].event[0].name = 'kill'
DB.subscriber[4].event[0].operation = []
DB.subscriber[4].event[0].type = 'battle'
DB.subscriber[4].event.insert(1, None)
DB.subscriber[4].event[1] = Dummy()
DB.subscriber[4].event[1].condition = []
DB.subscriber[4].event[1].context = 'player'
DB.subscriber[4].event[1].count = []
DB.subscriber[4].event[1].count.insert(0, None)
DB.subscriber[4].event[1].count[0] = Dummy()
DB.subscriber[4].event[1].count[0].value_ = 1
DB.subscriber[4].event[1].name = 'win'
DB.subscriber[4].event[1].operation = []
DB.subscriber[4].event[1].type = 'battle'
DB.subscriber[4].event.insert(2, None)
DB.subscriber[4].event[2] = Dummy()
DB.subscriber[4].event[2].condition = []
DB.subscriber[4].event[2].condition.insert(0, None)
DB.subscriber[4].event[2].condition[0] = Dummy()
DB.subscriber[4].event[2].condition[0].and_ = []
DB.subscriber[4].event[2].condition[0].contains = []
DB.subscriber[4].event[2].condition[0].equal = []
DB.subscriber[4].event[2].condition[0].equal.insert(0, None)
DB.subscriber[4].event[2].condition[0].equal[0] = Dummy()
DB.subscriber[4].event[2].condition[0].equal[0].context = []
DB.subscriber[4].event[2].condition[0].equal[0].context.insert(0, None)
DB.subscriber[4].event[2].condition[0].equal[0].context[0] = 'self.processors.count.0.done'
DB.subscriber[4].event[2].condition[0].equal[0].value_ = []
DB.subscriber[4].event[2].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[4].event[2].condition[0].equal[0].value_[0] = 'no'
DB.subscriber[4].event[2].condition[0].gt = []
DB.subscriber[4].event[2].condition[0].gte = []
DB.subscriber[4].event[2].condition[0].id = []
DB.subscriber[4].event[2].condition[0].in_ = []
DB.subscriber[4].event[2].condition[0].lt = []
DB.subscriber[4].event[2].condition[0].lte = []
DB.subscriber[4].event[2].condition[0].not_ = []
DB.subscriber[4].event[2].condition[0].or_ = []
DB.subscriber[4].event[2].context = 'player'
DB.subscriber[4].event[2].count = []
DB.subscriber[4].event[2].name = 'death'
DB.subscriber[4].event[2].operation = []
DB.subscriber[4].event[2].operation.insert(0, None)
DB.subscriber[4].event[2].operation[0] = Dummy()
DB.subscriber[4].event[2].operation[0].event = []
DB.subscriber[4].event[2].operation[0].id = []
DB.subscriber[4].event[2].operation[0].rollback = true
DB.subscriber[4].event[2].operation[0].self = true
DB.subscriber[4].event[2].type = 'battle'
DB.subscriber[4].modify = []
DB.subscriber[4].name = 'golubev'
DB.subscriber[4].operation = []
DB.subscriber[4].send = []
DB.subscriber.insert(5, None)
DB.subscriber[5] = Dummy()
DB.subscriber[5].activity = []
DB.subscriber[5].client = Dummy()
DB.subscriber[5].client.description = Dummy()
DB.subscriber[5].client.description.locale = 'MEDAL_DESCRIPTION_HABREZKI'
DB.subscriber[5].client.history = Dummy()
DB.subscriber[5].client.history.locale = 'MEDAL_HISTORY_HABREZKI'
DB.subscriber[5].client.icon = Dummy()
DB.subscriber[5].client.icon.big = 'icons/awards/achievementsInfo/acEpicGabreski.dds'
DB.subscriber[5].client.icon.faded = 'icons/awards/achievements/acEpicGabreski_Outline.dds'
DB.subscriber[5].client.icon.small = 'icons/awards/achievements/acEpicGabreski.dds'
DB.subscriber[5].client.level = Dummy()
DB.subscriber[5].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[5].client.multiple = true
DB.subscriber[5].client.name = Dummy()
DB.subscriber[5].client.name.locale = 'MEDAL_NAME_HABREZKI'
DB.subscriber[5].client.order = 5
DB.subscriber[5].client.page = 0
DB.subscriber[5].condition = []
DB.subscriber[5].count = []
DB.subscriber[5].event = []
DB.subscriber[5].event.insert(0, None)
DB.subscriber[5].event[0] = Dummy()
DB.subscriber[5].event[0].condition = []
DB.subscriber[5].event[0].context = 'player'
DB.subscriber[5].event[0].count = []
DB.subscriber[5].event[0].count.insert(0, None)
DB.subscriber[5].event[0].count[0] = Dummy()
DB.subscriber[5].event[0].count[0].id = 0
DB.subscriber[5].event[0].count[0].value_ = 10
DB.subscriber[5].event[0].name = 'kill'
DB.subscriber[5].event[0].operation = []
DB.subscriber[5].event[0].type = 'battle'
DB.subscriber[5].event.insert(1, None)
DB.subscriber[5].event[1] = Dummy()
DB.subscriber[5].event[1].condition = []
DB.subscriber[5].event[1].context = 'player'
DB.subscriber[5].event[1].count = []
DB.subscriber[5].event[1].count.insert(0, None)
DB.subscriber[5].event[1].count[0] = Dummy()
DB.subscriber[5].event[1].count[0].id = 1
DB.subscriber[5].event[1].count[0].value_ = 7
DB.subscriber[5].event[1].name = 'destroy'
DB.subscriber[5].event[1].operation = []
DB.subscriber[5].event[1].type = 'battle'
DB.subscriber[5].event.insert(2, None)
DB.subscriber[5].event[2] = Dummy()
DB.subscriber[5].event[2].condition = []
DB.subscriber[5].event[2].context = 'player'
DB.subscriber[5].event[2].count = []
DB.subscriber[5].event[2].count.insert(0, None)
DB.subscriber[5].event[2].count[0] = Dummy()
DB.subscriber[5].event[2].count[0].value_ = 1
DB.subscriber[5].event[2].name = 'win'
DB.subscriber[5].event[2].operation = []
DB.subscriber[5].event[2].type = 'battle'
DB.subscriber[5].event.insert(3, None)
DB.subscriber[5].event[3] = Dummy()
DB.subscriber[5].event[3].condition = []
DB.subscriber[5].event[3].condition.insert(0, None)
DB.subscriber[5].event[3].condition[0] = Dummy()
DB.subscriber[5].event[3].condition[0].and_ = []
DB.subscriber[5].event[3].condition[0].contains = []
DB.subscriber[5].event[3].condition[0].equal = []
DB.subscriber[5].event[3].condition[0].gt = []
DB.subscriber[5].event[3].condition[0].gte = []
DB.subscriber[5].event[3].condition[0].id = []
DB.subscriber[5].event[3].condition[0].in_ = []
DB.subscriber[5].event[3].condition[0].lt = []
DB.subscriber[5].event[3].condition[0].lte = []
DB.subscriber[5].event[3].condition[0].not_ = []
DB.subscriber[5].event[3].condition[0].or_ = []
DB.subscriber[5].event[3].condition[0].or_.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0] = Dummy()
DB.subscriber[5].event[3].condition[0].or_[0].and_ = []
DB.subscriber[5].event[3].condition[0].or_[0].contains = []
DB.subscriber[5].event[3].condition[0].or_[0].equal = []
DB.subscriber[5].event[3].condition[0].or_[0].equal.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[0] = Dummy()
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].context = []
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].context.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].context[0] = 'self.processors.count.0.done'
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].value_ = []
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].value_.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[0].value_[0] = 'no'
DB.subscriber[5].event[3].condition[0].or_[0].equal.insert(1, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[1] = Dummy()
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].context = []
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].context.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].context[0] = 'self.processors.count.1.done'
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].value_ = []
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].value_.insert(0, None)
DB.subscriber[5].event[3].condition[0].or_[0].equal[1].value_[0] = 'no'
DB.subscriber[5].event[3].condition[0].or_[0].gt = []
DB.subscriber[5].event[3].condition[0].or_[0].gte = []
DB.subscriber[5].event[3].condition[0].or_[0].id = []
DB.subscriber[5].event[3].condition[0].or_[0].in_ = []
DB.subscriber[5].event[3].condition[0].or_[0].lt = []
DB.subscriber[5].event[3].condition[0].or_[0].lte = []
DB.subscriber[5].event[3].condition[0].or_[0].not_ = []
DB.subscriber[5].event[3].condition[0].or_[0].or_ = []
DB.subscriber[5].event[3].context = 'player'
DB.subscriber[5].event[3].count = []
DB.subscriber[5].event[3].name = 'death'
DB.subscriber[5].event[3].operation = []
DB.subscriber[5].event[3].operation.insert(0, None)
DB.subscriber[5].event[3].operation[0] = Dummy()
DB.subscriber[5].event[3].operation[0].event = []
DB.subscriber[5].event[3].operation[0].id = []
DB.subscriber[5].event[3].operation[0].rollback = true
DB.subscriber[5].event[3].operation[0].self = true
DB.subscriber[5].event[3].type = 'battle'
DB.subscriber[5].modify = []
DB.subscriber[5].name = 'habrezki'
DB.subscriber[5].operation = []
DB.subscriber[5].send = []
DB.subscriber.insert(6, None)
DB.subscriber[6] = Dummy()
DB.subscriber[6].activity = []
DB.subscriber[6].client = Dummy()
DB.subscriber[6].client.description = Dummy()
DB.subscriber[6].client.description.locale = 'MEDAL_DESCRIPTION_AKAMATSU'
DB.subscriber[6].client.history = Dummy()
DB.subscriber[6].client.history.locale = 'MEDAL_HISTORY_AKAMATSU'
DB.subscriber[6].client.icon = Dummy()
DB.subscriber[6].client.icon.big = 'icons/awards/achievementsInfo/acEpicAkamatsu.dds'
DB.subscriber[6].client.icon.faded = 'icons/awards/achievements/acEpicAkamatsu_Outline.dds'
DB.subscriber[6].client.icon.small = 'icons/awards/achievements/acEpicAkamatsu.dds'
DB.subscriber[6].client.level = Dummy()
DB.subscriber[6].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[6].client.multiple = true
DB.subscriber[6].client.name = Dummy()
DB.subscriber[6].client.name.locale = 'MEDAL_NAME_AKAMATSU'
DB.subscriber[6].client.order = 6
DB.subscriber[6].client.page = 0
DB.subscriber[6].condition = []
DB.subscriber[6].count = []
DB.subscriber[6].event = []
DB.subscriber[6].event.insert(0, None)
DB.subscriber[6].event[0] = Dummy()
DB.subscriber[6].event[0].condition = []
DB.subscriber[6].event[0].condition.insert(0, None)
DB.subscriber[6].event[0].condition[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_[0].contains = []
DB.subscriber[6].event[0].condition[0].and_[0].equal = []
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context[0] = 'player.plane.type'
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_[0] = 'fighter'
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.object'
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_[0] = 'plane'
DB.subscriber[6].event[0].condition[0].and_[0].gt = []
DB.subscriber[6].event[0].condition[0].and_[0].gte = []
DB.subscriber[6].event[0].condition[0].and_[0].id = []
DB.subscriber[6].event[0].condition[0].and_[0].in_ = []
DB.subscriber[6].event[0].condition[0].and_[0].lt = []
DB.subscriber[6].event[0].condition[0].and_[0].lte = []
DB.subscriber[6].event[0].condition[0].and_[0].not_ = []
DB.subscriber[6].event[0].condition[0].and_[0].or_ = []
DB.subscriber[6].event[0].condition[0].contains = []
DB.subscriber[6].event[0].condition[0].equal = []
DB.subscriber[6].event[0].condition[0].gt = []
DB.subscriber[6].event[0].condition[0].gte = []
DB.subscriber[6].event[0].condition[0].id = []
DB.subscriber[6].event[0].condition[0].in_ = []
DB.subscriber[6].event[0].condition[0].lt = []
DB.subscriber[6].event[0].condition[0].lte = []
DB.subscriber[6].event[0].condition[0].not_ = []
DB.subscriber[6].event[0].condition[0].or_ = []
DB.subscriber[6].event[0].context = 'player'
DB.subscriber[6].event[0].count = []
DB.subscriber[6].event[0].count.insert(0, None)
DB.subscriber[6].event[0].count[0] = Dummy()
DB.subscriber[6].event[0].count[0].context = 'points.capture'
DB.subscriber[6].event[0].count[0].id = 0
DB.subscriber[6].event[0].count[0].value_ = 400
DB.subscriber[6].event[0].name = 'gain'
DB.subscriber[6].event[0].operation = []
DB.subscriber[6].event[0].type = 'battle'
DB.subscriber[6].event.insert(1, None)
DB.subscriber[6].event[1] = Dummy()
DB.subscriber[6].event[1].condition = []
DB.subscriber[6].event[1].context = 'player'
DB.subscriber[6].event[1].count = []
DB.subscriber[6].event[1].name = 'death'
DB.subscriber[6].event[1].operation = []
DB.subscriber[6].event[1].operation.insert(0, None)
DB.subscriber[6].event[1].operation[0] = Dummy()
DB.subscriber[6].event[1].operation[0].event = []
DB.subscriber[6].event[1].operation[0].id = []
DB.subscriber[6].event[1].operation[0].rollback = true
DB.subscriber[6].event[1].operation[0].self = true
DB.subscriber[6].event[1].type = 'battle'
DB.subscriber[6].modify = []
DB.subscriber[6].name = 'akamatsu'
DB.subscriber[6].operation = []
DB.subscriber[6].send = []
DB.subscriber.insert(7, None)
DB.subscriber[7] = Dummy()
DB.subscriber[7].activity = []
DB.subscriber[7].client = Dummy()
DB.subscriber[7].client.description = Dummy()
DB.subscriber[7].client.description.locale = 'MEDAL_DESCRIPTION_LAMBERTA'
DB.subscriber[7].client.history = Dummy()
DB.subscriber[7].client.history.locale = 'MEDAL_HISTORY_LAMBERTA'
DB.subscriber[7].client.icon = Dummy()
DB.subscriber[7].client.icon.big = 'icons/awards/achievementsInfo/acEpicLambert.dds'
DB.subscriber[7].client.icon.faded = 'icons/awards/achievements/acEpicLambert_Outline.dds'
DB.subscriber[7].client.icon.small = 'icons/awards/achievements/acEpicLambert.dds'
DB.subscriber[7].client.level = Dummy()
DB.subscriber[7].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[7].client.multiple = true
DB.subscriber[7].client.name = Dummy()
DB.subscriber[7].client.name.locale = 'MEDAL_NAME_LAMBERTA'
DB.subscriber[7].client.order = 7
DB.subscriber[7].client.page = 0
DB.subscriber[7].condition = []
DB.subscriber[7].count = []
DB.subscriber[7].event = []
DB.subscriber[7].event.insert(0, None)
DB.subscriber[7].event[0] = Dummy()
DB.subscriber[7].event[0].condition = []
DB.subscriber[7].event[0].condition.insert(0, None)
DB.subscriber[7].event[0].condition[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_ = []
DB.subscriber[7].event[0].condition[0].contains = []
DB.subscriber[7].event[0].condition[0].equal = []
DB.subscriber[7].event[0].condition[0].equal.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[7].event[0].condition[0].equal[0].context = []
DB.subscriber[7].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].context[0] = 'player.plane.type'
DB.subscriber[7].event[0].condition[0].equal[0].value_ = []
DB.subscriber[7].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].value_[0] = 'navy'
DB.subscriber[7].event[0].condition[0].gt = []
DB.subscriber[7].event[0].condition[0].gte = []
DB.subscriber[7].event[0].condition[0].id = []
DB.subscriber[7].event[0].condition[0].in_ = []
DB.subscriber[7].event[0].condition[0].lt = []
DB.subscriber[7].event[0].condition[0].lte = []
DB.subscriber[7].event[0].condition[0].not_ = []
DB.subscriber[7].event[0].condition[0].or_ = []
DB.subscriber[7].event[0].context = 'player'
DB.subscriber[7].event[0].count = []
DB.subscriber[7].event[0].count.insert(0, None)
DB.subscriber[7].event[0].count[0] = Dummy()
DB.subscriber[7].event[0].count[0].context = 'points.capture'
DB.subscriber[7].event[0].count[0].id = 0
DB.subscriber[7].event[0].count[0].value_ = 400
DB.subscriber[7].event[0].name = 'gain'
DB.subscriber[7].event[0].operation = []
DB.subscriber[7].event[0].type = 'battle'
DB.subscriber[7].event.insert(1, None)
DB.subscriber[7].event[1] = Dummy()
DB.subscriber[7].event[1].condition = []
DB.subscriber[7].event[1].context = 'player'
DB.subscriber[7].event[1].count = []
DB.subscriber[7].event[1].name = 'death'
DB.subscriber[7].event[1].operation = []
DB.subscriber[7].event[1].operation.insert(0, None)
DB.subscriber[7].event[1].operation[0] = Dummy()
DB.subscriber[7].event[1].operation[0].event = []
DB.subscriber[7].event[1].operation[0].id = []
DB.subscriber[7].event[1].operation[0].rollback = true
DB.subscriber[7].event[1].operation[0].self = true
DB.subscriber[7].event[1].type = 'battle'
DB.subscriber[7].modify = []
DB.subscriber[7].name = 'lamberta'
DB.subscriber[7].operation = []
DB.subscriber[7].send = []
DB.subscriber.insert(8, None)
DB.subscriber[8] = Dummy()
DB.subscriber[8].activity = []
DB.subscriber[8].client = Dummy()
DB.subscriber[8].client.description = Dummy()
DB.subscriber[8].client.description.locale = 'MEDAL_DESCRIPTION_MCGUIRE'
DB.subscriber[8].client.history = Dummy()
DB.subscriber[8].client.history.locale = 'MEDAL_HISTORY_MCGUIRE'
DB.subscriber[8].client.icon = Dummy()
DB.subscriber[8].client.icon.big = 'icons/awards/achievementsInfo/acEpicMcGuire.dds'
DB.subscriber[8].client.icon.faded = 'icons/awards/achievements/acEpicMcGuire_Outline.dds'
DB.subscriber[8].client.icon.small = 'icons/awards/achievements/acEpicMcGuire.dds'
DB.subscriber[8].client.level = Dummy()
DB.subscriber[8].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[8].client.multiple = true
DB.subscriber[8].client.name = Dummy()
DB.subscriber[8].client.name.locale = 'MEDAL_NAME_MCGUIRE'
DB.subscriber[8].client.order = 8
DB.subscriber[8].client.page = 0
DB.subscriber[8].condition = []
DB.subscriber[8].count = []
DB.subscriber[8].event = []
DB.subscriber[8].event.insert(0, None)
DB.subscriber[8].event[0] = Dummy()
DB.subscriber[8].event[0].condition = []
DB.subscriber[8].event[0].condition.insert(0, None)
DB.subscriber[8].event[0].condition[0] = Dummy()
DB.subscriber[8].event[0].condition[0].and_ = []
DB.subscriber[8].event[0].condition[0].contains = []
DB.subscriber[8].event[0].condition[0].equal = []
DB.subscriber[8].event[0].condition[0].equal.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[8].event[0].condition[0].equal[0].context = []
DB.subscriber[8].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0].context[0] = 'player.plane.type'
DB.subscriber[8].event[0].condition[0].equal[0].value_ = []
DB.subscriber[8].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0].value_[0] = 'heavy.fighter'
DB.subscriber[8].event[0].condition[0].gt = []
DB.subscriber[8].event[0].condition[0].gte = []
DB.subscriber[8].event[0].condition[0].id = []
DB.subscriber[8].event[0].condition[0].in_ = []
DB.subscriber[8].event[0].condition[0].lt = []
DB.subscriber[8].event[0].condition[0].lte = []
DB.subscriber[8].event[0].condition[0].not_ = []
DB.subscriber[8].event[0].condition[0].or_ = []
DB.subscriber[8].event[0].context = 'player'
DB.subscriber[8].event[0].count = []
DB.subscriber[8].event[0].count.insert(0, None)
DB.subscriber[8].event[0].count[0] = Dummy()
DB.subscriber[8].event[0].count[0].context = 'points.capture'
DB.subscriber[8].event[0].count[0].id = 0
DB.subscriber[8].event[0].count[0].value_ = 400
DB.subscriber[8].event[0].name = 'gain'
DB.subscriber[8].event[0].operation = []
DB.subscriber[8].event[0].type = 'battle'
DB.subscriber[8].event.insert(1, None)
DB.subscriber[8].event[1] = Dummy()
DB.subscriber[8].event[1].condition = []
DB.subscriber[8].event[1].context = 'player'
DB.subscriber[8].event[1].count = []
DB.subscriber[8].event[1].name = 'death'
DB.subscriber[8].event[1].operation = []
DB.subscriber[8].event[1].operation.insert(0, None)
DB.subscriber[8].event[1].operation[0] = Dummy()
DB.subscriber[8].event[1].operation[0].event = []
DB.subscriber[8].event[1].operation[0].id = []
DB.subscriber[8].event[1].operation[0].rollback = true
DB.subscriber[8].event[1].operation[0].self = true
DB.subscriber[8].event[1].type = 'battle'
DB.subscriber[8].modify = []
DB.subscriber[8].name = 'mcguire'
DB.subscriber[8].operation = []
DB.subscriber[8].send = []
DB.subscriber.insert(9, None)
DB.subscriber[9] = Dummy()
DB.subscriber[9].activity = []
DB.subscriber[9].client = Dummy()
DB.subscriber[9].client.description = Dummy()
DB.subscriber[9].client.description.locale = 'MEDAL_DESCRIPTION_YEFIMOV'
DB.subscriber[9].client.history = Dummy()
DB.subscriber[9].client.history.locale = 'MEDAL_HISTORY_YEFIMOV'
DB.subscriber[9].client.icon = Dummy()
DB.subscriber[9].client.icon.big = 'icons/awards/achievementsInfo/acEpicYefimov.dds'
DB.subscriber[9].client.icon.faded = 'icons/awards/achievements/acEpicYefimov_Outline.dds'
DB.subscriber[9].client.icon.small = 'icons/awards/achievements/acEpicYefimov.dds'
DB.subscriber[9].client.level = Dummy()
DB.subscriber[9].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[9].client.multiple = true
DB.subscriber[9].client.name = Dummy()
DB.subscriber[9].client.name.locale = 'MEDAL_NAME_YEFIMOV'
DB.subscriber[9].client.order = 9
DB.subscriber[9].client.page = 0
DB.subscriber[9].condition = []
DB.subscriber[9].count = []
DB.subscriber[9].event = []
DB.subscriber[9].event.insert(0, None)
DB.subscriber[9].event[0] = Dummy()
DB.subscriber[9].event[0].condition = []
DB.subscriber[9].event[0].condition.insert(0, None)
DB.subscriber[9].event[0].condition[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_ = []
DB.subscriber[9].event[0].condition[0].and_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].and_ = []
DB.subscriber[9].event[0].condition[0].and_[0].contains = []
DB.subscriber[9].event[0].condition[0].and_[0].equal = []
DB.subscriber[9].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.object'
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_[0] = 'ground'
DB.subscriber[9].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context[0] = 'player.plane.type'
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_[0] = 'assault'
DB.subscriber[9].event[0].condition[0].and_[0].gt = []
DB.subscriber[9].event[0].condition[0].and_[0].gte = []
DB.subscriber[9].event[0].condition[0].and_[0].id = []
DB.subscriber[9].event[0].condition[0].and_[0].in_ = []
DB.subscriber[9].event[0].condition[0].and_[0].lt = []
DB.subscriber[9].event[0].condition[0].and_[0].lte = []
DB.subscriber[9].event[0].condition[0].and_[0].not_ = []
DB.subscriber[9].event[0].condition[0].and_[0].or_ = []
DB.subscriber[9].event[0].condition[0].contains = []
DB.subscriber[9].event[0].condition[0].equal = []
DB.subscriber[9].event[0].condition[0].gt = []
DB.subscriber[9].event[0].condition[0].gte = []
DB.subscriber[9].event[0].condition[0].id = []
DB.subscriber[9].event[0].condition[0].in_ = []
DB.subscriber[9].event[0].condition[0].lt = []
DB.subscriber[9].event[0].condition[0].lte = []
DB.subscriber[9].event[0].condition[0].not_ = []
DB.subscriber[9].event[0].condition[0].or_ = []
DB.subscriber[9].event[0].context = 'player'
DB.subscriber[9].event[0].count = []
DB.subscriber[9].event[0].count.insert(0, None)
DB.subscriber[9].event[0].count[0] = Dummy()
DB.subscriber[9].event[0].count[0].context = 'points.capture'
DB.subscriber[9].event[0].count[0].id = 0
DB.subscriber[9].event[0].count[0].value_ = 400
DB.subscriber[9].event[0].name = 'gain'
DB.subscriber[9].event[0].operation = []
DB.subscriber[9].event[0].type = 'battle'
DB.subscriber[9].event.insert(1, None)
DB.subscriber[9].event[1] = Dummy()
DB.subscriber[9].event[1].condition = []
DB.subscriber[9].event[1].context = 'player'
DB.subscriber[9].event[1].count = []
DB.subscriber[9].event[1].name = 'death'
DB.subscriber[9].event[1].operation = []
DB.subscriber[9].event[1].operation.insert(0, None)
DB.subscriber[9].event[1].operation[0] = Dummy()
DB.subscriber[9].event[1].operation[0].event = []
DB.subscriber[9].event[1].operation[0].id = []
DB.subscriber[9].event[1].operation[0].rollback = true
DB.subscriber[9].event[1].operation[0].self = true
DB.subscriber[9].event[1].type = 'battle'
DB.subscriber[9].modify = []
DB.subscriber[9].name = 'yefimov'
DB.subscriber[9].operation = []
DB.subscriber[9].send = []
DB.subscriber.insert(10, None)
DB.subscriber[10] = Dummy()
DB.subscriber[10].activity = []
DB.subscriber[10].client = Dummy()
DB.subscriber[10].client.description = Dummy()
DB.subscriber[10].client.description.locale = 'MEDAL_DESCRIPTION_DULITTLA'
DB.subscriber[10].client.history = Dummy()
DB.subscriber[10].client.history.locale = 'MEDAL_HISTORY_DULITTLA'
DB.subscriber[10].client.icon = Dummy()
DB.subscriber[10].client.icon.big = 'icons/awards/achievementsInfo/acEpicDoolittle.dds'
DB.subscriber[10].client.icon.faded = 'icons/awards/achievements/acEpicDoolittle_Outline.dds'
DB.subscriber[10].client.icon.small = 'icons/awards/achievements/acEpicDoolittle.dds'
DB.subscriber[10].client.level = Dummy()
DB.subscriber[10].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[10].client.multiple = true
DB.subscriber[10].client.name = Dummy()
DB.subscriber[10].client.name.locale = 'MEDAL_NAME_DULITTLA'
DB.subscriber[10].client.order = 10
DB.subscriber[10].client.page = 0
DB.subscriber[10].condition = []
DB.subscriber[10].count = []
DB.subscriber[10].event = []
DB.subscriber[10].event.insert(0, None)
DB.subscriber[10].event[0] = Dummy()
DB.subscriber[10].event[0].condition = []
DB.subscriber[10].event[0].condition.insert(0, None)
DB.subscriber[10].event[0].condition[0] = Dummy()
DB.subscriber[10].event[0].condition[0].and_ = []
DB.subscriber[10].event[0].condition[0].and_.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[10].event[0].condition[0].and_[0].and_ = []
DB.subscriber[10].event[0].condition[0].and_[0].contains = []
DB.subscriber[10].event[0].condition[0].and_[0].equal = []
DB.subscriber[10].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.object'
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[0].value_[0] = 'ground'
DB.subscriber[10].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].context[0] = 'player.plane.type'
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[10].event[0].condition[0].and_[0].equal[1].value_[0] = 'bomber'
DB.subscriber[10].event[0].condition[0].and_[0].gt = []
DB.subscriber[10].event[0].condition[0].and_[0].gte = []
DB.subscriber[10].event[0].condition[0].and_[0].id = []
DB.subscriber[10].event[0].condition[0].and_[0].in_ = []
DB.subscriber[10].event[0].condition[0].and_[0].lt = []
DB.subscriber[10].event[0].condition[0].and_[0].lte = []
DB.subscriber[10].event[0].condition[0].and_[0].not_ = []
DB.subscriber[10].event[0].condition[0].and_[0].or_ = []
DB.subscriber[10].event[0].condition[0].contains = []
DB.subscriber[10].event[0].condition[0].equal = []
DB.subscriber[10].event[0].condition[0].gt = []
DB.subscriber[10].event[0].condition[0].gte = []
DB.subscriber[10].event[0].condition[0].id = []
DB.subscriber[10].event[0].condition[0].in_ = []
DB.subscriber[10].event[0].condition[0].lt = []
DB.subscriber[10].event[0].condition[0].lte = []
DB.subscriber[10].event[0].condition[0].not_ = []
DB.subscriber[10].event[0].condition[0].or_ = []
DB.subscriber[10].event[0].context = 'player'
DB.subscriber[10].event[0].count = []
DB.subscriber[10].event[0].count.insert(0, None)
DB.subscriber[10].event[0].count[0] = Dummy()
DB.subscriber[10].event[0].count[0].context = 'points.capture'
DB.subscriber[10].event[0].count[0].id = 0
DB.subscriber[10].event[0].count[0].value_ = 400
DB.subscriber[10].event[0].name = 'gain'
DB.subscriber[10].event[0].operation = []
DB.subscriber[10].event[0].type = 'battle'
DB.subscriber[10].event.insert(1, None)
DB.subscriber[10].event[1] = Dummy()
DB.subscriber[10].event[1].condition = []
DB.subscriber[10].event[1].context = 'player'
DB.subscriber[10].event[1].count = []
DB.subscriber[10].event[1].name = 'death'
DB.subscriber[10].event[1].operation = []
DB.subscriber[10].event[1].operation.insert(0, None)
DB.subscriber[10].event[1].operation[0] = Dummy()
DB.subscriber[10].event[1].operation[0].event = []
DB.subscriber[10].event[1].operation[0].id = []
DB.subscriber[10].event[1].operation[0].rollback = true
DB.subscriber[10].event[1].operation[0].self = true
DB.subscriber[10].event[1].type = 'battle'
DB.subscriber[10].modify = []
DB.subscriber[10].name = 'dulittla'
DB.subscriber[10].operation = []
DB.subscriber[10].send = []
DB.subscriber.insert(11, None)
DB.subscriber[11] = Dummy()
DB.subscriber[11].activity = []
DB.subscriber[11].client = Dummy()
DB.subscriber[11].client.description = Dummy()
DB.subscriber[11].client.description.locale = 'MEDAL_DESCRIPTION_KOJEDUBA'
DB.subscriber[11].client.history = Dummy()
DB.subscriber[11].client.history.locale = 'MEDAL_HISTORY_KOJEDUBA'
DB.subscriber[11].client.icon = Dummy()
DB.subscriber[11].client.icon.big = 'icons/awards/achievementsInfo/acEpicKozhedub.dds'
DB.subscriber[11].client.icon.faded = 'icons/awards/achievements/acEpicKozhedub_Outline.dds'
DB.subscriber[11].client.icon.small = 'icons/awards/achievements/acEpicKozhedub.dds'
DB.subscriber[11].client.level = Dummy()
DB.subscriber[11].client.level.locale = 'MEDAL_LEVEL_LIMIT'
DB.subscriber[11].client.multiple = true
DB.subscriber[11].client.name = Dummy()
DB.subscriber[11].client.name.locale = 'MEDAL_NAME_KOJEDUBA'
DB.subscriber[11].client.order = 11
DB.subscriber[11].client.page = 0
DB.subscriber[11].condition = []
DB.subscriber[11].count = []
DB.subscriber[11].event = []
DB.subscriber[11].event.insert(0, None)
DB.subscriber[11].event[0] = Dummy()
DB.subscriber[11].event[0].condition = []
DB.subscriber[11].event[0].condition.insert(0, None)
DB.subscriber[11].event[0].condition[0] = Dummy()
DB.subscriber[11].event[0].condition[0].and_ = []
DB.subscriber[11].event[0].condition[0].contains = []
DB.subscriber[11].event[0].condition[0].equal = []
DB.subscriber[11].event[0].condition[0].equal.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[11].event[0].condition[0].equal[0].context = []
DB.subscriber[11].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].context[0] = 'victim.type'
DB.subscriber[11].event[0].condition[0].equal[0].value_ = []
DB.subscriber[11].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].value_[0] = 'player'
DB.subscriber[11].event[0].condition[0].gt = []
DB.subscriber[11].event[0].condition[0].gte = []
DB.subscriber[11].event[0].condition[0].id = []
DB.subscriber[11].event[0].condition[0].in_ = []
DB.subscriber[11].event[0].condition[0].lt = []
DB.subscriber[11].event[0].condition[0].lte = []
DB.subscriber[11].event[0].condition[0].not_ = []
DB.subscriber[11].event[0].condition[0].or_ = []
DB.subscriber[11].event[0].context = 'player'
DB.subscriber[11].event[0].count = []
DB.subscriber[11].event[0].count.insert(0, None)
DB.subscriber[11].event[0].count[0] = Dummy()
DB.subscriber[11].event[0].count[0].id = 0
DB.subscriber[11].event[0].count[0].value_ = 5
DB.subscriber[11].event[0].name = 'kill'
DB.subscriber[11].event[0].operation = []
DB.subscriber[11].event[0].type = 'battle'
DB.subscriber[11].event.insert(1, None)
DB.subscriber[11].event[1] = Dummy()
DB.subscriber[11].event[1].condition = []
DB.subscriber[11].event[1].context = 'player'
DB.subscriber[11].event[1].count = []
DB.subscriber[11].event[1].count.insert(0, None)
DB.subscriber[11].event[1].count[0] = Dummy()
DB.subscriber[11].event[1].count[0].value_ = 1
DB.subscriber[11].event[1].name = 'result'
DB.subscriber[11].event[1].operation = []
DB.subscriber[11].event[1].type = 'battle'
DB.subscriber[11].event.insert(2, None)
DB.subscriber[11].event[2] = Dummy()
DB.subscriber[11].event[2].condition = []
DB.subscriber[11].event[2].context = 'player'
DB.subscriber[11].event[2].count = []
DB.subscriber[11].event[2].count.insert(0, None)
DB.subscriber[11].event[2].count[0] = Dummy()
DB.subscriber[11].event[2].count[0].value_ = 1
DB.subscriber[11].event[2].name = 'stormfront'
DB.subscriber[11].event[2].operation = []
DB.subscriber[11].event[2].operation.insert(0, None)
DB.subscriber[11].event[2].operation[0] = Dummy()
DB.subscriber[11].event[2].operation[0].event = []
DB.subscriber[11].event[2].operation[0].id = []
DB.subscriber[11].event[2].operation[0].processors = Dummy()
DB.subscriber[11].event[2].operation[0].processors.count = []
DB.subscriber[11].event[2].operation[0].processors.count.insert(0, None)
DB.subscriber[11].event[2].operation[0].processors.count[0] = 0
DB.subscriber[11].event[2].operation[0].processors.event = []
DB.subscriber[11].event[2].operation[0].processors.transaction = []
DB.subscriber[11].event[2].operation[0].rollback = true
DB.subscriber[11].event[2].operation[0].self = true
DB.subscriber[11].event[2].type = 'battle'
DB.subscriber[11].event.insert(3, None)
DB.subscriber[11].event[3] = Dummy()
DB.subscriber[11].event[3].condition = []
DB.subscriber[11].event[3].context = 'player'
DB.subscriber[11].event[3].count = []
DB.subscriber[11].event[3].name = 'death'
DB.subscriber[11].event[3].operation = []
DB.subscriber[11].event[3].operation.insert(0, None)
DB.subscriber[11].event[3].operation[0] = Dummy()
DB.subscriber[11].event[3].operation[0].event = []
DB.subscriber[11].event[3].operation[0].id = []
DB.subscriber[11].event[3].operation[0].rollback = true
DB.subscriber[11].event[3].operation[0].self = true
DB.subscriber[11].event[3].type = 'battle'
DB.subscriber[11].modify = []
DB.subscriber[11].name = 'kojeduba'
DB.subscriber[11].operation = []
DB.subscriber[11].send = []
DB.subscriber[0].id = -1089004620
DB.subscriber[1].id = -1112248543
DB.subscriber[2].id = 170115666
DB.subscriber[3].id = -276456889
DB.subscriber[4].id = -836674222
DB.subscriber[5].id = -1922574159
DB.subscriber[6].id = -943598293
DB.subscriber[7].id = 1470673654
DB.subscriber[8].id = -1396895200
DB.subscriber[9].id = -383690886
DB.subscriber[10].id = 306060851
DB.subscriber[11].id = 297655780
DB.subscriber[0].eventIds = (761754430, 35456563)
DB.subscriber[1].eventIds = (-104890988, -218451730, 615894436)
DB.subscriber[4].eventIds = (-104890988, -218451730, 615894436)
DB.subscriber[2].eventIds = (-218451730, 615894436, -104890988)
DB.subscriber[3].eventIds = (-1370837730, -218451730, 615894436)
DB.subscriber[5].eventIds = (-104890988,
 -1370837730,
 -218451730,
 615894436)
DB.subscriber[6].eventIds = (771950333, 615894436)
DB.subscriber[7].eventIds = (771950333, 615894436)
DB.subscriber[8].eventIds = (771950333, 615894436)
DB.subscriber[9].eventIds = (771950333, 615894436)
DB.subscriber[10].eventIds = (771950333, 615894436)
DB.subscriber[11].eventIds = (-104890988,
 516184373,
 -1789343170,
 615894436)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {-1089004620: (DB.subscriber[0],),
                                   -1112248543: (DB.subscriber[1],),
                                   170115666: (DB.subscriber[2],),
                                   -276456889: (DB.subscriber[3],),
                                   -836674222: (DB.subscriber[4],),
                                   -1922574159: (DB.subscriber[5],),
                                   -943598293: (DB.subscriber[6],),
                                   1470673654: (DB.subscriber[7],),
                                   -1396895200: (DB.subscriber[8],),
                                   -383690886: (DB.subscriber[9],),
                                   306060851: (DB.subscriber[10],),
                                   297655780: (DB.subscriber[11],)},
                            'name': {'reset': (DB.subscriber[0],),
                                     'marcel': (DB.subscriber[1],),
                                     'maccambell': (DB.subscriber[2],),
                                     'lang': (DB.subscriber[3],),
                                     'golubev': (DB.subscriber[4],),
                                     'habrezki': (DB.subscriber[5],),
                                     'akamatsu': (DB.subscriber[6],),
                                     'lamberta': (DB.subscriber[7],),
                                     'mcguire': (DB.subscriber[8],),
                                     'yefimov': (DB.subscriber[9],),
                                     'dulittla': (DB.subscriber[10],),
                                     'kojeduba': (DB.subscriber[11],)},
                            'type': {'achievement.reset': (DB.subscriber[0],),
                                     'achievement': (DB.subscriber[1],
                                                     DB.subscriber[2],
                                                     DB.subscriber[3],
                                                     DB.subscriber[4],
                                                     DB.subscriber[5],
                                                     DB.subscriber[6],
                                                     DB.subscriber[7],
                                                     DB.subscriber[8],
                                                     DB.subscriber[9],
                                                     DB.subscriber[10],
                                                     DB.subscriber[11])},
                            'group': {'epic': (DB.subscriber[0],
                                               DB.subscriber[1],
                                               DB.subscriber[2],
                                               DB.subscriber[3],
                                               DB.subscriber[4],
                                               DB.subscriber[5],
                                               DB.subscriber[6],
                                               DB.subscriber[7],
                                               DB.subscriber[8],
                                               DB.subscriber[9],
                                               DB.subscriber[10],
                                               DB.subscriber[11])},
                            'eventIds': {(761754430, 35456563): (DB.subscriber[0],),
                                         (-104890988, -218451730, 615894436): (DB.subscriber[1], DB.subscriber[4]),
                                         (-218451730, 615894436, -104890988): (DB.subscriber[2],),
                                         (-1370837730, -218451730, 615894436): (DB.subscriber[3],),
                                         (-104890988,
 -1370837730,
 -218451730,
 615894436): (DB.subscriber[5],),
                                         (771950333, 615894436): (DB.subscriber[6],
                                                                  DB.subscriber[7],
                                                                  DB.subscriber[8],
                                                                  DB.subscriber[9],
                                                                  DB.subscriber[10]),
                                         (-104890988,
 516184373,
 -1789343170,
 615894436): (DB.subscriber[11],)},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}