# Embedded file name: scripts/client/_ge_achievements_memorable.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy():
    pass


isServerDatabase = False

class AMMO_TYPE():
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy():
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType():
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE():
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE():
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.header = Dummy()
DB.header.client = Dummy()
DB.header.client.place = 'left'
DB.header.condition = []
DB.header.count = []
DB.header.event = []
DB.header.group = 'memorable'
DB.header.markers = Dummy()
DB.header.markers.group = 'memorable'
DB.header.modify = []
DB.header.operation = []
DB.header.send = []
DB.header.server = Dummy()
DB.header.server.active = true
DB.header.server.scope = []
DB.header.server.scope.insert(0, None)
DB.header.server.scope[0] = 'player'
DB.header.type = 'achievement'
DB.include = Dummy()
DB.include.condition = []
DB.include.condition.insert(0, None)
DB.include.condition[0] = Dummy()
DB.include.condition[0].and_ = []
DB.include.condition[0].and_.insert(0, None)
DB.include.condition[0].and_[0] = Dummy()
DB.include.condition[0].and_[0].and_ = []
DB.include.condition[0].and_[0].contains = []
DB.include.condition[0].and_[0].equal = []
DB.include.condition[0].and_[0].equal.insert(0, None)
DB.include.condition[0].and_[0].equal[0] = Dummy()
DB.include.condition[0].and_[0].equal[0].context = []
DB.include.condition[0].and_[0].equal[0].context.insert(0, None)
DB.include.condition[0].and_[0].equal[0].context[0] = 'arena.type'
DB.include.condition[0].and_[0].equal[0].value_ = []
DB.include.condition[0].and_[0].equal[0].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[0].value_[0] = 'normal'
DB.include.condition[0].and_[0].equal.insert(1, None)
DB.include.condition[0].and_[0].equal[1] = Dummy()
DB.include.condition[0].and_[0].equal[1].context = []
DB.include.condition[0].and_[0].equal[1].context.insert(0, None)
DB.include.condition[0].and_[0].equal[1].context[0] = 'arena.source'
DB.include.condition[0].and_[0].equal[1].value_ = []
DB.include.condition[0].and_[0].equal[1].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[1].value_[0] = 'player'
DB.include.condition[0].and_[0].gt = []
DB.include.condition[0].and_[0].gte = []
DB.include.condition[0].and_[0].id = []
DB.include.condition[0].and_[0].in_ = []
DB.include.condition[0].and_[0].lt = []
DB.include.condition[0].and_[0].lte = []
DB.include.condition[0].and_[0].not_ = []
DB.include.condition[0].and_[0].or_ = []
DB.include.condition[0].contains = []
DB.include.condition[0].equal = []
DB.include.condition[0].gt = []
DB.include.condition[0].gte = []
DB.include.condition[0].id = []
DB.include.condition[0].in_ = []
DB.include.condition[0].lt = []
DB.include.condition[0].lte = []
DB.include.condition[0].not_ = []
DB.include.condition[0].or_ = []
DB.include.count = []
DB.include.event = []
DB.include.metadata = Dummy()
DB.include.metadata.doneCount = true
DB.include.metadata.event = []
DB.include.metadata.firstDoneTime = true
DB.include.metadata.lastDoneTime = true
DB.include.modify = []
DB.include.operation = []
DB.include.send = []
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].client = Dummy()
DB.subscriber[0].client.description = Dummy()
DB.subscriber[0].client.description.locale = 'MEDAL_DESCRIPTION_IMPACT_FROM_THE_SKY'
DB.subscriber[0].client.icon = Dummy()
DB.subscriber[0].client.icon.big = 'icons/awards/achievementsInfo/acComImpactFromTheSky.dds'
DB.subscriber[0].client.icon.faded = 'icons/awards/achievements/acComImpactFromTheSky_Outline.dds'
DB.subscriber[0].client.icon.small = 'icons/awards/achievements/acComImpactFromTheSky.dds'
DB.subscriber[0].client.multiple = false
DB.subscriber[0].client.name = Dummy()
DB.subscriber[0].client.name.locale = 'MEDAL_NAME_IMPACT_FROM_THE_SKY'
DB.subscriber[0].client.order = 1
DB.subscriber[0].client.page = 0
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].condition.insert(0, None)
DB.subscriber[0].event[0].condition[0] = Dummy()
DB.subscriber[0].event[0].condition[0].and_ = []
DB.subscriber[0].event[0].condition[0].contains = []
DB.subscriber[0].event[0].condition[0].equal = []
DB.subscriber[0].event[0].condition[0].equal.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[0].event[0].condition[0].equal[0].context = []
DB.subscriber[0].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0].context[0] = 'victim.type'
DB.subscriber[0].event[0].condition[0].equal[0].value_ = []
DB.subscriber[0].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0].value_[0] = 'bomber'
DB.subscriber[0].event[0].condition[0].gt = []
DB.subscriber[0].event[0].condition[0].gte = []
DB.subscriber[0].event[0].condition[0].id = []
DB.subscriber[0].event[0].condition[0].in_ = []
DB.subscriber[0].event[0].condition[0].lt = []
DB.subscriber[0].event[0].condition[0].lte = []
DB.subscriber[0].event[0].condition[0].not_ = []
DB.subscriber[0].event[0].condition[0].or_ = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].count.insert(0, None)
DB.subscriber[0].event[0].count[0] = Dummy()
DB.subscriber[0].event[0].count[0].id = 0
DB.subscriber[0].event[0].count[0].value_ = 1
DB.subscriber[0].event[0].name = 'kill'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].type = 'battle'
DB.subscriber[0].modify = []
DB.subscriber[0].name = 'impactfromthesky'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber.insert(1, None)
DB.subscriber[1] = Dummy()
DB.subscriber[1].client = Dummy()
DB.subscriber[1].client.description = Dummy()
DB.subscriber[1].client.description.locale = 'MEDAL_DESCRIPTION_KNIGHT'
DB.subscriber[1].client.icon = Dummy()
DB.subscriber[1].client.icon.big = 'icons/awards/achievementsInfo/acComKnight.dds'
DB.subscriber[1].client.icon.faded = 'icons/awards/achievements/acComKnight_Outline.dds'
DB.subscriber[1].client.icon.small = 'icons/awards/achievements/acComKnight.dds'
DB.subscriber[1].client.level = Dummy()
DB.subscriber[1].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[1].client.multiple = false
DB.subscriber[1].client.name = Dummy()
DB.subscriber[1].client.name.locale = 'MEDAL_NAME_KNIGHT'
DB.subscriber[1].client.order = 2
DB.subscriber[1].client.page = 0
DB.subscriber[1].condition = []
DB.subscriber[1].condition.insert(0, None)
DB.subscriber[1].condition[0] = Dummy()
DB.subscriber[1].condition[0].and_ = []
DB.subscriber[1].condition[0].contains = []
DB.subscriber[1].condition[0].equal = []
DB.subscriber[1].condition[0].gt = []
DB.subscriber[1].condition[0].gte = []
DB.subscriber[1].condition[0].id = []
DB.subscriber[1].condition[0].in_ = []
DB.subscriber[1].condition[0].lt = []
DB.subscriber[1].condition[0].lte = []
DB.subscriber[1].condition[0].lte.insert(0, None)
DB.subscriber[1].condition[0].lte[0] = Dummy()
DB.subscriber[1].condition[0].lte[0].context = []
DB.subscriber[1].condition[0].lte[0].context.insert(0, None)
DB.subscriber[1].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[1].condition[0].lte[0].value_ = []
DB.subscriber[1].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[1].condition[0].lte[0].value_[0] = '3'
DB.subscriber[1].condition[0].not_ = []
DB.subscriber[1].condition[0].or_ = []
DB.subscriber[1].count = []
DB.subscriber[1].event = []
DB.subscriber[1].event.insert(0, None)
DB.subscriber[1].event[0] = Dummy()
DB.subscriber[1].event[0].condition = []
DB.subscriber[1].event[0].condition.insert(0, None)
DB.subscriber[1].event[0].condition[0] = Dummy()
DB.subscriber[1].event[0].condition[0].and_ = []
DB.subscriber[1].event[0].condition[0].contains = []
DB.subscriber[1].event[0].condition[0].equal = []
DB.subscriber[1].event[0].condition[0].equal.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[1].event[0].condition[0].equal[0].context = []
DB.subscriber[1].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0].context[0] = 'victim.type'
DB.subscriber[1].event[0].condition[0].equal[0].value_ = []
DB.subscriber[1].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0].value_[0] = 'defender'
DB.subscriber[1].event[0].condition[0].gt = []
DB.subscriber[1].event[0].condition[0].gte = []
DB.subscriber[1].event[0].condition[0].id = []
DB.subscriber[1].event[0].condition[0].in_ = []
DB.subscriber[1].event[0].condition[0].lt = []
DB.subscriber[1].event[0].condition[0].lte = []
DB.subscriber[1].event[0].condition[0].not_ = []
DB.subscriber[1].event[0].condition[0].or_ = []
DB.subscriber[1].event[0].context = 'player'
DB.subscriber[1].event[0].count = []
DB.subscriber[1].event[0].count.insert(0, None)
DB.subscriber[1].event[0].count[0] = Dummy()
DB.subscriber[1].event[0].count[0].id = 0
DB.subscriber[1].event[0].count[0].value_ = 1
DB.subscriber[1].event[0].name = 'kill'
DB.subscriber[1].event[0].operation = []
DB.subscriber[1].event[0].type = 'battle'
DB.subscriber[1].modify = []
DB.subscriber[1].name = 'knight'
DB.subscriber[1].operation = []
DB.subscriber[1].send = []
DB.subscriber.insert(2, None)
DB.subscriber[2] = Dummy()
DB.subscriber[2].client = Dummy()
DB.subscriber[2].client.description = Dummy()
DB.subscriber[2].client.description.locale = 'MEDAL_DESCRIPTION_PATROL'
DB.subscriber[2].client.icon = Dummy()
DB.subscriber[2].client.icon.big = 'icons/awards/achievementsInfo/acComPatrol.dds'
DB.subscriber[2].client.icon.faded = 'icons/awards/achievements/acComPatrol_Outline.dds'
DB.subscriber[2].client.icon.small = 'icons/awards/achievements/acComPatrol.dds'
DB.subscriber[2].client.level = Dummy()
DB.subscriber[2].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[2].client.multiple = false
DB.subscriber[2].client.name = Dummy()
DB.subscriber[2].client.name.locale = 'MEDAL_NAME_PATROL'
DB.subscriber[2].client.order = 3
DB.subscriber[2].client.page = 0
DB.subscriber[2].condition = []
DB.subscriber[2].condition.insert(0, None)
DB.subscriber[2].condition[0] = Dummy()
DB.subscriber[2].condition[0].and_ = []
DB.subscriber[2].condition[0].contains = []
DB.subscriber[2].condition[0].equal = []
DB.subscriber[2].condition[0].gt = []
DB.subscriber[2].condition[0].gte = []
DB.subscriber[2].condition[0].id = []
DB.subscriber[2].condition[0].in_ = []
DB.subscriber[2].condition[0].lt = []
DB.subscriber[2].condition[0].lte = []
DB.subscriber[2].condition[0].lte.insert(0, None)
DB.subscriber[2].condition[0].lte[0] = Dummy()
DB.subscriber[2].condition[0].lte[0].context = []
DB.subscriber[2].condition[0].lte[0].context.insert(0, None)
DB.subscriber[2].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[2].condition[0].lte[0].value_ = []
DB.subscriber[2].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[2].condition[0].lte[0].value_[0] = '3'
DB.subscriber[2].condition[0].not_ = []
DB.subscriber[2].condition[0].or_ = []
DB.subscriber[2].count = []
DB.subscriber[2].event = []
DB.subscriber[2].event.insert(0, None)
DB.subscriber[2].event[0] = Dummy()
DB.subscriber[2].event[0].condition = []
DB.subscriber[2].event[0].context = 'player'
DB.subscriber[2].event[0].count = []
DB.subscriber[2].event[0].name = 'finish'
DB.subscriber[2].event[0].operation = []
DB.subscriber[2].event[0].operation.insert(0, None)
DB.subscriber[2].event[0].operation[0] = Dummy()
DB.subscriber[2].event[0].operation[0].event = []
DB.subscriber[2].event[0].operation[0].id = []
DB.subscriber[2].event[0].operation[0].rollback = true
DB.subscriber[2].event[0].operation[0].self = true
DB.subscriber[2].event[0].type = 'battle'
DB.subscriber[2].event.insert(1, None)
DB.subscriber[2].event[1] = Dummy()
DB.subscriber[2].event[1].condition = []
DB.subscriber[2].event[1].context = 'player'
DB.subscriber[2].event[1].count = []
DB.subscriber[2].event[1].count.insert(0, None)
DB.subscriber[2].event[1].count[0] = Dummy()
DB.subscriber[2].event[1].count[0].id = 0
DB.subscriber[2].event[1].count[0].value_ = 2
DB.subscriber[2].event[1].name = 'kill'
DB.subscriber[2].event[1].operation = []
DB.subscriber[2].event[1].type = 'battle'
DB.subscriber[2].event.insert(2, None)
DB.subscriber[2].event[2] = Dummy()
DB.subscriber[2].event[2].condition = []
DB.subscriber[2].event[2].context = 'player'
DB.subscriber[2].event[2].count = []
DB.subscriber[2].event[2].count.insert(0, None)
DB.subscriber[2].event[2].count[0] = Dummy()
DB.subscriber[2].event[2].count[0].id = 1
DB.subscriber[2].event[2].count[0].value_ = 2
DB.subscriber[2].event[2].name = 'destroy'
DB.subscriber[2].event[2].operation = []
DB.subscriber[2].event[2].type = 'battle'
DB.subscriber[2].modify = []
DB.subscriber[2].name = 'patrol'
DB.subscriber[2].operation = []
DB.subscriber[2].send = []
DB.subscriber.insert(3, None)
DB.subscriber[3] = Dummy()
DB.subscriber[3].client = Dummy()
DB.subscriber[3].client.description = Dummy()
DB.subscriber[3].client.description.locale = 'MEDAL_DESCRIPTION_GUARD'
DB.subscriber[3].client.icon = Dummy()
DB.subscriber[3].client.icon.big = 'icons/awards/achievementsInfo/acComGuard.dds'
DB.subscriber[3].client.icon.faded = 'icons/awards/achievements/acComGuard_Outline.dds'
DB.subscriber[3].client.icon.small = 'icons/awards/achievements/acComGuard.dds'
DB.subscriber[3].client.level = Dummy()
DB.subscriber[3].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[3].client.multiple = false
DB.subscriber[3].client.name = Dummy()
DB.subscriber[3].client.name.locale = 'MEDAL_NAME_GUARD'
DB.subscriber[3].client.order = 4
DB.subscriber[3].client.page = 0
DB.subscriber[3].condition = []
DB.subscriber[3].condition.insert(0, None)
DB.subscriber[3].condition[0] = Dummy()
DB.subscriber[3].condition[0].and_ = []
DB.subscriber[3].condition[0].contains = []
DB.subscriber[3].condition[0].equal = []
DB.subscriber[3].condition[0].gt = []
DB.subscriber[3].condition[0].gte = []
DB.subscriber[3].condition[0].id = []
DB.subscriber[3].condition[0].in_ = []
DB.subscriber[3].condition[0].lt = []
DB.subscriber[3].condition[0].lte = []
DB.subscriber[3].condition[0].lte.insert(0, None)
DB.subscriber[3].condition[0].lte[0] = Dummy()
DB.subscriber[3].condition[0].lte[0].context = []
DB.subscriber[3].condition[0].lte[0].context.insert(0, None)
DB.subscriber[3].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[3].condition[0].lte[0].value_ = []
DB.subscriber[3].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[3].condition[0].lte[0].value_[0] = '3'
DB.subscriber[3].condition[0].not_ = []
DB.subscriber[3].condition[0].or_ = []
DB.subscriber[3].count = []
DB.subscriber[3].event = []
DB.subscriber[3].event.insert(0, None)
DB.subscriber[3].event[0] = Dummy()
DB.subscriber[3].event[0].condition = []
DB.subscriber[3].event[0].context = 'player'
DB.subscriber[3].event[0].count = []
DB.subscriber[3].event[0].count.insert(0, None)
DB.subscriber[3].event[0].count[0] = Dummy()
DB.subscriber[3].event[0].count[0].id = 0
DB.subscriber[3].event[0].count[0].value_ = 1
DB.subscriber[3].event[0].name = 'destroy'
DB.subscriber[3].event[0].operation = []
DB.subscriber[3].event[0].type = 'battle'
DB.subscriber[3].modify = []
DB.subscriber[3].name = 'guard'
DB.subscriber[3].operation = []
DB.subscriber[3].send = []
DB.subscriber.insert(4, None)
DB.subscriber[4] = Dummy()
DB.subscriber[4].client = Dummy()
DB.subscriber[4].client.description = Dummy()
DB.subscriber[4].client.description.locale = 'MEDAL_DESCRIPTION_DARING_SWOOP'
DB.subscriber[4].client.icon = Dummy()
DB.subscriber[4].client.icon.big = 'icons/awards/achievementsInfo/acComDaringSwoop.dds'
DB.subscriber[4].client.icon.faded = 'icons/awards/achievements/acComDaringSwoop_Outline.dds'
DB.subscriber[4].client.icon.small = 'icons/awards/achievements/acComDaringSwoop.dds'
DB.subscriber[4].client.level = Dummy()
DB.subscriber[4].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[4].client.multiple = false
DB.subscriber[4].client.name = Dummy()
DB.subscriber[4].client.name.locale = 'MEDAL_NAME_DARING_SWOOP'
DB.subscriber[4].client.order = 5
DB.subscriber[4].client.page = 0
DB.subscriber[4].condition = []
DB.subscriber[4].condition.insert(0, None)
DB.subscriber[4].condition[0] = Dummy()
DB.subscriber[4].condition[0].and_ = []
DB.subscriber[4].condition[0].contains = []
DB.subscriber[4].condition[0].equal = []
DB.subscriber[4].condition[0].gt = []
DB.subscriber[4].condition[0].gte = []
DB.subscriber[4].condition[0].id = []
DB.subscriber[4].condition[0].in_ = []
DB.subscriber[4].condition[0].lt = []
DB.subscriber[4].condition[0].lte = []
DB.subscriber[4].condition[0].lte.insert(0, None)
DB.subscriber[4].condition[0].lte[0] = Dummy()
DB.subscriber[4].condition[0].lte[0].context = []
DB.subscriber[4].condition[0].lte[0].context.insert(0, None)
DB.subscriber[4].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[4].condition[0].lte[0].value_ = []
DB.subscriber[4].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[4].condition[0].lte[0].value_[0] = '3'
DB.subscriber[4].condition[0].not_ = []
DB.subscriber[4].condition[0].or_ = []
DB.subscriber[4].count = []
DB.subscriber[4].event = []
DB.subscriber[4].event.insert(0, None)
DB.subscriber[4].event[0] = Dummy()
DB.subscriber[4].event[0].condition = []
DB.subscriber[4].event[0].context = 'player'
DB.subscriber[4].event[0].count = []
DB.subscriber[4].event[0].count.insert(0, None)
DB.subscriber[4].event[0].count[0] = Dummy()
DB.subscriber[4].event[0].count[0].id = 0
DB.subscriber[4].event[0].count[0].value_ = 1
DB.subscriber[4].event[0].name = 'sector.capture.participated'
DB.subscriber[4].event[0].operation = []
DB.subscriber[4].event[0].type = 'battle'
DB.subscriber[4].modify = []
DB.subscriber[4].name = 'daringswoop'
DB.subscriber[4].operation = []
DB.subscriber[4].send = []
DB.subscriber.insert(5, None)
DB.subscriber[5] = Dummy()
DB.subscriber[5].client = Dummy()
DB.subscriber[5].client.description = Dummy()
DB.subscriber[5].client.description.locale = 'MEDAL_DESCRIPTION_GOTCHA'
DB.subscriber[5].client.icon = Dummy()
DB.subscriber[5].client.icon.big = 'icons/awards/achievementsInfo/acComGotcha.dds'
DB.subscriber[5].client.icon.faded = 'icons/awards/achievements/acComGotcha_Outline.dds'
DB.subscriber[5].client.icon.small = 'icons/awards/achievements/acComGotcha.dds'
DB.subscriber[5].client.level = Dummy()
DB.subscriber[5].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[5].client.multiple = false
DB.subscriber[5].client.name = Dummy()
DB.subscriber[5].client.name.locale = 'MEDAL_NAME_GOTCHA'
DB.subscriber[5].client.order = 6
DB.subscriber[5].client.page = 0
DB.subscriber[5].condition = []
DB.subscriber[5].condition.insert(0, None)
DB.subscriber[5].condition[0] = Dummy()
DB.subscriber[5].condition[0].and_ = []
DB.subscriber[5].condition[0].contains = []
DB.subscriber[5].condition[0].equal = []
DB.subscriber[5].condition[0].gt = []
DB.subscriber[5].condition[0].gte = []
DB.subscriber[5].condition[0].id = []
DB.subscriber[5].condition[0].in_ = []
DB.subscriber[5].condition[0].lt = []
DB.subscriber[5].condition[0].lte = []
DB.subscriber[5].condition[0].lte.insert(0, None)
DB.subscriber[5].condition[0].lte[0] = Dummy()
DB.subscriber[5].condition[0].lte[0].context = []
DB.subscriber[5].condition[0].lte[0].context.insert(0, None)
DB.subscriber[5].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[5].condition[0].lte[0].value_ = []
DB.subscriber[5].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[5].condition[0].lte[0].value_[0] = '3'
DB.subscriber[5].condition[0].not_ = []
DB.subscriber[5].condition[0].or_ = []
DB.subscriber[5].count = []
DB.subscriber[5].event = []
DB.subscriber[5].event.insert(0, None)
DB.subscriber[5].event[0] = Dummy()
DB.subscriber[5].event[0].condition = []
DB.subscriber[5].event[0].condition.insert(0, None)
DB.subscriber[5].event[0].condition[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_ = []
DB.subscriber[5].event[0].condition[0].and_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].and_ = []
DB.subscriber[5].event[0].condition[0].and_[0].contains = []
DB.subscriber[5].event[0].condition[0].and_[0].equal = []
DB.subscriber[5].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.object'
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_[0] = 'plane'
DB.subscriber[5].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context[0] = 'by'
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_[0] = 'bullet'
DB.subscriber[5].event[0].condition[0].and_[0].gt = []
DB.subscriber[5].event[0].condition[0].and_[0].gte = []
DB.subscriber[5].event[0].condition[0].and_[0].id = []
DB.subscriber[5].event[0].condition[0].and_[0].in_ = []
DB.subscriber[5].event[0].condition[0].and_[0].lt = []
DB.subscriber[5].event[0].condition[0].and_[0].lte = []
DB.subscriber[5].event[0].condition[0].and_[0].not_ = []
DB.subscriber[5].event[0].condition[0].and_[0].or_ = []
DB.subscriber[5].event[0].condition[0].contains = []
DB.subscriber[5].event[0].condition[0].equal = []
DB.subscriber[5].event[0].condition[0].gt = []
DB.subscriber[5].event[0].condition[0].gte = []
DB.subscriber[5].event[0].condition[0].id = []
DB.subscriber[5].event[0].condition[0].in_ = []
DB.subscriber[5].event[0].condition[0].lt = []
DB.subscriber[5].event[0].condition[0].lte = []
DB.subscriber[5].event[0].condition[0].not_ = []
DB.subscriber[5].event[0].condition[0].or_ = []
DB.subscriber[5].event[0].context = 'player'
DB.subscriber[5].event[0].count = []
DB.subscriber[5].event[0].count.insert(0, None)
DB.subscriber[5].event[0].count[0] = Dummy()
DB.subscriber[5].event[0].count[0].id = 0
DB.subscriber[5].event[0].count[0].value_ = 1
DB.subscriber[5].event[0].name = 'damage'
DB.subscriber[5].event[0].operation = []
DB.subscriber[5].event[0].type = 'battle'
DB.subscriber[5].modify = []
DB.subscriber[5].name = 'gotcha'
DB.subscriber[5].operation = []
DB.subscriber[5].send = []
DB.subscriber.insert(6, None)
DB.subscriber[6] = Dummy()
DB.subscriber[6].client = Dummy()
DB.subscriber[6].client.description = Dummy()
DB.subscriber[6].client.description.locale = 'MEDAL_DESCRIPTION_GUNNER'
DB.subscriber[6].client.icon = Dummy()
DB.subscriber[6].client.icon.big = 'icons/awards/achievementsInfo/acComGunner.dds'
DB.subscriber[6].client.icon.faded = 'icons/awards/achievements/acComGunner_Outline.dds'
DB.subscriber[6].client.icon.small = 'icons/awards/achievements/acComGunner.dds'
DB.subscriber[6].client.level = Dummy()
DB.subscriber[6].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[6].client.multiple = false
DB.subscriber[6].client.name = Dummy()
DB.subscriber[6].client.name.locale = 'MEDAL_NAME_GUNNER'
DB.subscriber[6].client.order = 7
DB.subscriber[6].client.page = 0
DB.subscriber[6].condition = []
DB.subscriber[6].condition.insert(0, None)
DB.subscriber[6].condition[0] = Dummy()
DB.subscriber[6].condition[0].and_ = []
DB.subscriber[6].condition[0].contains = []
DB.subscriber[6].condition[0].equal = []
DB.subscriber[6].condition[0].gt = []
DB.subscriber[6].condition[0].gte = []
DB.subscriber[6].condition[0].id = []
DB.subscriber[6].condition[0].in_ = []
DB.subscriber[6].condition[0].lt = []
DB.subscriber[6].condition[0].lte = []
DB.subscriber[6].condition[0].lte.insert(0, None)
DB.subscriber[6].condition[0].lte[0] = Dummy()
DB.subscriber[6].condition[0].lte[0].context = []
DB.subscriber[6].condition[0].lte[0].context.insert(0, None)
DB.subscriber[6].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[6].condition[0].lte[0].value_ = []
DB.subscriber[6].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[6].condition[0].lte[0].value_[0] = '3'
DB.subscriber[6].condition[0].not_ = []
DB.subscriber[6].condition[0].or_ = []
DB.subscriber[6].count = []
DB.subscriber[6].event = []
DB.subscriber[6].event.insert(0, None)
DB.subscriber[6].event[0] = Dummy()
DB.subscriber[6].event[0].condition = []
DB.subscriber[6].event[0].condition.insert(0, None)
DB.subscriber[6].event[0].condition[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_[0].contains = []
DB.subscriber[6].event[0].condition[0].and_[0].equal = []
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.object'
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_[0] = 'plane'
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context[0] = 'by'
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_[0] = 'gunner'
DB.subscriber[6].event[0].condition[0].and_[0].gt = []
DB.subscriber[6].event[0].condition[0].and_[0].gte = []
DB.subscriber[6].event[0].condition[0].and_[0].id = []
DB.subscriber[6].event[0].condition[0].and_[0].in_ = []
DB.subscriber[6].event[0].condition[0].and_[0].lt = []
DB.subscriber[6].event[0].condition[0].and_[0].lte = []
DB.subscriber[6].event[0].condition[0].and_[0].not_ = []
DB.subscriber[6].event[0].condition[0].and_[0].or_ = []
DB.subscriber[6].event[0].condition[0].contains = []
DB.subscriber[6].event[0].condition[0].equal = []
DB.subscriber[6].event[0].condition[0].gt = []
DB.subscriber[6].event[0].condition[0].gte = []
DB.subscriber[6].event[0].condition[0].id = []
DB.subscriber[6].event[0].condition[0].in_ = []
DB.subscriber[6].event[0].condition[0].lt = []
DB.subscriber[6].event[0].condition[0].lte = []
DB.subscriber[6].event[0].condition[0].not_ = []
DB.subscriber[6].event[0].condition[0].or_ = []
DB.subscriber[6].event[0].context = 'player'
DB.subscriber[6].event[0].count = []
DB.subscriber[6].event[0].count.insert(0, None)
DB.subscriber[6].event[0].count[0] = Dummy()
DB.subscriber[6].event[0].count[0].id = 0
DB.subscriber[6].event[0].count[0].value_ = 1
DB.subscriber[6].event[0].name = 'damage'
DB.subscriber[6].event[0].operation = []
DB.subscriber[6].event[0].type = 'battle'
DB.subscriber[6].modify = []
DB.subscriber[6].name = 'gunner'
DB.subscriber[6].operation = []
DB.subscriber[6].send = []
DB.subscriber.insert(7, None)
DB.subscriber[7] = Dummy()
DB.subscriber[7].client = Dummy()
DB.subscriber[7].client.description = Dummy()
DB.subscriber[7].client.description.locale = 'MEDAL_DESCRIPTION_BOMBING'
DB.subscriber[7].client.icon = Dummy()
DB.subscriber[7].client.icon.big = 'icons/awards/achievementsInfo/acComBombing.dds'
DB.subscriber[7].client.icon.faded = 'icons/awards/achievements/acComBombing_Outline.dds'
DB.subscriber[7].client.icon.small = 'icons/awards/achievements/acComBombing.dds'
DB.subscriber[7].client.level = Dummy()
DB.subscriber[7].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[7].client.multiple = false
DB.subscriber[7].client.name = Dummy()
DB.subscriber[7].client.name.locale = 'MEDAL_NAME_BOMBING'
DB.subscriber[7].client.order = 8
DB.subscriber[7].client.page = 0
DB.subscriber[7].condition = []
DB.subscriber[7].condition.insert(0, None)
DB.subscriber[7].condition[0] = Dummy()
DB.subscriber[7].condition[0].and_ = []
DB.subscriber[7].condition[0].contains = []
DB.subscriber[7].condition[0].equal = []
DB.subscriber[7].condition[0].gt = []
DB.subscriber[7].condition[0].gte = []
DB.subscriber[7].condition[0].id = []
DB.subscriber[7].condition[0].in_ = []
DB.subscriber[7].condition[0].lt = []
DB.subscriber[7].condition[0].lte = []
DB.subscriber[7].condition[0].lte.insert(0, None)
DB.subscriber[7].condition[0].lte[0] = Dummy()
DB.subscriber[7].condition[0].lte[0].context = []
DB.subscriber[7].condition[0].lte[0].context.insert(0, None)
DB.subscriber[7].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[7].condition[0].lte[0].value_ = []
DB.subscriber[7].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[7].condition[0].lte[0].value_[0] = '3'
DB.subscriber[7].condition[0].not_ = []
DB.subscriber[7].condition[0].or_ = []
DB.subscriber[7].count = []
DB.subscriber[7].event = []
DB.subscriber[7].event.insert(0, None)
DB.subscriber[7].event[0] = Dummy()
DB.subscriber[7].event[0].condition = []
DB.subscriber[7].event[0].condition.insert(0, None)
DB.subscriber[7].event[0].condition[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_ = []
DB.subscriber[7].event[0].condition[0].contains = []
DB.subscriber[7].event[0].condition[0].equal = []
DB.subscriber[7].event[0].condition[0].equal.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[7].event[0].condition[0].equal[0].context = []
DB.subscriber[7].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[7].event[0].condition[0].equal[0].value_ = []
DB.subscriber[7].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].value_[0] = 'bomb'
DB.subscriber[7].event[0].condition[0].gt = []
DB.subscriber[7].event[0].condition[0].gte = []
DB.subscriber[7].event[0].condition[0].id = []
DB.subscriber[7].event[0].condition[0].in_ = []
DB.subscriber[7].event[0].condition[0].lt = []
DB.subscriber[7].event[0].condition[0].lte = []
DB.subscriber[7].event[0].condition[0].not_ = []
DB.subscriber[7].event[0].condition[0].or_ = []
DB.subscriber[7].event[0].context = 'player'
DB.subscriber[7].event[0].count = []
DB.subscriber[7].event[0].count.insert(0, None)
DB.subscriber[7].event[0].count[0] = Dummy()
DB.subscriber[7].event[0].count[0].id = 0
DB.subscriber[7].event[0].count[0].value_ = 25
DB.subscriber[7].event[0].name = 'destroy'
DB.subscriber[7].event[0].operation = []
DB.subscriber[7].event[0].type = 'battle'
DB.subscriber[7].modify = []
DB.subscriber[7].name = 'bombing'
DB.subscriber[7].operation = []
DB.subscriber[7].send = []
DB.subscriber.insert(8, None)
DB.subscriber[8] = Dummy()
DB.subscriber[8].client = Dummy()
DB.subscriber[8].client.description = Dummy()
DB.subscriber[8].client.description.locale = 'MEDAL_DESCRIPTION_MISSILE_STRIKE'
DB.subscriber[8].client.icon = Dummy()
DB.subscriber[8].client.icon.big = 'icons/awards/achievementsInfo/acComMissleStrike.dds'
DB.subscriber[8].client.icon.faded = 'icons/awards/achievements/acComMissleStrike_Outline.dds'
DB.subscriber[8].client.icon.small = 'icons/awards/achievements/acComMissleStrike.dds'
DB.subscriber[8].client.level = Dummy()
DB.subscriber[8].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[8].client.multiple = false
DB.subscriber[8].client.name = Dummy()
DB.subscriber[8].client.name.locale = 'MEDAL_NAME_MISSILE_STRIKE'
DB.subscriber[8].client.order = 9
DB.subscriber[8].client.page = 0
DB.subscriber[8].condition = []
DB.subscriber[8].condition.insert(0, None)
DB.subscriber[8].condition[0] = Dummy()
DB.subscriber[8].condition[0].and_ = []
DB.subscriber[8].condition[0].contains = []
DB.subscriber[8].condition[0].equal = []
DB.subscriber[8].condition[0].gt = []
DB.subscriber[8].condition[0].gte = []
DB.subscriber[8].condition[0].id = []
DB.subscriber[8].condition[0].in_ = []
DB.subscriber[8].condition[0].lt = []
DB.subscriber[8].condition[0].lte = []
DB.subscriber[8].condition[0].lte.insert(0, None)
DB.subscriber[8].condition[0].lte[0] = Dummy()
DB.subscriber[8].condition[0].lte[0].context = []
DB.subscriber[8].condition[0].lte[0].context.insert(0, None)
DB.subscriber[8].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[8].condition[0].lte[0].value_ = []
DB.subscriber[8].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[8].condition[0].lte[0].value_[0] = '3'
DB.subscriber[8].condition[0].not_ = []
DB.subscriber[8].condition[0].or_ = []
DB.subscriber[8].count = []
DB.subscriber[8].event = []
DB.subscriber[8].event.insert(0, None)
DB.subscriber[8].event[0] = Dummy()
DB.subscriber[8].event[0].condition = []
DB.subscriber[8].event[0].condition.insert(0, None)
DB.subscriber[8].event[0].condition[0] = Dummy()
DB.subscriber[8].event[0].condition[0].and_ = []
DB.subscriber[8].event[0].condition[0].contains = []
DB.subscriber[8].event[0].condition[0].equal = []
DB.subscriber[8].event[0].condition[0].equal.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[8].event[0].condition[0].equal[0].context = []
DB.subscriber[8].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[8].event[0].condition[0].equal[0].value_ = []
DB.subscriber[8].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[8].event[0].condition[0].equal[0].value_[0] = 'rocket'
DB.subscriber[8].event[0].condition[0].gt = []
DB.subscriber[8].event[0].condition[0].gte = []
DB.subscriber[8].event[0].condition[0].id = []
DB.subscriber[8].event[0].condition[0].in_ = []
DB.subscriber[8].event[0].condition[0].lt = []
DB.subscriber[8].event[0].condition[0].lte = []
DB.subscriber[8].event[0].condition[0].not_ = []
DB.subscriber[8].event[0].condition[0].or_ = []
DB.subscriber[8].event[0].context = 'player'
DB.subscriber[8].event[0].count = []
DB.subscriber[8].event[0].count.insert(0, None)
DB.subscriber[8].event[0].count[0] = Dummy()
DB.subscriber[8].event[0].count[0].id = 0
DB.subscriber[8].event[0].count[0].value_ = 40
DB.subscriber[8].event[0].name = 'destroy'
DB.subscriber[8].event[0].operation = []
DB.subscriber[8].event[0].type = 'battle'
DB.subscriber[8].modify = []
DB.subscriber[8].name = 'missilestrike'
DB.subscriber[8].operation = []
DB.subscriber[8].send = []
DB.subscriber.insert(9, None)
DB.subscriber[9] = Dummy()
DB.subscriber[9].client = Dummy()
DB.subscriber[9].client.description = Dummy()
DB.subscriber[9].client.description.locale = 'MEDAL_DESCRIPTION_CAUTION_BOMB'
DB.subscriber[9].client.icon = Dummy()
DB.subscriber[9].client.icon.big = 'icons/awards/achievementsInfo/acComCautionBomb.dds'
DB.subscriber[9].client.icon.faded = 'icons/awards/achievements/acComCautionBomb_Outline.dds'
DB.subscriber[9].client.icon.small = 'icons/awards/achievements/acComCautionBomb.dds'
DB.subscriber[9].client.level = Dummy()
DB.subscriber[9].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[9].client.multiple = false
DB.subscriber[9].client.name = Dummy()
DB.subscriber[9].client.name.locale = 'MEDAL_NAME_CAUTION_BOMB'
DB.subscriber[9].client.order = 10
DB.subscriber[9].client.page = 0
DB.subscriber[9].condition = []
DB.subscriber[9].condition.insert(0, None)
DB.subscriber[9].condition[0] = Dummy()
DB.subscriber[9].condition[0].and_ = []
DB.subscriber[9].condition[0].contains = []
DB.subscriber[9].condition[0].equal = []
DB.subscriber[9].condition[0].gt = []
DB.subscriber[9].condition[0].gte = []
DB.subscriber[9].condition[0].id = []
DB.subscriber[9].condition[0].in_ = []
DB.subscriber[9].condition[0].lt = []
DB.subscriber[9].condition[0].lte = []
DB.subscriber[9].condition[0].lte.insert(0, None)
DB.subscriber[9].condition[0].lte[0] = Dummy()
DB.subscriber[9].condition[0].lte[0].context = []
DB.subscriber[9].condition[0].lte[0].context.insert(0, None)
DB.subscriber[9].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[9].condition[0].lte[0].value_ = []
DB.subscriber[9].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[9].condition[0].lte[0].value_[0] = '3'
DB.subscriber[9].condition[0].not_ = []
DB.subscriber[9].condition[0].or_ = []
DB.subscriber[9].count = []
DB.subscriber[9].event = []
DB.subscriber[9].event.insert(0, None)
DB.subscriber[9].event[0] = Dummy()
DB.subscriber[9].event[0].condition = []
DB.subscriber[9].event[0].condition.insert(0, None)
DB.subscriber[9].event[0].condition[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_ = []
DB.subscriber[9].event[0].condition[0].and_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].and_ = []
DB.subscriber[9].event[0].condition[0].and_[0].contains = []
DB.subscriber[9].event[0].condition[0].and_[0].equal = []
DB.subscriber[9].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.object'
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[0].value_[0] = 'plane'
DB.subscriber[9].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].context[0] = 'by'
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[9].event[0].condition[0].and_[0].equal[1].value_[0] = 'bomb'
DB.subscriber[9].event[0].condition[0].and_[0].gt = []
DB.subscriber[9].event[0].condition[0].and_[0].gte = []
DB.subscriber[9].event[0].condition[0].and_[0].id = []
DB.subscriber[9].event[0].condition[0].and_[0].in_ = []
DB.subscriber[9].event[0].condition[0].and_[0].lt = []
DB.subscriber[9].event[0].condition[0].and_[0].lte = []
DB.subscriber[9].event[0].condition[0].and_[0].not_ = []
DB.subscriber[9].event[0].condition[0].and_[0].or_ = []
DB.subscriber[9].event[0].condition[0].contains = []
DB.subscriber[9].event[0].condition[0].equal = []
DB.subscriber[9].event[0].condition[0].gt = []
DB.subscriber[9].event[0].condition[0].gte = []
DB.subscriber[9].event[0].condition[0].id = []
DB.subscriber[9].event[0].condition[0].in_ = []
DB.subscriber[9].event[0].condition[0].lt = []
DB.subscriber[9].event[0].condition[0].lte = []
DB.subscriber[9].event[0].condition[0].not_ = []
DB.subscriber[9].event[0].condition[0].or_ = []
DB.subscriber[9].event[0].context = 'player'
DB.subscriber[9].event[0].count = []
DB.subscriber[9].event[0].count.insert(0, None)
DB.subscriber[9].event[0].count[0] = Dummy()
DB.subscriber[9].event[0].count[0].id = 0
DB.subscriber[9].event[0].count[0].value_ = 1
DB.subscriber[9].event[0].name = 'damage'
DB.subscriber[9].event[0].operation = []
DB.subscriber[9].event[0].type = 'battle'
DB.subscriber[9].modify = []
DB.subscriber[9].name = 'cautionbomb'
DB.subscriber[9].operation = []
DB.subscriber[9].send = []
DB.subscriber.insert(10, None)
DB.subscriber[10] = Dummy()
DB.subscriber[10].client = Dummy()
DB.subscriber[10].client.description = Dummy()
DB.subscriber[10].client.description.locale = 'MEDAL_DESCRIPTION_FIREBUG'
DB.subscriber[10].client.icon = Dummy()
DB.subscriber[10].client.icon.big = 'icons/awards/achievementsInfo/acComFirebug.dds'
DB.subscriber[10].client.icon.faded = 'icons/awards/achievements/acComFirebug_Outline.dds'
DB.subscriber[10].client.icon.small = 'icons/awards/achievements/acComFirebug.dds'
DB.subscriber[10].client.level = Dummy()
DB.subscriber[10].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[10].client.multiple = false
DB.subscriber[10].client.name = Dummy()
DB.subscriber[10].client.name.locale = 'MEDAL_NAME_FIREBUG'
DB.subscriber[10].client.order = 11
DB.subscriber[10].client.page = 0
DB.subscriber[10].condition = []
DB.subscriber[10].condition.insert(0, None)
DB.subscriber[10].condition[0] = Dummy()
DB.subscriber[10].condition[0].and_ = []
DB.subscriber[10].condition[0].contains = []
DB.subscriber[10].condition[0].equal = []
DB.subscriber[10].condition[0].gt = []
DB.subscriber[10].condition[0].gte = []
DB.subscriber[10].condition[0].id = []
DB.subscriber[10].condition[0].in_ = []
DB.subscriber[10].condition[0].lt = []
DB.subscriber[10].condition[0].lte = []
DB.subscriber[10].condition[0].lte.insert(0, None)
DB.subscriber[10].condition[0].lte[0] = Dummy()
DB.subscriber[10].condition[0].lte[0].context = []
DB.subscriber[10].condition[0].lte[0].context.insert(0, None)
DB.subscriber[10].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[10].condition[0].lte[0].value_ = []
DB.subscriber[10].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[10].condition[0].lte[0].value_[0] = '3'
DB.subscriber[10].condition[0].not_ = []
DB.subscriber[10].condition[0].or_ = []
DB.subscriber[10].count = []
DB.subscriber[10].event = []
DB.subscriber[10].event.insert(0, None)
DB.subscriber[10].event[0] = Dummy()
DB.subscriber[10].event[0].condition = []
DB.subscriber[10].event[0].condition.insert(0, None)
DB.subscriber[10].event[0].condition[0] = Dummy()
DB.subscriber[10].event[0].condition[0].and_ = []
DB.subscriber[10].event[0].condition[0].contains = []
DB.subscriber[10].event[0].condition[0].equal = []
DB.subscriber[10].event[0].condition[0].equal.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[10].event[0].condition[0].equal[0].context = []
DB.subscriber[10].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[10].event[0].condition[0].equal[0].value_ = []
DB.subscriber[10].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0].value_[0] = 'fire'
DB.subscriber[10].event[0].condition[0].gt = []
DB.subscriber[10].event[0].condition[0].gte = []
DB.subscriber[10].event[0].condition[0].id = []
DB.subscriber[10].event[0].condition[0].in_ = []
DB.subscriber[10].event[0].condition[0].lt = []
DB.subscriber[10].event[0].condition[0].lte = []
DB.subscriber[10].event[0].condition[0].not_ = []
DB.subscriber[10].event[0].condition[0].or_ = []
DB.subscriber[10].event[0].context = 'player'
DB.subscriber[10].event[0].count = []
DB.subscriber[10].event[0].count.insert(0, None)
DB.subscriber[10].event[0].count[0] = Dummy()
DB.subscriber[10].event[0].count[0].id = 0
DB.subscriber[10].event[0].count[0].value_ = 1
DB.subscriber[10].event[0].name = 'destroy'
DB.subscriber[10].event[0].operation = []
DB.subscriber[10].event[0].type = 'battle'
DB.subscriber[10].modify = []
DB.subscriber[10].name = 'firebug'
DB.subscriber[10].operation = []
DB.subscriber[10].send = []
DB.subscriber.insert(11, None)
DB.subscriber[11] = Dummy()
DB.subscriber[11].client = Dummy()
DB.subscriber[11].client.description = Dummy()
DB.subscriber[11].client.description.locale = 'MEDAL_DESCRIPTION_CROSSFIRE'
DB.subscriber[11].client.icon = Dummy()
DB.subscriber[11].client.icon.big = 'icons/awards/achievementsInfo/acComCrossfire.dds'
DB.subscriber[11].client.icon.faded = 'icons/awards/achievements/acComCrossfire_Outline.dds'
DB.subscriber[11].client.icon.small = 'icons/awards/achievements/acComCrossfire.dds'
DB.subscriber[11].client.level = Dummy()
DB.subscriber[11].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[11].client.multiple = false
DB.subscriber[11].client.name = Dummy()
DB.subscriber[11].client.name.locale = 'MEDAL_NAME_CROSSFIRE'
DB.subscriber[11].client.order = 12
DB.subscriber[11].client.page = 0
DB.subscriber[11].condition = []
DB.subscriber[11].condition.insert(0, None)
DB.subscriber[11].condition[0] = Dummy()
DB.subscriber[11].condition[0].and_ = []
DB.subscriber[11].condition[0].contains = []
DB.subscriber[11].condition[0].equal = []
DB.subscriber[11].condition[0].gt = []
DB.subscriber[11].condition[0].gte = []
DB.subscriber[11].condition[0].id = []
DB.subscriber[11].condition[0].in_ = []
DB.subscriber[11].condition[0].lt = []
DB.subscriber[11].condition[0].lte = []
DB.subscriber[11].condition[0].lte.insert(0, None)
DB.subscriber[11].condition[0].lte[0] = Dummy()
DB.subscriber[11].condition[0].lte[0].context = []
DB.subscriber[11].condition[0].lte[0].context.insert(0, None)
DB.subscriber[11].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[11].condition[0].lte[0].value_ = []
DB.subscriber[11].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[11].condition[0].lte[0].value_[0] = '3'
DB.subscriber[11].condition[0].not_ = []
DB.subscriber[11].condition[0].or_ = []
DB.subscriber[11].count = []
DB.subscriber[11].event = []
DB.subscriber[11].event.insert(0, None)
DB.subscriber[11].event[0] = Dummy()
DB.subscriber[11].event[0].condition = []
DB.subscriber[11].event[0].condition.insert(0, None)
DB.subscriber[11].event[0].condition[0] = Dummy()
DB.subscriber[11].event[0].condition[0].and_ = []
DB.subscriber[11].event[0].condition[0].contains = []
DB.subscriber[11].event[0].condition[0].equal = []
DB.subscriber[11].event[0].condition[0].equal.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[11].event[0].condition[0].equal[0].context = []
DB.subscriber[11].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].context[0] = 'victim.object'
DB.subscriber[11].event[0].condition[0].equal[0].value_ = []
DB.subscriber[11].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].value_[0] = 'plane'
DB.subscriber[11].event[0].condition[0].gt = []
DB.subscriber[11].event[0].condition[0].gte = []
DB.subscriber[11].event[0].condition[0].id = []
DB.subscriber[11].event[0].condition[0].in_ = []
DB.subscriber[11].event[0].condition[0].lt = []
DB.subscriber[11].event[0].condition[0].lte = []
DB.subscriber[11].event[0].condition[0].not_ = []
DB.subscriber[11].event[0].condition[0].or_ = []
DB.subscriber[11].event[0].context = 'player'
DB.subscriber[11].event[0].count = []
DB.subscriber[11].event[0].count.insert(0, None)
DB.subscriber[11].event[0].count[0] = Dummy()
DB.subscriber[11].event[0].count[0].id = 0
DB.subscriber[11].event[0].count[0].value_ = 100
DB.subscriber[11].event[0].name = 'assist'
DB.subscriber[11].event[0].operation = []
DB.subscriber[11].event[0].type = 'battle'
DB.subscriber[11].modify = []
DB.subscriber[11].name = 'crossfire'
DB.subscriber[11].operation = []
DB.subscriber[11].send = []
DB.subscriber.insert(12, None)
DB.subscriber[12] = Dummy()
DB.subscriber[12].client = Dummy()
DB.subscriber[12].client.description = Dummy()
DB.subscriber[12].client.description.locale = 'MEDAL_DESCRIPTION_LIGHT_WEIGHT'
DB.subscriber[12].client.icon = Dummy()
DB.subscriber[12].client.icon.big = 'icons/awards/achievementsInfo/acComLightWeight.dds'
DB.subscriber[12].client.icon.faded = 'icons/awards/achievements/acComLightWeight_Outline.dds'
DB.subscriber[12].client.icon.small = 'icons/awards/achievements/acComLightWeight.dds'
DB.subscriber[12].client.level = Dummy()
DB.subscriber[12].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[12].client.multiple = false
DB.subscriber[12].client.name = Dummy()
DB.subscriber[12].client.name.locale = 'MEDAL_NAME_LIGHT_WEIGHT'
DB.subscriber[12].client.order = 13
DB.subscriber[12].client.page = 0
DB.subscriber[12].condition = []
DB.subscriber[12].condition.insert(0, None)
DB.subscriber[12].condition[0] = Dummy()
DB.subscriber[12].condition[0].and_ = []
DB.subscriber[12].condition[0].contains = []
DB.subscriber[12].condition[0].equal = []
DB.subscriber[12].condition[0].gt = []
DB.subscriber[12].condition[0].gte = []
DB.subscriber[12].condition[0].id = []
DB.subscriber[12].condition[0].in_ = []
DB.subscriber[12].condition[0].lt = []
DB.subscriber[12].condition[0].lte = []
DB.subscriber[12].condition[0].lte.insert(0, None)
DB.subscriber[12].condition[0].lte[0] = Dummy()
DB.subscriber[12].condition[0].lte[0].context = []
DB.subscriber[12].condition[0].lte[0].context.insert(0, None)
DB.subscriber[12].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[12].condition[0].lte[0].value_ = []
DB.subscriber[12].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[12].condition[0].lte[0].value_[0] = '3'
DB.subscriber[12].condition[0].not_ = []
DB.subscriber[12].condition[0].or_ = []
DB.subscriber[12].count = []
DB.subscriber[12].event = []
DB.subscriber[12].event.insert(0, None)
DB.subscriber[12].event[0] = Dummy()
DB.subscriber[12].event[0].condition = []
DB.subscriber[12].event[0].condition.insert(0, None)
DB.subscriber[12].event[0].condition[0] = Dummy()
DB.subscriber[12].event[0].condition[0].and_ = []
DB.subscriber[12].event[0].condition[0].and_.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[12].event[0].condition[0].and_[0].and_ = []
DB.subscriber[12].event[0].condition[0].and_[0].contains = []
DB.subscriber[12].event[0].condition[0].and_[0].equal = []
DB.subscriber[12].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[12].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[12].event[0].condition[0].and_[0].equal[1].value_[0] = 'fighter'
DB.subscriber[12].event[0].condition[0].and_[0].gt = []
DB.subscriber[12].event[0].condition[0].and_[0].gte = []
DB.subscriber[12].event[0].condition[0].and_[0].id = []
DB.subscriber[12].event[0].condition[0].and_[0].in_ = []
DB.subscriber[12].event[0].condition[0].and_[0].lt = []
DB.subscriber[12].event[0].condition[0].and_[0].lte = []
DB.subscriber[12].event[0].condition[0].and_[0].not_ = []
DB.subscriber[12].event[0].condition[0].and_[0].or_ = []
DB.subscriber[12].event[0].condition[0].contains = []
DB.subscriber[12].event[0].condition[0].equal = []
DB.subscriber[12].event[0].condition[0].gt = []
DB.subscriber[12].event[0].condition[0].gte = []
DB.subscriber[12].event[0].condition[0].id = []
DB.subscriber[12].event[0].condition[0].in_ = []
DB.subscriber[12].event[0].condition[0].lt = []
DB.subscriber[12].event[0].condition[0].lte = []
DB.subscriber[12].event[0].condition[0].not_ = []
DB.subscriber[12].event[0].condition[0].or_ = []
DB.subscriber[12].event[0].context = 'player'
DB.subscriber[12].event[0].count = []
DB.subscriber[12].event[0].count.insert(0, None)
DB.subscriber[12].event[0].count[0] = Dummy()
DB.subscriber[12].event[0].count[0].id = 0
DB.subscriber[12].event[0].count[0].value_ = 200
DB.subscriber[12].event[0].name = 'kill'
DB.subscriber[12].event[0].operation = []
DB.subscriber[12].event[0].type = 'battle'
DB.subscriber[12].modify = []
DB.subscriber[12].name = 'lightweight'
DB.subscriber[12].operation = []
DB.subscriber[12].send = []
DB.subscriber.insert(13, None)
DB.subscriber[13] = Dummy()
DB.subscriber[13].client = Dummy()
DB.subscriber[13].client.description = Dummy()
DB.subscriber[13].client.description.locale = 'MEDAL_DESCRIPTION_NORMALWEIGHT'
DB.subscriber[13].client.icon = Dummy()
DB.subscriber[13].client.icon.big = 'icons/awards/achievementsInfo/acComNormalWeight.dds'
DB.subscriber[13].client.icon.faded = 'icons/awards/achievements/acComNormalWeight_Outline.dds'
DB.subscriber[13].client.icon.small = 'icons/awards/achievements/acComNormalWeight.dds'
DB.subscriber[13].client.level = Dummy()
DB.subscriber[13].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[13].client.multiple = false
DB.subscriber[13].client.name = Dummy()
DB.subscriber[13].client.name.locale = 'MEDAL_NAME_NORMALWEIGHT'
DB.subscriber[13].client.order = 14
DB.subscriber[13].client.page = 0
DB.subscriber[13].condition = []
DB.subscriber[13].condition.insert(0, None)
DB.subscriber[13].condition[0] = Dummy()
DB.subscriber[13].condition[0].and_ = []
DB.subscriber[13].condition[0].contains = []
DB.subscriber[13].condition[0].equal = []
DB.subscriber[13].condition[0].gt = []
DB.subscriber[13].condition[0].gte = []
DB.subscriber[13].condition[0].id = []
DB.subscriber[13].condition[0].in_ = []
DB.subscriber[13].condition[0].lt = []
DB.subscriber[13].condition[0].lte = []
DB.subscriber[13].condition[0].lte.insert(0, None)
DB.subscriber[13].condition[0].lte[0] = Dummy()
DB.subscriber[13].condition[0].lte[0].context = []
DB.subscriber[13].condition[0].lte[0].context.insert(0, None)
DB.subscriber[13].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[13].condition[0].lte[0].value_ = []
DB.subscriber[13].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[13].condition[0].lte[0].value_[0] = '3'
DB.subscriber[13].condition[0].not_ = []
DB.subscriber[13].condition[0].or_ = []
DB.subscriber[13].count = []
DB.subscriber[13].event = []
DB.subscriber[13].event.insert(0, None)
DB.subscriber[13].event[0] = Dummy()
DB.subscriber[13].event[0].condition = []
DB.subscriber[13].event[0].condition.insert(0, None)
DB.subscriber[13].event[0].condition[0] = Dummy()
DB.subscriber[13].event[0].condition[0].and_ = []
DB.subscriber[13].event[0].condition[0].and_.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[13].event[0].condition[0].and_[0].and_ = []
DB.subscriber[13].event[0].condition[0].and_[0].contains = []
DB.subscriber[13].event[0].condition[0].and_[0].equal = []
DB.subscriber[13].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[13].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[13].event[0].condition[0].and_[0].equal[1].value_[0] = 'navy'
DB.subscriber[13].event[0].condition[0].and_[0].gt = []
DB.subscriber[13].event[0].condition[0].and_[0].gte = []
DB.subscriber[13].event[0].condition[0].and_[0].id = []
DB.subscriber[13].event[0].condition[0].and_[0].in_ = []
DB.subscriber[13].event[0].condition[0].and_[0].lt = []
DB.subscriber[13].event[0].condition[0].and_[0].lte = []
DB.subscriber[13].event[0].condition[0].and_[0].not_ = []
DB.subscriber[13].event[0].condition[0].and_[0].or_ = []
DB.subscriber[13].event[0].condition[0].contains = []
DB.subscriber[13].event[0].condition[0].equal = []
DB.subscriber[13].event[0].condition[0].gt = []
DB.subscriber[13].event[0].condition[0].gte = []
DB.subscriber[13].event[0].condition[0].id = []
DB.subscriber[13].event[0].condition[0].in_ = []
DB.subscriber[13].event[0].condition[0].lt = []
DB.subscriber[13].event[0].condition[0].lte = []
DB.subscriber[13].event[0].condition[0].not_ = []
DB.subscriber[13].event[0].condition[0].or_ = []
DB.subscriber[13].event[0].context = 'player'
DB.subscriber[13].event[0].count = []
DB.subscriber[13].event[0].count.insert(0, None)
DB.subscriber[13].event[0].count[0] = Dummy()
DB.subscriber[13].event[0].count[0].id = 0
DB.subscriber[13].event[0].count[0].value_ = 150
DB.subscriber[13].event[0].name = 'kill'
DB.subscriber[13].event[0].operation = []
DB.subscriber[13].event[0].type = 'battle'
DB.subscriber[13].modify = []
DB.subscriber[13].name = 'normalweight'
DB.subscriber[13].operation = []
DB.subscriber[13].send = []
DB.subscriber.insert(14, None)
DB.subscriber[14] = Dummy()
DB.subscriber[14].client = Dummy()
DB.subscriber[14].client.description = Dummy()
DB.subscriber[14].client.description.locale = 'MEDAL_DESCRIPTION_HEAVYWEIGHT'
DB.subscriber[14].client.icon = Dummy()
DB.subscriber[14].client.icon.big = 'icons/awards/achievementsInfo/acComHeavyWeight.dds'
DB.subscriber[14].client.icon.faded = 'icons/awards/achievements/acComHeavyWeight_Outline.dds'
DB.subscriber[14].client.icon.small = 'icons/awards/achievements/acComHeavyWeight.dds'
DB.subscriber[14].client.level = Dummy()
DB.subscriber[14].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[14].client.multiple = false
DB.subscriber[14].client.name = Dummy()
DB.subscriber[14].client.name.locale = 'MEDAL_NAME_HEAVYWEIGHT'
DB.subscriber[14].client.order = 15
DB.subscriber[14].client.page = 0
DB.subscriber[14].condition = []
DB.subscriber[14].condition.insert(0, None)
DB.subscriber[14].condition[0] = Dummy()
DB.subscriber[14].condition[0].and_ = []
DB.subscriber[14].condition[0].contains = []
DB.subscriber[14].condition[0].equal = []
DB.subscriber[14].condition[0].gt = []
DB.subscriber[14].condition[0].gte = []
DB.subscriber[14].condition[0].id = []
DB.subscriber[14].condition[0].in_ = []
DB.subscriber[14].condition[0].lt = []
DB.subscriber[14].condition[0].lte = []
DB.subscriber[14].condition[0].lte.insert(0, None)
DB.subscriber[14].condition[0].lte[0] = Dummy()
DB.subscriber[14].condition[0].lte[0].context = []
DB.subscriber[14].condition[0].lte[0].context.insert(0, None)
DB.subscriber[14].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[14].condition[0].lte[0].value_ = []
DB.subscriber[14].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[14].condition[0].lte[0].value_[0] = '3'
DB.subscriber[14].condition[0].not_ = []
DB.subscriber[14].condition[0].or_ = []
DB.subscriber[14].count = []
DB.subscriber[14].event = []
DB.subscriber[14].event.insert(0, None)
DB.subscriber[14].event[0] = Dummy()
DB.subscriber[14].event[0].condition = []
DB.subscriber[14].event[0].condition.insert(0, None)
DB.subscriber[14].event[0].condition[0] = Dummy()
DB.subscriber[14].event[0].condition[0].and_ = []
DB.subscriber[14].event[0].condition[0].and_.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[14].event[0].condition[0].and_[0].and_ = []
DB.subscriber[14].event[0].condition[0].and_[0].contains = []
DB.subscriber[14].event[0].condition[0].and_[0].equal = []
DB.subscriber[14].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[14].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[14].event[0].condition[0].and_[0].equal[1].value_[0] = 'heavy.fighter'
DB.subscriber[14].event[0].condition[0].and_[0].gt = []
DB.subscriber[14].event[0].condition[0].and_[0].gte = []
DB.subscriber[14].event[0].condition[0].and_[0].id = []
DB.subscriber[14].event[0].condition[0].and_[0].in_ = []
DB.subscriber[14].event[0].condition[0].and_[0].lt = []
DB.subscriber[14].event[0].condition[0].and_[0].lte = []
DB.subscriber[14].event[0].condition[0].and_[0].not_ = []
DB.subscriber[14].event[0].condition[0].and_[0].or_ = []
DB.subscriber[14].event[0].condition[0].contains = []
DB.subscriber[14].event[0].condition[0].equal = []
DB.subscriber[14].event[0].condition[0].gt = []
DB.subscriber[14].event[0].condition[0].gte = []
DB.subscriber[14].event[0].condition[0].id = []
DB.subscriber[14].event[0].condition[0].in_ = []
DB.subscriber[14].event[0].condition[0].lt = []
DB.subscriber[14].event[0].condition[0].lte = []
DB.subscriber[14].event[0].condition[0].not_ = []
DB.subscriber[14].event[0].condition[0].or_ = []
DB.subscriber[14].event[0].context = 'player'
DB.subscriber[14].event[0].count = []
DB.subscriber[14].event[0].count.insert(0, None)
DB.subscriber[14].event[0].count[0] = Dummy()
DB.subscriber[14].event[0].count[0].id = 0
DB.subscriber[14].event[0].count[0].value_ = 150
DB.subscriber[14].event[0].name = 'kill'
DB.subscriber[14].event[0].operation = []
DB.subscriber[14].event[0].type = 'battle'
DB.subscriber[14].modify = []
DB.subscriber[14].name = 'heavyweight'
DB.subscriber[14].operation = []
DB.subscriber[14].send = []
DB.subscriber.insert(15, None)
DB.subscriber[15] = Dummy()
DB.subscriber[15].client = Dummy()
DB.subscriber[15].client.description = Dummy()
DB.subscriber[15].client.description.locale = 'MEDAL_DESCRIPTION_SUPERHEAVYWEIGHT'
DB.subscriber[15].client.icon = Dummy()
DB.subscriber[15].client.icon.big = 'icons/awards/achievementsInfo/acComSuperHeavyWeight.dds'
DB.subscriber[15].client.icon.faded = 'icons/awards/achievements/acComSuperHeavyWeight_Outline.dds'
DB.subscriber[15].client.icon.small = 'icons/awards/achievements/acComSuperHeavyWeight.dds'
DB.subscriber[15].client.level = Dummy()
DB.subscriber[15].client.level.locale = 'MEDAL_LOW_LEVEL_LIMIT'
DB.subscriber[15].client.multiple = false
DB.subscriber[15].client.name = Dummy()
DB.subscriber[15].client.name.locale = 'MEDAL_NAME_SUPERHEAVYWEIGHT'
DB.subscriber[15].client.order = 16
DB.subscriber[15].client.page = 0
DB.subscriber[15].condition = []
DB.subscriber[15].condition.insert(0, None)
DB.subscriber[15].condition[0] = Dummy()
DB.subscriber[15].condition[0].and_ = []
DB.subscriber[15].condition[0].contains = []
DB.subscriber[15].condition[0].equal = []
DB.subscriber[15].condition[0].gt = []
DB.subscriber[15].condition[0].gte = []
DB.subscriber[15].condition[0].id = []
DB.subscriber[15].condition[0].in_ = []
DB.subscriber[15].condition[0].lt = []
DB.subscriber[15].condition[0].lte = []
DB.subscriber[15].condition[0].lte.insert(0, None)
DB.subscriber[15].condition[0].lte[0] = Dummy()
DB.subscriber[15].condition[0].lte[0].context = []
DB.subscriber[15].condition[0].lte[0].context.insert(0, None)
DB.subscriber[15].condition[0].lte[0].context[0] = 'player.plane.level'
DB.subscriber[15].condition[0].lte[0].value_ = []
DB.subscriber[15].condition[0].lte[0].value_.insert(0, None)
DB.subscriber[15].condition[0].lte[0].value_[0] = '3'
DB.subscriber[15].condition[0].not_ = []
DB.subscriber[15].condition[0].or_ = []
DB.subscriber[15].count = []
DB.subscriber[15].event = []
DB.subscriber[15].event.insert(0, None)
DB.subscriber[15].event[0] = Dummy()
DB.subscriber[15].event[0].condition = []
DB.subscriber[15].event[0].condition.insert(0, None)
DB.subscriber[15].event[0].condition[0] = Dummy()
DB.subscriber[15].event[0].condition[0].and_ = []
DB.subscriber[15].event[0].condition[0].and_.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[15].event[0].condition[0].and_[0].and_ = []
DB.subscriber[15].event[0].condition[0].and_[0].contains = []
DB.subscriber[15].event[0].condition[0].and_[0].equal = []
DB.subscriber[15].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[15].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[15].event[0].condition[0].and_[0].equal[1].value_[0] = 'assault'
DB.subscriber[15].event[0].condition[0].and_[0].gt = []
DB.subscriber[15].event[0].condition[0].and_[0].gte = []
DB.subscriber[15].event[0].condition[0].and_[0].id = []
DB.subscriber[15].event[0].condition[0].and_[0].in_ = []
DB.subscriber[15].event[0].condition[0].and_[0].lt = []
DB.subscriber[15].event[0].condition[0].and_[0].lte = []
DB.subscriber[15].event[0].condition[0].and_[0].not_ = []
DB.subscriber[15].event[0].condition[0].and_[0].or_ = []
DB.subscriber[15].event[0].condition[0].contains = []
DB.subscriber[15].event[0].condition[0].equal = []
DB.subscriber[15].event[0].condition[0].gt = []
DB.subscriber[15].event[0].condition[0].gte = []
DB.subscriber[15].event[0].condition[0].id = []
DB.subscriber[15].event[0].condition[0].in_ = []
DB.subscriber[15].event[0].condition[0].lt = []
DB.subscriber[15].event[0].condition[0].lte = []
DB.subscriber[15].event[0].condition[0].not_ = []
DB.subscriber[15].event[0].condition[0].or_ = []
DB.subscriber[15].event[0].context = 'player'
DB.subscriber[15].event[0].count = []
DB.subscriber[15].event[0].count.insert(0, None)
DB.subscriber[15].event[0].count[0] = Dummy()
DB.subscriber[15].event[0].count[0].id = 0
DB.subscriber[15].event[0].count[0].value_ = 100
DB.subscriber[15].event[0].name = 'kill'
DB.subscriber[15].event[0].operation = []
DB.subscriber[15].event[0].type = 'battle'
DB.subscriber[15].modify = []
DB.subscriber[15].name = 'superheavyweight'
DB.subscriber[15].operation = []
DB.subscriber[15].send = []
DB.subscriber.insert(16, None)
DB.subscriber[16] = Dummy()
DB.subscriber[16].client = Dummy()
DB.subscriber[16].client.description = Dummy()
DB.subscriber[16].client.description.locale = 'MEDAL_DESCRIPTION_UNLIMITED_WEIGHT'
DB.subscriber[16].client.icon = Dummy()
DB.subscriber[16].client.icon.big = 'icons/awards/achievementsInfo/acComUnlimitedWeight.dds'
DB.subscriber[16].client.icon.faded = 'icons/awards/achievements/acComUnlimitedWeight_Outline.dds'
DB.subscriber[16].client.icon.small = 'icons/awards/achievements/acComUnlimitedWeight.dds'
DB.subscriber[16].client.multiple = false
DB.subscriber[16].client.name = Dummy()
DB.subscriber[16].client.name.locale = 'MEDAL_NAME_UNLIMITED_WEIGHT'
DB.subscriber[16].client.order = 17
DB.subscriber[16].client.page = 0
DB.subscriber[16].condition = []
DB.subscriber[16].count = []
DB.subscriber[16].event = []
DB.subscriber[16].event.insert(0, None)
DB.subscriber[16].event[0] = Dummy()
DB.subscriber[16].event[0].condition = []
DB.subscriber[16].event[0].condition.insert(0, None)
DB.subscriber[16].event[0].condition[0] = Dummy()
DB.subscriber[16].event[0].condition[0].and_ = []
DB.subscriber[16].event[0].condition[0].and_.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[16].event[0].condition[0].and_[0].and_ = []
DB.subscriber[16].event[0].condition[0].and_[0].contains = []
DB.subscriber[16].event[0].condition[0].and_[0].equal = []
DB.subscriber[16].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[16].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[16].event[0].condition[0].and_[0].equal[1].value_[0] = 'bomber'
DB.subscriber[16].event[0].condition[0].and_[0].gt = []
DB.subscriber[16].event[0].condition[0].and_[0].gte = []
DB.subscriber[16].event[0].condition[0].and_[0].id = []
DB.subscriber[16].event[0].condition[0].and_[0].in_ = []
DB.subscriber[16].event[0].condition[0].and_[0].lt = []
DB.subscriber[16].event[0].condition[0].and_[0].lte = []
DB.subscriber[16].event[0].condition[0].and_[0].not_ = []
DB.subscriber[16].event[0].condition[0].and_[0].or_ = []
DB.subscriber[16].event[0].condition[0].contains = []
DB.subscriber[16].event[0].condition[0].equal = []
DB.subscriber[16].event[0].condition[0].gt = []
DB.subscriber[16].event[0].condition[0].gte = []
DB.subscriber[16].event[0].condition[0].id = []
DB.subscriber[16].event[0].condition[0].in_ = []
DB.subscriber[16].event[0].condition[0].lt = []
DB.subscriber[16].event[0].condition[0].lte = []
DB.subscriber[16].event[0].condition[0].not_ = []
DB.subscriber[16].event[0].condition[0].or_ = []
DB.subscriber[16].event[0].context = 'player'
DB.subscriber[16].event[0].count = []
DB.subscriber[16].event[0].count.insert(0, None)
DB.subscriber[16].event[0].count[0] = Dummy()
DB.subscriber[16].event[0].count[0].id = 0
DB.subscriber[16].event[0].count[0].value_ = 50
DB.subscriber[16].event[0].name = 'kill'
DB.subscriber[16].event[0].operation = []
DB.subscriber[16].event[0].type = 'battle'
DB.subscriber[16].modify = []
DB.subscriber[16].name = 'unlimitedweight'
DB.subscriber[16].operation = []
DB.subscriber[16].send = []
DB.subscriber[0].id = 4152809
DB.subscriber[1].id = 487556879
DB.subscriber[2].id = -306789298
DB.subscriber[3].id = 979176171
DB.subscriber[4].id = 1143987158
DB.subscriber[5].id = -846806777
DB.subscriber[6].id = -1258748173
DB.subscriber[7].id = -718520460
DB.subscriber[8].id = -1375732489
DB.subscriber[9].id = -1448871195
DB.subscriber[10].id = 449933596
DB.subscriber[11].id = -635250117
DB.subscriber[12].id = -1472915512
DB.subscriber[13].id = -1718146328
DB.subscriber[14].id = -787036152
DB.subscriber[15].id = -960673042
DB.subscriber[16].id = 1168920809
DB.subscriber[0].eventIds = (-104890988,)
DB.subscriber[1].eventIds = (-104890988,)
DB.subscriber[12].eventIds = (-104890988,)
DB.subscriber[13].eventIds = (-104890988,)
DB.subscriber[14].eventIds = (-104890988,)
DB.subscriber[15].eventIds = (-104890988,)
DB.subscriber[16].eventIds = (-104890988,)
DB.subscriber[2].eventIds = (761754430, -104890988, -1370837730)
DB.subscriber[3].eventIds = (-1370837730,)
DB.subscriber[7].eventIds = (-1370837730,)
DB.subscriber[8].eventIds = (-1370837730,)
DB.subscriber[10].eventIds = (-1370837730,)
DB.subscriber[4].eventIds = (-1597458317,)
DB.subscriber[5].eventIds = (476499018,)
DB.subscriber[6].eventIds = (476499018,)
DB.subscriber[9].eventIds = (476499018,)
DB.subscriber[11].eventIds = (-1405083736,)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {4152809: (DB.subscriber[0],),
                                   487556879: (DB.subscriber[1],),
                                   -306789298: (DB.subscriber[2],),
                                   979176171: (DB.subscriber[3],),
                                   1143987158: (DB.subscriber[4],),
                                   -846806777: (DB.subscriber[5],),
                                   -1258748173: (DB.subscriber[6],),
                                   -718520460: (DB.subscriber[7],),
                                   -1375732489: (DB.subscriber[8],),
                                   -1448871195: (DB.subscriber[9],),
                                   449933596: (DB.subscriber[10],),
                                   -635250117: (DB.subscriber[11],),
                                   -1472915512: (DB.subscriber[12],),
                                   -1718146328: (DB.subscriber[13],),
                                   -787036152: (DB.subscriber[14],),
                                   -960673042: (DB.subscriber[15],),
                                   1168920809: (DB.subscriber[16],)},
                            'name': {'impactfromthesky': (DB.subscriber[0],),
                                     'knight': (DB.subscriber[1],),
                                     'patrol': (DB.subscriber[2],),
                                     'guard': (DB.subscriber[3],),
                                     'daringswoop': (DB.subscriber[4],),
                                     'gotcha': (DB.subscriber[5],),
                                     'gunner': (DB.subscriber[6],),
                                     'bombing': (DB.subscriber[7],),
                                     'missilestrike': (DB.subscriber[8],),
                                     'cautionbomb': (DB.subscriber[9],),
                                     'firebug': (DB.subscriber[10],),
                                     'crossfire': (DB.subscriber[11],),
                                     'lightweight': (DB.subscriber[12],),
                                     'normalweight': (DB.subscriber[13],),
                                     'heavyweight': (DB.subscriber[14],),
                                     'superheavyweight': (DB.subscriber[15],),
                                     'unlimitedweight': (DB.subscriber[16],)},
                            'type': {'achievement': (DB.subscriber[0],
                                                     DB.subscriber[1],
                                                     DB.subscriber[2],
                                                     DB.subscriber[3],
                                                     DB.subscriber[4],
                                                     DB.subscriber[5],
                                                     DB.subscriber[6],
                                                     DB.subscriber[7],
                                                     DB.subscriber[8],
                                                     DB.subscriber[9],
                                                     DB.subscriber[10],
                                                     DB.subscriber[11],
                                                     DB.subscriber[12],
                                                     DB.subscriber[13],
                                                     DB.subscriber[14],
                                                     DB.subscriber[15],
                                                     DB.subscriber[16])},
                            'group': {'memorable': (DB.subscriber[0],
                                                    DB.subscriber[1],
                                                    DB.subscriber[2],
                                                    DB.subscriber[3],
                                                    DB.subscriber[4],
                                                    DB.subscriber[5],
                                                    DB.subscriber[6],
                                                    DB.subscriber[7],
                                                    DB.subscriber[8],
                                                    DB.subscriber[9],
                                                    DB.subscriber[10],
                                                    DB.subscriber[11],
                                                    DB.subscriber[12],
                                                    DB.subscriber[13],
                                                    DB.subscriber[14],
                                                    DB.subscriber[15],
                                                    DB.subscriber[16])},
                            'eventIds': {(-104890988,): (DB.subscriber[0],
                                                         DB.subscriber[1],
                                                         DB.subscriber[12],
                                                         DB.subscriber[13],
                                                         DB.subscriber[14],
                                                         DB.subscriber[15],
                                                         DB.subscriber[16]),
                                         (761754430, -104890988, -1370837730): (DB.subscriber[2],),
                                         (-1370837730,): (DB.subscriber[3],
                                                          DB.subscriber[7],
                                                          DB.subscriber[8],
                                                          DB.subscriber[10]),
                                         (-1597458317,): (DB.subscriber[4],),
                                         (476499018,): (DB.subscriber[5], DB.subscriber[6], DB.subscriber[9]),
                                         (-1405083736,): (DB.subscriber[11],)},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}