# Embedded file name: scripts/client/_ge_sse_release.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = False

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy:
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType:
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].condition.insert(0, None)
DB.subscriber[0].event[0].condition[0] = Dummy()
DB.subscriber[0].event[0].condition[0].and_ = []
DB.subscriber[0].event[0].condition[0].and_.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[0].event[0].condition[0].and_[0].and_ = []
DB.subscriber[0].event[0].condition[0].and_[0].equal = []
DB.subscriber[0].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].context[0] = 'arena.type'
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[0].value_[0] = 'normal'
DB.subscriber[0].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].context[0] = 'arena.source'
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[0].event[0].condition[0].and_[0].equal[1].value_[0] = 'player'
DB.subscriber[0].event[0].condition[0].and_[0].gt = []
DB.subscriber[0].event[0].condition[0].and_[0].gte = []
DB.subscriber[0].event[0].condition[0].and_[0].id = []
DB.subscriber[0].event[0].condition[0].and_[0].in_ = []
DB.subscriber[0].event[0].condition[0].and_[0].lt = []
DB.subscriber[0].event[0].condition[0].and_[0].lte = []
DB.subscriber[0].event[0].condition[0].and_[0].not_ = []
DB.subscriber[0].event[0].condition[0].and_[0].or_ = []
DB.subscriber[0].event[0].condition[0].equal = []
DB.subscriber[0].event[0].condition[0].gt = []
DB.subscriber[0].event[0].condition[0].gte = []
DB.subscriber[0].event[0].condition[0].id = []
DB.subscriber[0].event[0].condition[0].in_ = []
DB.subscriber[0].event[0].condition[0].lt = []
DB.subscriber[0].event[0].condition[0].lte = []
DB.subscriber[0].event[0].condition[0].not_ = []
DB.subscriber[0].event[0].condition[0].or_ = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].count.insert(0, None)
DB.subscriber[0].event[0].count[0] = Dummy()
DB.subscriber[0].event[0].count[0].value_ = 1
DB.subscriber[0].event[0].name = 'after.battle.result'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].type = 'hangar'
DB.subscriber[0].group = 'gift'
DB.subscriber[0].modify = []
DB.subscriber[0].name = 'release_2_0'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber[0].server = Dummy()
DB.subscriber[0].server.active = true
DB.subscriber[0].server.scope = []
DB.subscriber[0].server.scope.insert(0, None)
DB.subscriber[0].server.scope[0] = 'player'
DB.subscriber[0].type = 'sse'
DB.subscriber[0].id = 1130707531
DB.subscriber[0].eventIds = (465201302,)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {1130707531: (DB.subscriber[0],)},
                            'name': {'release_2_0': (DB.subscriber[0],)},
                            'type': {'sse': (DB.subscriber[0],)},
                            'group': {'gift': (DB.subscriber[0],)},
                            'eventIds': {(465201302,): (DB.subscriber[0],)},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}