# Embedded file name: scripts/client/_ge_achievements_settings.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = False

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.achievements = Dummy()
DB.achievements.client = Dummy()
DB.achievements.client.group = []
DB.achievements.client.group.insert(0, None)
DB.achievements.client.group[0] = Dummy()
DB.achievements.client.group[0].locale = 'ACHIEVEMENTS_TAB_AWARDS_EPIC'
DB.achievements.client.group[0].name = 'epic'
DB.achievements.client.group[0].order = 1
DB.achievements.client.group.insert(1, None)
DB.achievements.client.group[1] = Dummy()
DB.achievements.client.group[1].locale = 'ACHIEVEMENTS_TAB_AWARDS_HERO'
DB.achievements.client.group[1].name = 'heroic'
DB.achievements.client.group[1].order = 2
DB.achievements.client.group.insert(2, None)
DB.achievements.client.group[2] = Dummy()
DB.achievements.client.group[2].locale = 'ACHIEVEMENTS_TAB_AWARDS_HONOR'
DB.achievements.client.group[2].name = 'honorable'
DB.achievements.client.group[2].order = 3
DB.achievements.client.group.insert(3, None)
DB.achievements.client.group[3] = Dummy()
DB.achievements.client.group[3].locale = 'ACHIEVEMENTS_TAB_AWARDS_SERIAL'
DB.achievements.client.group[3].name = 'series'
DB.achievements.client.group[3].order = 5
DB.achievements.client.group.insert(4, None)
DB.achievements.client.group[4] = Dummy()
DB.achievements.client.group[4].locale = 'ACHIEVEMENTS_TAB_AWARDS_DISTINCTION'
DB.achievements.client.group[4].name = 'distinguished'
DB.achievements.client.group[4].order = 7
DB.achievements.client.group.insert(5, None)
DB.achievements.client.group[5] = Dummy()
DB.achievements.client.group[5].locale = 'ACHIEVEMENTS_TAB_AWARDS_GROUP'
DB.achievements.client.group[5].name = 'group'
DB.achievements.client.group[5].order = 6
DB.achievements.client.group.insert(6, None)
DB.achievements.client.group[6] = Dummy()
DB.achievements.client.group[6].locale = 'ACHIEVEMENTS_TAB_AWARDS_STAGE'
DB.achievements.client.group[6].name = 'stage'
DB.achievements.client.group[6].order = 4
DB.achievements.client.group.insert(7, None)
DB.achievements.client.group[7] = Dummy()
DB.achievements.client.group[7].locale = 'ACHIEVEMENTS_TAB_AWARDS_MEMORIAL'
DB.achievements.client.group[7].name = 'memorable'
DB.achievements.client.group[7].order = 8
DB.achievements.client.group.insert(8, None)
DB.achievements.client.group[8] = Dummy()
DB.achievements.client.group[8].locale = 'ACHIEVEMENTS_TAB_AWARDS_OLD'
DB.achievements.client.group[8].name = 'old'
DB.achievements.client.group[8].order = 9
DB.achievements.client.group.insert(9, None)
DB.achievements.client.group[9] = Dummy()
DB.achievements.client.group[9].locale = 'LOBBY_ALBION_OPERATION'
DB.achievements.client.group[9].name = 'albion'
DB.achievements.client.group[9].order = 10
DB.achievements.client.group.insert(10, None)
DB.achievements.client.group[10] = Dummy()
DB.achievements.client.group[10].locale = 'ACHIEVEMENTS_TAB_AWARDS_NEW_YEAR'
DB.achievements.client.group[10].name = 'newyear'
DB.achievements.client.group[10].order = 11