# Embedded file name: scripts/client/_ge_achievements_distinguished.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = False

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy:
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType:
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.header = Dummy()
DB.header.activity = []
DB.header.client = Dummy()
DB.header.client.multiple = false
DB.header.client.place = 'left'
DB.header.condition = []
DB.header.count = []
DB.header.event = []
DB.header.group = 'distinguished'
DB.header.markers = Dummy()
DB.header.markers.group = 'distinguished'
DB.header.modify = []
DB.header.operation = []
DB.header.send = []
DB.header.server = Dummy()
DB.header.server.active = true
DB.header.server.scope = []
DB.header.server.scope.insert(0, None)
DB.header.server.scope[0] = 'plane'
DB.header.type = 'achievement'
DB.include = Dummy()
DB.include.activity = []
DB.include.condition = []
DB.include.condition.insert(0, None)
DB.include.condition[0] = Dummy()
DB.include.condition[0].and_ = []
DB.include.condition[0].and_.insert(0, None)
DB.include.condition[0].and_[0] = Dummy()
DB.include.condition[0].and_[0].and_ = []
DB.include.condition[0].and_[0].contains = []
DB.include.condition[0].and_[0].equal = []
DB.include.condition[0].and_[0].equal.insert(0, None)
DB.include.condition[0].and_[0].equal[0] = Dummy()
DB.include.condition[0].and_[0].equal[0].context = []
DB.include.condition[0].and_[0].equal[0].context.insert(0, None)
DB.include.condition[0].and_[0].equal[0].context[0] = 'arena.type'
DB.include.condition[0].and_[0].equal[0].value_ = []
DB.include.condition[0].and_[0].equal[0].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[0].value_[0] = 'normal'
DB.include.condition[0].and_[0].equal.insert(1, None)
DB.include.condition[0].and_[0].equal[1] = Dummy()
DB.include.condition[0].and_[0].equal[1].context = []
DB.include.condition[0].and_[0].equal[1].context.insert(0, None)
DB.include.condition[0].and_[0].equal[1].context[0] = 'arena.source'
DB.include.condition[0].and_[0].equal[1].value_ = []
DB.include.condition[0].and_[0].equal[1].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[1].value_[0] = 'player'
DB.include.condition[0].and_[0].gt = []
DB.include.condition[0].and_[0].gte = []
DB.include.condition[0].and_[0].id = []
DB.include.condition[0].and_[0].in_ = []
DB.include.condition[0].and_[0].lt = []
DB.include.condition[0].and_[0].lte = []
DB.include.condition[0].and_[0].not_ = []
DB.include.condition[0].and_[0].or_ = []
DB.include.condition[0].contains = []
DB.include.condition[0].equal = []
DB.include.condition[0].gt = []
DB.include.condition[0].gte = []
DB.include.condition[0].id = []
DB.include.condition[0].in_ = []
DB.include.condition[0].lt = []
DB.include.condition[0].lte = []
DB.include.condition[0].not_ = []
DB.include.condition[0].or_ = []
DB.include.count = []
DB.include.event = []
DB.include.event.insert(0, None)
DB.include.event[0] = Dummy()
DB.include.event[0].condition = []
DB.include.event[0].context = 'player'
DB.include.event[0].count = []
DB.include.event[0].name = 'finish'
DB.include.event[0].operation = []
DB.include.event[0].operation.insert(0, None)
DB.include.event[0].operation[0] = Dummy()
DB.include.event[0].operation[0].event = []
DB.include.event[0].operation[0].id = []
DB.include.event[0].operation[0].rollback = true
DB.include.event[0].operation[0].self = true
DB.include.event[0].type = 'battle'
DB.include.metadata = Dummy()
DB.include.metadata.doneCount = true
DB.include.metadata.event = []
DB.include.metadata.firstDoneTime = true
DB.include.metadata.lastDoneTime = true
DB.include.modify = []
DB.include.operation = []
DB.include.send = []
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].activity = []
DB.subscriber[0].client = Dummy()
DB.subscriber[0].client.description = Dummy()
DB.subscriber[0].client.description.locale = 'MEDAL_DESCRIPTION_FLAME_OF_HEAVEN'
DB.subscriber[0].client.icon = Dummy()
DB.subscriber[0].client.icon.big = 'icons/awards/achievementsInfo/acDistinctFlameOfHeaven.dds'
DB.subscriber[0].client.icon.faded = 'icons/awards/achievements/acDistinctFlameOfHeaven_Outline.dds'
DB.subscriber[0].client.icon.small = 'icons/awards/achievements/acDistinctFlameOfHeaven.dds'
DB.subscriber[0].client.name = Dummy()
DB.subscriber[0].client.name.locale = 'MEDAL_NAME_FLAME_OF_HEAVEN'
DB.subscriber[0].client.order = 1
DB.subscriber[0].client.page = 0
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].condition.insert(0, None)
DB.subscriber[0].event[0].condition[0] = Dummy()
DB.subscriber[0].event[0].condition[0].and_ = []
DB.subscriber[0].event[0].condition[0].contains = []
DB.subscriber[0].event[0].condition[0].equal = []
DB.subscriber[0].event[0].condition[0].equal.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[0].event[0].condition[0].equal[0].context = []
DB.subscriber[0].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[0].event[0].condition[0].equal[0].value_ = []
DB.subscriber[0].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[0].event[0].condition[0].equal[0].value_[0] = 'fire'
DB.subscriber[0].event[0].condition[0].gt = []
DB.subscriber[0].event[0].condition[0].gte = []
DB.subscriber[0].event[0].condition[0].id = []
DB.subscriber[0].event[0].condition[0].in_ = []
DB.subscriber[0].event[0].condition[0].lt = []
DB.subscriber[0].event[0].condition[0].lte = []
DB.subscriber[0].event[0].condition[0].not_ = []
DB.subscriber[0].event[0].condition[0].or_ = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].count.insert(0, None)
DB.subscriber[0].event[0].count[0] = Dummy()
DB.subscriber[0].event[0].count[0].value_ = 1
DB.subscriber[0].event[0].name = 'kill'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].type = 'battle'
DB.subscriber[0].modify = []
DB.subscriber[0].name = 'flameofheaven'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber.insert(1, None)
DB.subscriber[1] = Dummy()
DB.subscriber[1].activity = []
DB.subscriber[1].client = Dummy()
DB.subscriber[1].client.description = Dummy()
DB.subscriber[1].client.description.locale = 'MEDAL_DESCRIPTION_FIRESPITTING'
DB.subscriber[1].client.icon = Dummy()
DB.subscriber[1].client.icon.big = 'icons/awards/achievementsInfo/acDistinctFireSpitting.dds'
DB.subscriber[1].client.icon.faded = 'icons/awards/achievements/acDistinctFireSpitting_Outline.dds'
DB.subscriber[1].client.icon.small = 'icons/awards/achievements/acDistinctFireSpitting.dds'
DB.subscriber[1].client.name = Dummy()
DB.subscriber[1].client.name.locale = 'MEDAL_NAME_FIRESPITTING'
DB.subscriber[1].client.order = 2
DB.subscriber[1].client.page = 0
DB.subscriber[1].condition = []
DB.subscriber[1].count = []
DB.subscriber[1].event = []
DB.subscriber[1].event.insert(0, None)
DB.subscriber[1].event[0] = Dummy()
DB.subscriber[1].event[0].condition = []
DB.subscriber[1].event[0].condition.insert(0, None)
DB.subscriber[1].event[0].condition[0] = Dummy()
DB.subscriber[1].event[0].condition[0].and_ = []
DB.subscriber[1].event[0].condition[0].contains = []
DB.subscriber[1].event[0].condition[0].equal = []
DB.subscriber[1].event[0].condition[0].equal.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[1].event[0].condition[0].equal[0].context = []
DB.subscriber[1].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[1].event[0].condition[0].equal[0].value_ = []
DB.subscriber[1].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[1].event[0].condition[0].equal[0].value_[0] = 'fire'
DB.subscriber[1].event[0].condition[0].gt = []
DB.subscriber[1].event[0].condition[0].gte = []
DB.subscriber[1].event[0].condition[0].id = []
DB.subscriber[1].event[0].condition[0].in_ = []
DB.subscriber[1].event[0].condition[0].lt = []
DB.subscriber[1].event[0].condition[0].lte = []
DB.subscriber[1].event[0].condition[0].not_ = []
DB.subscriber[1].event[0].condition[0].or_ = []
DB.subscriber[1].event[0].context = 'player'
DB.subscriber[1].event[0].count = []
DB.subscriber[1].event[0].count.insert(0, None)
DB.subscriber[1].event[0].count[0] = Dummy()
DB.subscriber[1].event[0].count[0].value_ = 2
DB.subscriber[1].event[0].name = 'destroy'
DB.subscriber[1].event[0].operation = []
DB.subscriber[1].event[0].type = 'battle'
DB.subscriber[1].modify = []
DB.subscriber[1].name = 'firespitting'
DB.subscriber[1].operation = []
DB.subscriber[1].send = []
DB.subscriber.insert(2, None)
DB.subscriber[2] = Dummy()
DB.subscriber[2].activity = []
DB.subscriber[2].client = Dummy()
DB.subscriber[2].client.description = Dummy()
DB.subscriber[2].client.description.locale = 'MEDAL_DESCRIPTION_BOMBARDIER'
DB.subscriber[2].client.icon = Dummy()
DB.subscriber[2].client.icon.big = 'icons/awards/achievementsInfo/acDistinctBombardier.dds'
DB.subscriber[2].client.icon.faded = 'icons/awards/achievements/acDistinctBombardier_Outline.dds'
DB.subscriber[2].client.icon.small = 'icons/awards/achievements/acDistinctBombardier.dds'
DB.subscriber[2].client.name = Dummy()
DB.subscriber[2].client.name.locale = 'MEDAL_NAME_BOMBARDIER'
DB.subscriber[2].client.order = 3
DB.subscriber[2].client.page = 0
DB.subscriber[2].condition = []
DB.subscriber[2].count = []
DB.subscriber[2].event = []
DB.subscriber[2].event.insert(0, None)
DB.subscriber[2].event[0] = Dummy()
DB.subscriber[2].event[0].condition = []
DB.subscriber[2].event[0].condition.insert(0, None)
DB.subscriber[2].event[0].condition[0] = Dummy()
DB.subscriber[2].event[0].condition[0].and_ = []
DB.subscriber[2].event[0].condition[0].contains = []
DB.subscriber[2].event[0].condition[0].equal = []
DB.subscriber[2].event[0].condition[0].equal.insert(0, None)
DB.subscriber[2].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[2].event[0].condition[0].equal[0].context = []
DB.subscriber[2].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[2].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[2].event[0].condition[0].equal[0].value_ = []
DB.subscriber[2].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[2].event[0].condition[0].equal[0].value_[0] = 'bomb'
DB.subscriber[2].event[0].condition[0].gt = []
DB.subscriber[2].event[0].condition[0].gte = []
DB.subscriber[2].event[0].condition[0].id = []
DB.subscriber[2].event[0].condition[0].in_ = []
DB.subscriber[2].event[0].condition[0].lt = []
DB.subscriber[2].event[0].condition[0].lte = []
DB.subscriber[2].event[0].condition[0].not_ = []
DB.subscriber[2].event[0].condition[0].or_ = []
DB.subscriber[2].event[0].context = 'player'
DB.subscriber[2].event[0].count = []
DB.subscriber[2].event[0].count.insert(0, None)
DB.subscriber[2].event[0].count[0] = Dummy()
DB.subscriber[2].event[0].count[0].value_ = 1
DB.subscriber[2].event[0].name = 'kill'
DB.subscriber[2].event[0].operation = []
DB.subscriber[2].event[0].type = 'battle'
DB.subscriber[2].modify = []
DB.subscriber[2].name = 'bombardier'
DB.subscriber[2].operation = []
DB.subscriber[2].send = []
DB.subscriber.insert(3, None)
DB.subscriber[3] = Dummy()
DB.subscriber[3].activity = []
DB.subscriber[3].client = Dummy()
DB.subscriber[3].client.description = Dummy()
DB.subscriber[3].client.description.locale = 'MEDAL_DESCRIPTION_FALCON_HUNTING'
DB.subscriber[3].client.icon = Dummy()
DB.subscriber[3].client.icon.big = 'icons/awards/achievementsInfo/acDistinctFalconHunting.dds'
DB.subscriber[3].client.icon.faded = 'icons/awards/achievements/acDistinctFalconHunting_Outline.dds'
DB.subscriber[3].client.icon.small = 'icons/awards/achievements/acDistinctFalconHunting.dds'
DB.subscriber[3].client.name = Dummy()
DB.subscriber[3].client.name.locale = 'MEDAL_NAME_FALCON_HUNTING'
DB.subscriber[3].client.order = 4
DB.subscriber[3].client.page = 0
DB.subscriber[3].condition = []
DB.subscriber[3].count = []
DB.subscriber[3].event = []
DB.subscriber[3].event.insert(0, None)
DB.subscriber[3].event[0] = Dummy()
DB.subscriber[3].event[0].condition = []
DB.subscriber[3].event[0].condition.insert(0, None)
DB.subscriber[3].event[0].condition[0] = Dummy()
DB.subscriber[3].event[0].condition[0].and_ = []
DB.subscriber[3].event[0].condition[0].and_.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[3].event[0].condition[0].and_[0].and_ = []
DB.subscriber[3].event[0].condition[0].and_[0].contains = []
DB.subscriber[3].event[0].condition[0].and_[0].equal = []
DB.subscriber[3].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[3].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[3].event[0].condition[0].and_[0].equal[1].value_[0] = 'fighter'
DB.subscriber[3].event[0].condition[0].and_[0].gt = []
DB.subscriber[3].event[0].condition[0].and_[0].gte = []
DB.subscriber[3].event[0].condition[0].and_[0].id = []
DB.subscriber[3].event[0].condition[0].and_[0].in_ = []
DB.subscriber[3].event[0].condition[0].and_[0].lt = []
DB.subscriber[3].event[0].condition[0].and_[0].lte = []
DB.subscriber[3].event[0].condition[0].and_[0].not_ = []
DB.subscriber[3].event[0].condition[0].and_[0].or_ = []
DB.subscriber[3].event[0].condition[0].contains = []
DB.subscriber[3].event[0].condition[0].equal = []
DB.subscriber[3].event[0].condition[0].gt = []
DB.subscriber[3].event[0].condition[0].gte = []
DB.subscriber[3].event[0].condition[0].id = []
DB.subscriber[3].event[0].condition[0].in_ = []
DB.subscriber[3].event[0].condition[0].lt = []
DB.subscriber[3].event[0].condition[0].lte = []
DB.subscriber[3].event[0].condition[0].not_ = []
DB.subscriber[3].event[0].condition[0].or_ = []
DB.subscriber[3].event[0].context = 'player'
DB.subscriber[3].event[0].count = []
DB.subscriber[3].event[0].count.insert(0, None)
DB.subscriber[3].event[0].count[0] = Dummy()
DB.subscriber[3].event[0].count[0].id = 0
DB.subscriber[3].event[0].count[0].value_ = 6
DB.subscriber[3].event[0].name = 'kill'
DB.subscriber[3].event[0].operation = []
DB.subscriber[3].event[0].type = 'battle'
DB.subscriber[3].event.insert(1, None)
DB.subscriber[3].event[1] = Dummy()
DB.subscriber[3].event[1].condition = []
DB.subscriber[3].event[1].context = 'player'
DB.subscriber[3].event[1].count = []
DB.subscriber[3].event[1].count.insert(0, None)
DB.subscriber[3].event[1].count[0] = Dummy()
DB.subscriber[3].event[1].count[0].value_ = 1
DB.subscriber[3].event[1].name = 'win'
DB.subscriber[3].event[1].operation = []
DB.subscriber[3].event[1].type = 'battle'
DB.subscriber[3].modify = []
DB.subscriber[3].name = 'falconhunting'
DB.subscriber[3].operation = []
DB.subscriber[3].send = []
DB.subscriber.insert(4, None)
DB.subscriber[4] = Dummy()
DB.subscriber[4].activity = []
DB.subscriber[4].client = Dummy()
DB.subscriber[4].client.description = Dummy()
DB.subscriber[4].client.description.locale = 'MEDAL_DESCRIPTION_BATTLE_VULTURE'
DB.subscriber[4].client.icon = Dummy()
DB.subscriber[4].client.icon.big = 'icons/awards/achievementsInfo/acDistinctBattleVulture.dds'
DB.subscriber[4].client.icon.faded = 'icons/awards/achievements/acDistinctBattleVulture_Outline.dds'
DB.subscriber[4].client.icon.small = 'icons/awards/achievements/acDistinctBattleVulture.dds'
DB.subscriber[4].client.name = Dummy()
DB.subscriber[4].client.name.locale = 'MEDAL_NAME_BATTLE_VULTURE'
DB.subscriber[4].client.order = 5
DB.subscriber[4].client.page = 0
DB.subscriber[4].condition = []
DB.subscriber[4].count = []
DB.subscriber[4].event = []
DB.subscriber[4].event.insert(0, None)
DB.subscriber[4].event[0] = Dummy()
DB.subscriber[4].event[0].condition = []
DB.subscriber[4].event[0].condition.insert(0, None)
DB.subscriber[4].event[0].condition[0] = Dummy()
DB.subscriber[4].event[0].condition[0].and_ = []
DB.subscriber[4].event[0].condition[0].and_.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[4].event[0].condition[0].and_[0].and_ = []
DB.subscriber[4].event[0].condition[0].and_[0].contains = []
DB.subscriber[4].event[0].condition[0].and_[0].equal = []
DB.subscriber[4].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[4].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[4].event[0].condition[0].and_[0].equal[1].value_[0] = 'navy'
DB.subscriber[4].event[0].condition[0].and_[0].gt = []
DB.subscriber[4].event[0].condition[0].and_[0].gte = []
DB.subscriber[4].event[0].condition[0].and_[0].id = []
DB.subscriber[4].event[0].condition[0].and_[0].in_ = []
DB.subscriber[4].event[0].condition[0].and_[0].lt = []
DB.subscriber[4].event[0].condition[0].and_[0].lte = []
DB.subscriber[4].event[0].condition[0].and_[0].not_ = []
DB.subscriber[4].event[0].condition[0].and_[0].or_ = []
DB.subscriber[4].event[0].condition[0].contains = []
DB.subscriber[4].event[0].condition[0].equal = []
DB.subscriber[4].event[0].condition[0].gt = []
DB.subscriber[4].event[0].condition[0].gte = []
DB.subscriber[4].event[0].condition[0].id = []
DB.subscriber[4].event[0].condition[0].in_ = []
DB.subscriber[4].event[0].condition[0].lt = []
DB.subscriber[4].event[0].condition[0].lte = []
DB.subscriber[4].event[0].condition[0].not_ = []
DB.subscriber[4].event[0].condition[0].or_ = []
DB.subscriber[4].event[0].context = 'player'
DB.subscriber[4].event[0].count = []
DB.subscriber[4].event[0].count.insert(0, None)
DB.subscriber[4].event[0].count[0] = Dummy()
DB.subscriber[4].event[0].count[0].id = 0
DB.subscriber[4].event[0].count[0].value_ = 6
DB.subscriber[4].event[0].name = 'kill'
DB.subscriber[4].event[0].operation = []
DB.subscriber[4].event[0].type = 'battle'
DB.subscriber[4].event.insert(1, None)
DB.subscriber[4].event[1] = Dummy()
DB.subscriber[4].event[1].condition = []
DB.subscriber[4].event[1].context = 'player'
DB.subscriber[4].event[1].count = []
DB.subscriber[4].event[1].count.insert(0, None)
DB.subscriber[4].event[1].count[0] = Dummy()
DB.subscriber[4].event[1].count[0].value_ = 1
DB.subscriber[4].event[1].name = 'win'
DB.subscriber[4].event[1].operation = []
DB.subscriber[4].event[1].type = 'battle'
DB.subscriber[4].modify = []
DB.subscriber[4].name = 'battlevulture'
DB.subscriber[4].operation = []
DB.subscriber[4].send = []
DB.subscriber.insert(5, None)
DB.subscriber[5] = Dummy()
DB.subscriber[5].activity = []
DB.subscriber[5].client = Dummy()
DB.subscriber[5].client.description = Dummy()
DB.subscriber[5].client.description.locale = 'MEDAL_DESCRIPTION_PREDATORY_BIRD'
DB.subscriber[5].client.icon = Dummy()
DB.subscriber[5].client.icon.big = 'icons/awards/achievementsInfo/acDistinctPredatoryBird.dds'
DB.subscriber[5].client.icon.faded = 'icons/awards/achievements/acDistinctPredatoryBird_Outline.dds'
DB.subscriber[5].client.icon.small = 'icons/awards/achievements/acDistinctPredatoryBird.dds'
DB.subscriber[5].client.name = Dummy()
DB.subscriber[5].client.name.locale = 'MEDAL_NAME_PREDATORY_BIRD'
DB.subscriber[5].client.order = 6
DB.subscriber[5].client.page = 0
DB.subscriber[5].condition = []
DB.subscriber[5].count = []
DB.subscriber[5].event = []
DB.subscriber[5].event.insert(0, None)
DB.subscriber[5].event[0] = Dummy()
DB.subscriber[5].event[0].condition = []
DB.subscriber[5].event[0].condition.insert(0, None)
DB.subscriber[5].event[0].condition[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_ = []
DB.subscriber[5].event[0].condition[0].and_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].and_ = []
DB.subscriber[5].event[0].condition[0].and_[0].contains = []
DB.subscriber[5].event[0].condition[0].and_[0].equal = []
DB.subscriber[5].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[5].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[5].event[0].condition[0].and_[0].equal[1].value_[0] = 'heavy.fighter'
DB.subscriber[5].event[0].condition[0].and_[0].gt = []
DB.subscriber[5].event[0].condition[0].and_[0].gte = []
DB.subscriber[5].event[0].condition[0].and_[0].id = []
DB.subscriber[5].event[0].condition[0].and_[0].in_ = []
DB.subscriber[5].event[0].condition[0].and_[0].lt = []
DB.subscriber[5].event[0].condition[0].and_[0].lte = []
DB.subscriber[5].event[0].condition[0].and_[0].not_ = []
DB.subscriber[5].event[0].condition[0].and_[0].or_ = []
DB.subscriber[5].event[0].condition[0].contains = []
DB.subscriber[5].event[0].condition[0].equal = []
DB.subscriber[5].event[0].condition[0].gt = []
DB.subscriber[5].event[0].condition[0].gte = []
DB.subscriber[5].event[0].condition[0].id = []
DB.subscriber[5].event[0].condition[0].in_ = []
DB.subscriber[5].event[0].condition[0].lt = []
DB.subscriber[5].event[0].condition[0].lte = []
DB.subscriber[5].event[0].condition[0].not_ = []
DB.subscriber[5].event[0].condition[0].or_ = []
DB.subscriber[5].event[0].context = 'player'
DB.subscriber[5].event[0].count = []
DB.subscriber[5].event[0].count.insert(0, None)
DB.subscriber[5].event[0].count[0] = Dummy()
DB.subscriber[5].event[0].count[0].id = 0
DB.subscriber[5].event[0].count[0].value_ = 6
DB.subscriber[5].event[0].name = 'kill'
DB.subscriber[5].event[0].operation = []
DB.subscriber[5].event[0].type = 'battle'
DB.subscriber[5].event.insert(1, None)
DB.subscriber[5].event[1] = Dummy()
DB.subscriber[5].event[1].condition = []
DB.subscriber[5].event[1].context = 'player'
DB.subscriber[5].event[1].count = []
DB.subscriber[5].event[1].count.insert(0, None)
DB.subscriber[5].event[1].count[0] = Dummy()
DB.subscriber[5].event[1].count[0].value_ = 1
DB.subscriber[5].event[1].name = 'win'
DB.subscriber[5].event[1].operation = []
DB.subscriber[5].event[1].type = 'battle'
DB.subscriber[5].modify = []
DB.subscriber[5].name = 'predatorybird'
DB.subscriber[5].operation = []
DB.subscriber[5].send = []
DB.subscriber.insert(6, None)
DB.subscriber[6] = Dummy()
DB.subscriber[6].activity = []
DB.subscriber[6].client = Dummy()
DB.subscriber[6].client.description = Dummy()
DB.subscriber[6].client.description.locale = 'MEDAL_DESCRIPTION_INTERCEPTORHEAVYWEIGHT_FIGHTER'
DB.subscriber[6].client.icon = Dummy()
DB.subscriber[6].client.icon.big = 'icons/awards/achievementsInfo/acDistinctHeavyWeightFighter.dds'
DB.subscriber[6].client.icon.faded = 'icons/awards/achievements/acDistinctHeavyWeightFighter_Outline.dds'
DB.subscriber[6].client.icon.small = 'icons/awards/achievements/acDistinctHeavyWeightFighter.dds'
DB.subscriber[6].client.name = Dummy()
DB.subscriber[6].client.name.locale = 'MEDAL_NAME_HEAVYWEIGHT_FIGHTER'
DB.subscriber[6].client.order = 7
DB.subscriber[6].client.page = 0
DB.subscriber[6].condition = []
DB.subscriber[6].count = []
DB.subscriber[6].event = []
DB.subscriber[6].event.insert(0, None)
DB.subscriber[6].event[0] = Dummy()
DB.subscriber[6].event[0].condition = []
DB.subscriber[6].event[0].condition.insert(0, None)
DB.subscriber[6].event[0].condition[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].and_ = []
DB.subscriber[6].event[0].condition[0].and_[0].contains = []
DB.subscriber[6].event[0].condition[0].and_[0].equal = []
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[6].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[6].event[0].condition[0].and_[0].equal[1].value_[0] = 'assault'
DB.subscriber[6].event[0].condition[0].and_[0].gt = []
DB.subscriber[6].event[0].condition[0].and_[0].gte = []
DB.subscriber[6].event[0].condition[0].and_[0].id = []
DB.subscriber[6].event[0].condition[0].and_[0].in_ = []
DB.subscriber[6].event[0].condition[0].and_[0].lt = []
DB.subscriber[6].event[0].condition[0].and_[0].lte = []
DB.subscriber[6].event[0].condition[0].and_[0].not_ = []
DB.subscriber[6].event[0].condition[0].and_[0].or_ = []
DB.subscriber[6].event[0].condition[0].contains = []
DB.subscriber[6].event[0].condition[0].equal = []
DB.subscriber[6].event[0].condition[0].gt = []
DB.subscriber[6].event[0].condition[0].gte = []
DB.subscriber[6].event[0].condition[0].id = []
DB.subscriber[6].event[0].condition[0].in_ = []
DB.subscriber[6].event[0].condition[0].lt = []
DB.subscriber[6].event[0].condition[0].lte = []
DB.subscriber[6].event[0].condition[0].not_ = []
DB.subscriber[6].event[0].condition[0].or_ = []
DB.subscriber[6].event[0].context = 'player'
DB.subscriber[6].event[0].count = []
DB.subscriber[6].event[0].count.insert(0, None)
DB.subscriber[6].event[0].count[0] = Dummy()
DB.subscriber[6].event[0].count[0].id = 0
DB.subscriber[6].event[0].count[0].value_ = 4
DB.subscriber[6].event[0].name = 'kill'
DB.subscriber[6].event[0].operation = []
DB.subscriber[6].event[0].type = 'battle'
DB.subscriber[6].event.insert(1, None)
DB.subscriber[6].event[1] = Dummy()
DB.subscriber[6].event[1].condition = []
DB.subscriber[6].event[1].context = 'player'
DB.subscriber[6].event[1].count = []
DB.subscriber[6].event[1].count.insert(0, None)
DB.subscriber[6].event[1].count[0] = Dummy()
DB.subscriber[6].event[1].count[0].value_ = 1
DB.subscriber[6].event[1].name = 'win'
DB.subscriber[6].event[1].operation = []
DB.subscriber[6].event[1].type = 'battle'
DB.subscriber[6].modify = []
DB.subscriber[6].name = 'heavyweightfighter'
DB.subscriber[6].operation = []
DB.subscriber[6].send = []
DB.subscriber.insert(7, None)
DB.subscriber[7] = Dummy()
DB.subscriber[7].activity = []
DB.subscriber[7].client = Dummy()
DB.subscriber[7].client.description = Dummy()
DB.subscriber[7].client.description.locale = 'MEDAL_DESCRIPTION_ALTITUDE_HUNTER'
DB.subscriber[7].client.icon = Dummy()
DB.subscriber[7].client.icon.big = 'icons/awards/achievementsInfo/acDistinctAltitudeHunter.dds'
DB.subscriber[7].client.icon.faded = 'icons/awards/achievements/acDistinctAltitudeHunter_Outline.dds'
DB.subscriber[7].client.icon.small = 'icons/awards/achievements/acDistinctAltitudeHunter.dds'
DB.subscriber[7].client.name = Dummy()
DB.subscriber[7].client.name.locale = 'MEDAL_NAME_ALTITUDE_HUNTER'
DB.subscriber[7].client.order = 8
DB.subscriber[7].client.page = 0
DB.subscriber[7].condition = []
DB.subscriber[7].count = []
DB.subscriber[7].event = []
DB.subscriber[7].event.insert(0, None)
DB.subscriber[7].event[0] = Dummy()
DB.subscriber[7].event[0].condition = []
DB.subscriber[7].event[0].condition.insert(0, None)
DB.subscriber[7].event[0].condition[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_ = []
DB.subscriber[7].event[0].condition[0].and_.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_[0].and_ = []
DB.subscriber[7].event[0].condition[0].and_[0].contains = []
DB.subscriber[7].event[0].condition[0].and_[0].equal = []
DB.subscriber[7].event[0].condition[0].and_[0].equal.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].context = []
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].context.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].context[0] = 'victim.type'
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].value_ = []
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].value_.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[0].value_[0] = 'player'
DB.subscriber[7].event[0].condition[0].and_[0].equal.insert(1, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[1] = Dummy()
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].context = []
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].context.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].context[0] = 'victim.plane.type'
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].value_ = []
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].value_.insert(0, None)
DB.subscriber[7].event[0].condition[0].and_[0].equal[1].value_[0] = 'bomber'
DB.subscriber[7].event[0].condition[0].and_[0].gt = []
DB.subscriber[7].event[0].condition[0].and_[0].gte = []
DB.subscriber[7].event[0].condition[0].and_[0].id = []
DB.subscriber[7].event[0].condition[0].and_[0].in_ = []
DB.subscriber[7].event[0].condition[0].and_[0].lt = []
DB.subscriber[7].event[0].condition[0].and_[0].lte = []
DB.subscriber[7].event[0].condition[0].and_[0].not_ = []
DB.subscriber[7].event[0].condition[0].and_[0].or_ = []
DB.subscriber[7].event[0].condition[0].contains = []
DB.subscriber[7].event[0].condition[0].equal = []
DB.subscriber[7].event[0].condition[0].gt = []
DB.subscriber[7].event[0].condition[0].gte = []
DB.subscriber[7].event[0].condition[0].id = []
DB.subscriber[7].event[0].condition[0].in_ = []
DB.subscriber[7].event[0].condition[0].lt = []
DB.subscriber[7].event[0].condition[0].lte = []
DB.subscriber[7].event[0].condition[0].not_ = []
DB.subscriber[7].event[0].condition[0].or_ = []
DB.subscriber[7].event[0].context = 'player'
DB.subscriber[7].event[0].count = []
DB.subscriber[7].event[0].count.insert(0, None)
DB.subscriber[7].event[0].count[0] = Dummy()
DB.subscriber[7].event[0].count[0].id = 0
DB.subscriber[7].event[0].count[0].value_ = 4
DB.subscriber[7].event[0].name = 'kill'
DB.subscriber[7].event[0].operation = []
DB.subscriber[7].event[0].type = 'battle'
DB.subscriber[7].event.insert(1, None)
DB.subscriber[7].event[1] = Dummy()
DB.subscriber[7].event[1].condition = []
DB.subscriber[7].event[1].context = 'player'
DB.subscriber[7].event[1].count = []
DB.subscriber[7].event[1].count.insert(0, None)
DB.subscriber[7].event[1].count[0] = Dummy()
DB.subscriber[7].event[1].count[0].value_ = 1
DB.subscriber[7].event[1].name = 'win'
DB.subscriber[7].event[1].operation = []
DB.subscriber[7].event[1].type = 'battle'
DB.subscriber[7].modify = []
DB.subscriber[7].name = 'altitudehunter'
DB.subscriber[7].operation = []
DB.subscriber[7].send = []
DB.subscriber.insert(8, None)
DB.subscriber[8] = Dummy()
DB.subscriber[8].activity = []
DB.subscriber[8].client = Dummy()
DB.subscriber[8].client.description = Dummy()
DB.subscriber[8].client.description.locale = 'MEDAL_DESCRIPTION_DOMINATOR'
DB.subscriber[8].client.icon = Dummy()
DB.subscriber[8].client.icon.big = 'icons/awards/achievementsInfo/acDistinctDominator.dds'
DB.subscriber[8].client.icon.faded = 'icons/awards/achievements/acDistinctDominator_Outline.dds'
DB.subscriber[8].client.icon.small = 'icons/awards/achievements/acDistinctDominator.dds'
DB.subscriber[8].client.name = Dummy()
DB.subscriber[8].client.name.locale = 'MEDAL_NAME_DOMINATOR'
DB.subscriber[8].client.order = 9
DB.subscriber[8].client.page = 0
DB.subscriber[8].condition = []
DB.subscriber[8].count = []
DB.subscriber[8].event = []
DB.subscriber[8].event.insert(0, None)
DB.subscriber[8].event[0] = Dummy()
DB.subscriber[8].event[0].condition = []
DB.subscriber[8].event[0].context = 'player'
DB.subscriber[8].event[0].count = []
DB.subscriber[8].event[0].count.insert(0, None)
DB.subscriber[8].event[0].count[0] = Dummy()
DB.subscriber[8].event[0].count[0].by = 'victim.plane.type'
DB.subscriber[8].event[0].count[0].contains = Dummy()
DB.subscriber[8].event[0].count[0].contains.item = []
DB.subscriber[8].event[0].count[0].contains.item.insert(0, None)
DB.subscriber[8].event[0].count[0].contains.item[0] = 'fighter'
DB.subscriber[8].event[0].count[0].contains.item.insert(1, None)
DB.subscriber[8].event[0].count[0].contains.item[1] = 'heavy.fighter'
DB.subscriber[8].event[0].count[0].contains.item.insert(2, None)
DB.subscriber[8].event[0].count[0].contains.item[2] = 'assault'
DB.subscriber[8].event[0].count[0].id = 0
DB.subscriber[8].event[0].count[0].total = true
DB.subscriber[8].event[0].count[0].value_ = 3
DB.subscriber[8].event[0].name = 'kill'
DB.subscriber[8].event[0].operation = []
DB.subscriber[8].event[0].type = 'battle'
DB.subscriber[8].event.insert(1, None)
DB.subscriber[8].event[1] = Dummy()
DB.subscriber[8].event[1].condition = []
DB.subscriber[8].event[1].context = 'player'
DB.subscriber[8].event[1].count = []
DB.subscriber[8].event[1].count.insert(0, None)
DB.subscriber[8].event[1].count[0] = Dummy()
DB.subscriber[8].event[1].count[0].value_ = 1
DB.subscriber[8].event[1].name = 'win'
DB.subscriber[8].event[1].operation = []
DB.subscriber[8].event[1].type = 'battle'
DB.subscriber[8].modify = []
DB.subscriber[8].name = 'dominator'
DB.subscriber[8].operation = []
DB.subscriber[8].send = []
DB.subscriber.insert(9, None)
DB.subscriber[9] = Dummy()
DB.subscriber[9].activity = []
DB.subscriber[9].client = Dummy()
DB.subscriber[9].client.description = Dummy()
DB.subscriber[9].client.description.locale = 'MEDAL_DESCRIPTION_FLOWN'
DB.subscriber[9].client.icon = Dummy()
DB.subscriber[9].client.icon.big = 'icons/awards/achievementsInfo/acDistinctFlown.dds'
DB.subscriber[9].client.icon.faded = 'icons/awards/achievements/acDistinctFlown_Outline.dds'
DB.subscriber[9].client.icon.small = 'icons/awards/achievements/acDistinctFlown.dds'
DB.subscriber[9].client.name = Dummy()
DB.subscriber[9].client.name.locale = 'MEDAL_NAME_FLOWN'
DB.subscriber[9].client.order = 10
DB.subscriber[9].client.page = 0
DB.subscriber[9].condition = []
DB.subscriber[9].count = []
DB.subscriber[9].event = []
DB.subscriber[9].event.insert(0, None)
DB.subscriber[9].event[0] = Dummy()
DB.subscriber[9].event[0].condition = []
DB.subscriber[9].event[0].condition.insert(0, None)
DB.subscriber[9].event[0].condition[0] = Dummy()
DB.subscriber[9].event[0].condition[0].and_ = []
DB.subscriber[9].event[0].condition[0].contains = []
DB.subscriber[9].event[0].condition[0].equal = []
DB.subscriber[9].event[0].condition[0].equal.insert(0, None)
DB.subscriber[9].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[9].event[0].condition[0].equal[0].context = []
DB.subscriber[9].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[9].event[0].condition[0].equal[0].context[0] = 'victim.object'
DB.subscriber[9].event[0].condition[0].equal[0].value_ = []
DB.subscriber[9].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[9].event[0].condition[0].equal[0].value_[0] = 'plane'
DB.subscriber[9].event[0].condition[0].gt = []
DB.subscriber[9].event[0].condition[0].gte = []
DB.subscriber[9].event[0].condition[0].id = []
DB.subscriber[9].event[0].condition[0].in_ = []
DB.subscriber[9].event[0].condition[0].lt = []
DB.subscriber[9].event[0].condition[0].lte = []
DB.subscriber[9].event[0].condition[0].not_ = []
DB.subscriber[9].event[0].condition[0].or_ = []
DB.subscriber[9].event[0].context = 'player'
DB.subscriber[9].event[0].count = []
DB.subscriber[9].event[0].count.insert(0, None)
DB.subscriber[9].event[0].count[0] = Dummy()
DB.subscriber[9].event[0].count[0].id = 0
DB.subscriber[9].event[0].count[0].value_ = 4
DB.subscriber[9].event[0].name = 'assist'
DB.subscriber[9].event[0].operation = []
DB.subscriber[9].event[0].type = 'battle'
DB.subscriber[9].event.insert(1, None)
DB.subscriber[9].event[1] = Dummy()
DB.subscriber[9].event[1].condition = []
DB.subscriber[9].event[1].context = 'player'
DB.subscriber[9].event[1].count = []
DB.subscriber[9].event[1].count.insert(0, None)
DB.subscriber[9].event[1].count[0] = Dummy()
DB.subscriber[9].event[1].count[0].value_ = 1
DB.subscriber[9].event[1].name = 'win'
DB.subscriber[9].event[1].operation = []
DB.subscriber[9].event[1].type = 'battle'
DB.subscriber[9].modify = []
DB.subscriber[9].name = 'flown'
DB.subscriber[9].operation = []
DB.subscriber[9].send = []
DB.subscriber.insert(10, None)
DB.subscriber[10] = Dummy()
DB.subscriber[10].activity = []
DB.subscriber[10].client = Dummy()
DB.subscriber[10].client.description = Dummy()
DB.subscriber[10].client.description.locale = 'MEDAL_DESCRIPTION_RELIABLE_PROTECTION'
DB.subscriber[10].client.icon = Dummy()
DB.subscriber[10].client.icon.big = 'icons/awards/achievementsInfo/acDistinctReliableProtection.dds'
DB.subscriber[10].client.icon.faded = 'icons/awards/achievements/acDistinctReliableProtection_Outline.dds'
DB.subscriber[10].client.icon.small = 'icons/awards/achievements/acDistinctReliableProtection.dds'
DB.subscriber[10].client.name = Dummy()
DB.subscriber[10].client.name.locale = 'MEDAL_NAME_RELIABLE_PROTECTION'
DB.subscriber[10].client.order = 11
DB.subscriber[10].client.page = 0
DB.subscriber[10].condition = []
DB.subscriber[10].count = []
DB.subscriber[10].event = []
DB.subscriber[10].event.insert(0, None)
DB.subscriber[10].event[0] = Dummy()
DB.subscriber[10].event[0].condition = []
DB.subscriber[10].event[0].condition.insert(0, None)
DB.subscriber[10].event[0].condition[0] = Dummy()
DB.subscriber[10].event[0].condition[0].and_ = []
DB.subscriber[10].event[0].condition[0].contains = []
DB.subscriber[10].event[0].condition[0].equal = []
DB.subscriber[10].event[0].condition[0].equal.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[10].event[0].condition[0].equal[0].context = []
DB.subscriber[10].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0].context[0] = 'victim.object'
DB.subscriber[10].event[0].condition[0].equal[0].value_ = []
DB.subscriber[10].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[10].event[0].condition[0].equal[0].value_[0] = 'plane'
DB.subscriber[10].event[0].condition[0].gt = []
DB.subscriber[10].event[0].condition[0].gte = []
DB.subscriber[10].event[0].condition[0].id = []
DB.subscriber[10].event[0].condition[0].in_ = []
DB.subscriber[10].event[0].condition[0].lt = []
DB.subscriber[10].event[0].condition[0].lte = []
DB.subscriber[10].event[0].condition[0].not_ = []
DB.subscriber[10].event[0].condition[0].or_ = []
DB.subscriber[10].event[0].context = 'player'
DB.subscriber[10].event[0].count = []
DB.subscriber[10].event[0].count.insert(0, None)
DB.subscriber[10].event[0].count[0] = Dummy()
DB.subscriber[10].event[0].count[0].id = 0
DB.subscriber[10].event[0].count[0].value_ = 8
DB.subscriber[10].event[0].name = 'assist'
DB.subscriber[10].event[0].operation = []
DB.subscriber[10].event[0].type = 'battle'
DB.subscriber[10].event.insert(1, None)
DB.subscriber[10].event[1] = Dummy()
DB.subscriber[10].event[1].condition = []
DB.subscriber[10].event[1].context = 'player'
DB.subscriber[10].event[1].count = []
DB.subscriber[10].event[1].count.insert(0, None)
DB.subscriber[10].event[1].count[0] = Dummy()
DB.subscriber[10].event[1].count[0].value_ = 1
DB.subscriber[10].event[1].name = 'win'
DB.subscriber[10].event[1].operation = []
DB.subscriber[10].event[1].type = 'battle'
DB.subscriber[10].modify = []
DB.subscriber[10].name = 'reliableprotection'
DB.subscriber[10].operation = []
DB.subscriber[10].send = []
DB.subscriber.insert(11, None)
DB.subscriber[11] = Dummy()
DB.subscriber[11].activity = []
DB.subscriber[11].client = Dummy()
DB.subscriber[11].client.description = Dummy()
DB.subscriber[11].client.description.locale = 'MEDAL_DESCRIPTION_RIDDLE'
DB.subscriber[11].client.icon = Dummy()
DB.subscriber[11].client.icon.big = 'icons/awards/achievementsInfo/acDistinctRiddle.dds'
DB.subscriber[11].client.icon.faded = 'icons/awards/achievements/acDistinctRiddle_Outline.dds'
DB.subscriber[11].client.icon.small = 'icons/awards/achievements/acDistinctRiddle.dds'
DB.subscriber[11].client.name = Dummy()
DB.subscriber[11].client.name.locale = 'MEDAL_NAME_RIDDLE'
DB.subscriber[11].client.order = 12
DB.subscriber[11].client.page = 0
DB.subscriber[11].condition = []
DB.subscriber[11].count = []
DB.subscriber[11].event = []
DB.subscriber[11].event.insert(0, None)
DB.subscriber[11].event[0] = Dummy()
DB.subscriber[11].event[0].condition = []
DB.subscriber[11].event[0].condition.insert(0, None)
DB.subscriber[11].event[0].condition[0] = Dummy()
DB.subscriber[11].event[0].condition[0].and_ = []
DB.subscriber[11].event[0].condition[0].contains = []
DB.subscriber[11].event[0].condition[0].equal = []
DB.subscriber[11].event[0].condition[0].equal.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[11].event[0].condition[0].equal[0].context = []
DB.subscriber[11].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].context[0] = 'victim.object'
DB.subscriber[11].event[0].condition[0].equal[0].value_ = []
DB.subscriber[11].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[11].event[0].condition[0].equal[0].value_[0] = 'ground'
DB.subscriber[11].event[0].condition[0].gt = []
DB.subscriber[11].event[0].condition[0].gte = []
DB.subscriber[11].event[0].condition[0].id = []
DB.subscriber[11].event[0].condition[0].in_ = []
DB.subscriber[11].event[0].condition[0].lt = []
DB.subscriber[11].event[0].condition[0].lte = []
DB.subscriber[11].event[0].condition[0].not_ = []
DB.subscriber[11].event[0].condition[0].or_ = []
DB.subscriber[11].event[0].context = 'player'
DB.subscriber[11].event[0].count = []
DB.subscriber[11].event[0].count.insert(0, None)
DB.subscriber[11].event[0].count[0] = Dummy()
DB.subscriber[11].event[0].count[0].id = 0
DB.subscriber[11].event[0].count[0].value_ = 4
DB.subscriber[11].event[0].name = 'assist'
DB.subscriber[11].event[0].operation = []
DB.subscriber[11].event[0].type = 'battle'
DB.subscriber[11].event.insert(1, None)
DB.subscriber[11].event[1] = Dummy()
DB.subscriber[11].event[1].condition = []
DB.subscriber[11].event[1].context = 'player'
DB.subscriber[11].event[1].count = []
DB.subscriber[11].event[1].count.insert(0, None)
DB.subscriber[11].event[1].count[0] = Dummy()
DB.subscriber[11].event[1].count[0].value_ = 1
DB.subscriber[11].event[1].name = 'win'
DB.subscriber[11].event[1].operation = []
DB.subscriber[11].event[1].type = 'battle'
DB.subscriber[11].modify = []
DB.subscriber[11].name = 'riddle'
DB.subscriber[11].operation = []
DB.subscriber[11].send = []
DB.subscriber.insert(12, None)
DB.subscriber[12] = Dummy()
DB.subscriber[12].activity = []
DB.subscriber[12].client = Dummy()
DB.subscriber[12].client.description = Dummy()
DB.subscriber[12].client.description.locale = 'MEDAL_DESCRIPTION_STEEL_FLURRY'
DB.subscriber[12].client.icon = Dummy()
DB.subscriber[12].client.icon.big = 'icons/awards/achievementsInfo/acDistinctSteelflury.dds'
DB.subscriber[12].client.icon.faded = 'icons/awards/achievements/acDistinctSteelflury_Outline.dds'
DB.subscriber[12].client.icon.small = 'icons/awards/achievements/acDistinctSteelflury.dds'
DB.subscriber[12].client.name = Dummy()
DB.subscriber[12].client.name.locale = 'MEDAL_NAME_STEEL_FLURRY'
DB.subscriber[12].client.order = 13
DB.subscriber[12].client.page = 0
DB.subscriber[12].condition = []
DB.subscriber[12].count = []
DB.subscriber[12].event = []
DB.subscriber[12].event.insert(0, None)
DB.subscriber[12].event[0] = Dummy()
DB.subscriber[12].event[0].condition = []
DB.subscriber[12].event[0].condition.insert(0, None)
DB.subscriber[12].event[0].condition[0] = Dummy()
DB.subscriber[12].event[0].condition[0].and_ = []
DB.subscriber[12].event[0].condition[0].contains = []
DB.subscriber[12].event[0].condition[0].equal = []
DB.subscriber[12].event[0].condition[0].equal.insert(0, None)
DB.subscriber[12].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[12].event[0].condition[0].equal[0].context = []
DB.subscriber[12].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[12].event[0].condition[0].equal[0].context[0] = 'victim.object'
DB.subscriber[12].event[0].condition[0].equal[0].value_ = []
DB.subscriber[12].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[12].event[0].condition[0].equal[0].value_[0] = 'ground'
DB.subscriber[12].event[0].condition[0].gt = []
DB.subscriber[12].event[0].condition[0].gte = []
DB.subscriber[12].event[0].condition[0].id = []
DB.subscriber[12].event[0].condition[0].in_ = []
DB.subscriber[12].event[0].condition[0].lt = []
DB.subscriber[12].event[0].condition[0].lte = []
DB.subscriber[12].event[0].condition[0].not_ = []
DB.subscriber[12].event[0].condition[0].or_ = []
DB.subscriber[12].event[0].context = 'player'
DB.subscriber[12].event[0].count = []
DB.subscriber[12].event[0].count.insert(0, None)
DB.subscriber[12].event[0].count[0] = Dummy()
DB.subscriber[12].event[0].count[0].id = 0
DB.subscriber[12].event[0].count[0].value_ = 8
DB.subscriber[12].event[0].name = 'assist'
DB.subscriber[12].event[0].operation = []
DB.subscriber[12].event[0].type = 'battle'
DB.subscriber[12].event.insert(1, None)
DB.subscriber[12].event[1] = Dummy()
DB.subscriber[12].event[1].condition = []
DB.subscriber[12].event[1].context = 'player'
DB.subscriber[12].event[1].count = []
DB.subscriber[12].event[1].count.insert(0, None)
DB.subscriber[12].event[1].count[0] = Dummy()
DB.subscriber[12].event[1].count[0].value_ = 1
DB.subscriber[12].event[1].name = 'win'
DB.subscriber[12].event[1].operation = []
DB.subscriber[12].event[1].type = 'battle'
DB.subscriber[12].modify = []
DB.subscriber[12].name = 'steelflurry'
DB.subscriber[12].operation = []
DB.subscriber[12].send = []
DB.subscriber[0].id = -484139544
DB.subscriber[1].id = 1515672252
DB.subscriber[2].id = 609734944
DB.subscriber[3].id = -1996307921
DB.subscriber[4].id = -1549315390
DB.subscriber[5].id = -111291050
DB.subscriber[6].id = -102910299
DB.subscriber[7].id = 202025891
DB.subscriber[8].id = 1092563282
DB.subscriber[9].id = 829085796
DB.subscriber[10].id = -294367590
DB.subscriber[11].id = 720421259
DB.subscriber[12].id = -1818745423
DB.subscriber[0].eventIds = (-104890988, 761754430)
DB.subscriber[2].eventIds = (-104890988, 761754430)
DB.subscriber[1].eventIds = (-1370837730, 761754430)
DB.subscriber[3].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[4].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[5].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[6].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[7].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[8].eventIds = (-104890988, -218451730, 761754430)
DB.subscriber[9].eventIds = (-1405083736, -218451730, 761754430)
DB.subscriber[10].eventIds = (-1405083736, -218451730, 761754430)
DB.subscriber[11].eventIds = (-1405083736, -218451730, 761754430)
DB.subscriber[12].eventIds = (-1405083736, -218451730, 761754430)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {-484139544: (DB.subscriber[0],),
                                   1515672252: (DB.subscriber[1],),
                                   609734944: (DB.subscriber[2],),
                                   -1996307921: (DB.subscriber[3],),
                                   -1549315390: (DB.subscriber[4],),
                                   -111291050: (DB.subscriber[5],),
                                   -102910299: (DB.subscriber[6],),
                                   202025891: (DB.subscriber[7],),
                                   1092563282: (DB.subscriber[8],),
                                   829085796: (DB.subscriber[9],),
                                   -294367590: (DB.subscriber[10],),
                                   720421259: (DB.subscriber[11],),
                                   -1818745423: (DB.subscriber[12],)},
                            'name': {'flameofheaven': (DB.subscriber[0],),
                                     'firespitting': (DB.subscriber[1],),
                                     'bombardier': (DB.subscriber[2],),
                                     'falconhunting': (DB.subscriber[3],),
                                     'battlevulture': (DB.subscriber[4],),
                                     'predatorybird': (DB.subscriber[5],),
                                     'heavyweightfighter': (DB.subscriber[6],),
                                     'altitudehunter': (DB.subscriber[7],),
                                     'dominator': (DB.subscriber[8],),
                                     'flown': (DB.subscriber[9],),
                                     'reliableprotection': (DB.subscriber[10],),
                                     'riddle': (DB.subscriber[11],),
                                     'steelflurry': (DB.subscriber[12],)},
                            'type': {'achievement': (DB.subscriber[0],
                                                     DB.subscriber[1],
                                                     DB.subscriber[2],
                                                     DB.subscriber[3],
                                                     DB.subscriber[4],
                                                     DB.subscriber[5],
                                                     DB.subscriber[6],
                                                     DB.subscriber[7],
                                                     DB.subscriber[8],
                                                     DB.subscriber[9],
                                                     DB.subscriber[10],
                                                     DB.subscriber[11],
                                                     DB.subscriber[12])},
                            'group': {'distinguished': (DB.subscriber[0],
                                                        DB.subscriber[1],
                                                        DB.subscriber[2],
                                                        DB.subscriber[3],
                                                        DB.subscriber[4],
                                                        DB.subscriber[5],
                                                        DB.subscriber[6],
                                                        DB.subscriber[7],
                                                        DB.subscriber[8],
                                                        DB.subscriber[9],
                                                        DB.subscriber[10],
                                                        DB.subscriber[11],
                                                        DB.subscriber[12])},
                            'eventIds': {(-104890988, 761754430): (DB.subscriber[0], DB.subscriber[2]),
                                         (-1370837730, 761754430): (DB.subscriber[1],),
                                         (-104890988, -218451730, 761754430): (DB.subscriber[3],
                                                                               DB.subscriber[4],
                                                                               DB.subscriber[5],
                                                                               DB.subscriber[6],
                                                                               DB.subscriber[7],
                                                                               DB.subscriber[8]),
                                         (-1405083736, -218451730, 761754430): (DB.subscriber[9],
                                                                                DB.subscriber[10],
                                                                                DB.subscriber[11],
                                                                                DB.subscriber[12])},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}