# Embedded file name: scripts/client/_ge_achievements_series.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = False

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy:
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType:
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.header = Dummy()
DB.header.activity = []
DB.header.client = Dummy()
DB.header.client.place = 'left'
DB.header.client.show = Dummy()
DB.header.client.show.onlyMaxUpdated = true
DB.header.condition = []
DB.header.count = []
DB.header.event = []
DB.header.group = 'series'
DB.header.markers = Dummy()
DB.header.markers.group = 'series'
DB.header.modify = []
DB.header.operation = []
DB.header.send = []
DB.header.server = Dummy()
DB.header.server.active = true
DB.header.server.scope = []
DB.header.server.scope.insert(0, None)
DB.header.server.scope[0] = 'plane'
DB.header.type = 'achievement'
DB.include = Dummy()
DB.include.activity = []
DB.include.condition = []
DB.include.condition.insert(0, None)
DB.include.condition[0] = Dummy()
DB.include.condition[0].and_ = []
DB.include.condition[0].and_.insert(0, None)
DB.include.condition[0].and_[0] = Dummy()
DB.include.condition[0].and_[0].and_ = []
DB.include.condition[0].and_[0].contains = []
DB.include.condition[0].and_[0].equal = []
DB.include.condition[0].and_[0].equal.insert(0, None)
DB.include.condition[0].and_[0].equal[0] = Dummy()
DB.include.condition[0].and_[0].equal[0].context = []
DB.include.condition[0].and_[0].equal[0].context.insert(0, None)
DB.include.condition[0].and_[0].equal[0].context[0] = 'arena.type'
DB.include.condition[0].and_[0].equal[0].value_ = []
DB.include.condition[0].and_[0].equal[0].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[0].value_[0] = 'normal'
DB.include.condition[0].and_[0].equal.insert(1, None)
DB.include.condition[0].and_[0].equal[1] = Dummy()
DB.include.condition[0].and_[0].equal[1].context = []
DB.include.condition[0].and_[0].equal[1].context.insert(0, None)
DB.include.condition[0].and_[0].equal[1].context[0] = 'arena.source'
DB.include.condition[0].and_[0].equal[1].value_ = []
DB.include.condition[0].and_[0].equal[1].value_.insert(0, None)
DB.include.condition[0].and_[0].equal[1].value_[0] = 'player'
DB.include.condition[0].and_[0].gt = []
DB.include.condition[0].and_[0].gte = []
DB.include.condition[0].and_[0].id = []
DB.include.condition[0].and_[0].in_ = []
DB.include.condition[0].and_[0].lt = []
DB.include.condition[0].and_[0].lte = []
DB.include.condition[0].and_[0].not_ = []
DB.include.condition[0].and_[0].or_ = []
DB.include.condition[0].contains = []
DB.include.condition[0].equal = []
DB.include.condition[0].gt = []
DB.include.condition[0].gte = []
DB.include.condition[0].id = []
DB.include.condition[0].in_ = []
DB.include.condition[0].lt = []
DB.include.condition[0].lte = []
DB.include.condition[0].not_ = []
DB.include.condition[0].or_ = []
DB.include.count = []
DB.include.event = []
DB.include.metadata = Dummy()
DB.include.metadata.doneCount = true
DB.include.metadata.event = []
DB.include.metadata.firstDoneTime = true
DB.include.metadata.lastDoneTime = true
DB.include.metadata.maxDoneCount = true
DB.include.modify = []
DB.include.operation = []
DB.include.send = []
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].activity = []
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].name = 'finish'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].operation.insert(0, None)
DB.subscriber[0].event[0].operation[0] = Dummy()
DB.subscriber[0].event[0].operation[0].event = []
DB.subscriber[0].event[0].operation[0].id = []
DB.subscriber[0].event[0].operation[0].id.insert(0, None)
DB.subscriber[0].event[0].operation[0].id[0] = Dummy()
DB.subscriber[0].event[0].operation[0].id[0].group = 'series'
DB.subscriber[0].event[0].operation[0].id[0].name = '*'
DB.subscriber[0].event[0].operation[0].id[0].type = 'achievement'
DB.subscriber[0].event[0].operation[0].rollback = true
DB.subscriber[0].event[0].operation[0].scope = 'plane'
DB.subscriber[0].event[0].operation[0].set = Dummy()
DB.subscriber[0].event[0].operation[0].set.completed = false
DB.subscriber[0].event[0].type = 'battle'
DB.subscriber[0].group = 'series'
DB.subscriber[0].modify = []
DB.subscriber[0].name = 'reset'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber[0].server = Dummy()
DB.subscriber[0].server.overwrite = true
DB.subscriber[0].server.repeat = true
DB.subscriber[0].server.scope = []
DB.subscriber[0].server.scope.insert(0, None)
DB.subscriber[0].server.scope[0] = 'player'
DB.subscriber[0].type = 'achievement.reset'
DB.subscriber.insert(1, None)
DB.subscriber[1] = Dummy()
DB.subscriber[1].activity = []
DB.subscriber[1].client = Dummy()
DB.subscriber[1].client.description = Dummy()
DB.subscriber[1].client.description.locale = 'MEDAL_DESCRIPTION_EFFECTIVE'
DB.subscriber[1].client.icon = Dummy()
DB.subscriber[1].client.icon.big = 'icons/awards/achievementsInfo/acSeriesEffective.dds'
DB.subscriber[1].client.icon.faded = 'icons/awards/achievements/acSeriesEffective_Outline.dds'
DB.subscriber[1].client.icon.small = 'icons/awards/achievements/acSeriesEffective.dds'
DB.subscriber[1].client.multiple = true
DB.subscriber[1].client.name = Dummy()
DB.subscriber[1].client.name.locale = 'MEDAL_NAME_EFFECTIVE'
DB.subscriber[1].client.order = 1
DB.subscriber[1].client.page = 0
DB.subscriber[1].client.show = Dummy()
DB.subscriber[1].client.show.whenDone = 2
DB.subscriber[1].condition = []
DB.subscriber[1].count = []
DB.subscriber[1].event = []
DB.subscriber[1].event.insert(0, None)
DB.subscriber[1].event[0] = Dummy()
DB.subscriber[1].event[0].condition = []
DB.subscriber[1].event[0].context = 'player'
DB.subscriber[1].event[0].count = []
DB.subscriber[1].event[0].count.insert(0, None)
DB.subscriber[1].event[0].count[0] = Dummy()
DB.subscriber[1].event[0].count[0].context = 'points.battle'
DB.subscriber[1].event[0].count[0].id = 0
DB.subscriber[1].event[0].count[0].value_ = 5000
DB.subscriber[1].event[0].name = 'gain'
DB.subscriber[1].event[0].operation = []
DB.subscriber[1].event[0].type = 'battle'
DB.subscriber[1].event.insert(1, None)
DB.subscriber[1].event[1] = Dummy()
DB.subscriber[1].event[1].condition = []
DB.subscriber[1].event[1].context = 'player'
DB.subscriber[1].event[1].count = []
DB.subscriber[1].event[1].name = 'result'
DB.subscriber[1].event[1].operation = []
DB.subscriber[1].event[1].operation.insert(0, None)
DB.subscriber[1].event[1].operation[0] = Dummy()
DB.subscriber[1].event[1].operation[0].event = []
DB.subscriber[1].event[1].operation[0].id = []
DB.subscriber[1].event[1].operation[0].reset_ = true
DB.subscriber[1].event[1].operation[0].self = true
DB.subscriber[1].event[1].type = 'battle'
DB.subscriber[1].modify = []
DB.subscriber[1].name = 'effective'
DB.subscriber[1].operation = []
DB.subscriber[1].send = []
DB.subscriber.insert(2, None)
DB.subscriber[2] = Dummy()
DB.subscriber[2].activity = []
DB.subscriber[2].client = Dummy()
DB.subscriber[2].client.description = Dummy()
DB.subscriber[2].client.description.locale = 'MEDAL_DESCRIPTION_GROUND_AND_IN_THE_SKY'
DB.subscriber[2].client.icon = Dummy()
DB.subscriber[2].client.icon.big = 'icons/awards/achievementsInfo/acSeriesGroundSky.dds'
DB.subscriber[2].client.icon.faded = 'icons/awards/achievements/acSeriesGroundSky_Outline.dds'
DB.subscriber[2].client.icon.small = 'icons/awards/achievements/acSeriesGroundSky.dds'
DB.subscriber[2].client.multiple = true
DB.subscriber[2].client.name = Dummy()
DB.subscriber[2].client.name.locale = 'MEDAL_NAME_GROUND_AND_IN_THE_SKY'
DB.subscriber[2].client.order = 2
DB.subscriber[2].client.page = 0
DB.subscriber[2].client.show = Dummy()
DB.subscriber[2].client.show.whenDone = 2
DB.subscriber[2].condition = []
DB.subscriber[2].count = []
DB.subscriber[2].event = []
DB.subscriber[2].event.insert(0, None)
DB.subscriber[2].event[0] = Dummy()
DB.subscriber[2].event[0].condition = []
DB.subscriber[2].event[0].context = 'player'
DB.subscriber[2].event[0].count = []
DB.subscriber[2].event[0].count.insert(0, None)
DB.subscriber[2].event[0].count[0] = Dummy()
DB.subscriber[2].event[0].count[0].id = 0
DB.subscriber[2].event[0].count[0].value_ = 4
DB.subscriber[2].event[0].name = 'kill'
DB.subscriber[2].event[0].operation = []
DB.subscriber[2].event[0].type = 'battle'
DB.subscriber[2].event.insert(1, None)
DB.subscriber[2].event[1] = Dummy()
DB.subscriber[2].event[1].condition = []
DB.subscriber[2].event[1].context = 'player'
DB.subscriber[2].event[1].count = []
DB.subscriber[2].event[1].count.insert(0, None)
DB.subscriber[2].event[1].count[0] = Dummy()
DB.subscriber[2].event[1].count[0].id = 1
DB.subscriber[2].event[1].count[0].value_ = 4
DB.subscriber[2].event[1].name = 'destroy'
DB.subscriber[2].event[1].operation = []
DB.subscriber[2].event[1].type = 'battle'
DB.subscriber[2].event.insert(2, None)
DB.subscriber[2].event[2] = Dummy()
DB.subscriber[2].event[2].condition = []
DB.subscriber[2].event[2].context = 'player'
DB.subscriber[2].event[2].count = []
DB.subscriber[2].event[2].name = 'result'
DB.subscriber[2].event[2].operation = []
DB.subscriber[2].event[2].operation.insert(0, None)
DB.subscriber[2].event[2].operation[0] = Dummy()
DB.subscriber[2].event[2].operation[0].event = []
DB.subscriber[2].event[2].operation[0].id = []
DB.subscriber[2].event[2].operation[0].reset_ = true
DB.subscriber[2].event[2].operation[0].self = true
DB.subscriber[2].event[2].type = 'battle'
DB.subscriber[2].modify = []
DB.subscriber[2].name = 'groundandinthesky'
DB.subscriber[2].operation = []
DB.subscriber[2].send = []
DB.subscriber.insert(3, None)
DB.subscriber[3] = Dummy()
DB.subscriber[3].activity = []
DB.subscriber[3].client = Dummy()
DB.subscriber[3].client.description = Dummy()
DB.subscriber[3].client.description.locale = 'MEDAL_DESCRIPTION_DANGEROUS_TARGET'
DB.subscriber[3].client.icon = Dummy()
DB.subscriber[3].client.icon.big = 'icons/awards/achievementsInfo/acSeriesDangerTarget.dds'
DB.subscriber[3].client.icon.faded = 'icons/awards/achievements/acSeriesDangerTarget_Outline.dds'
DB.subscriber[3].client.icon.small = 'icons/awards/achievements/acSeriesDangerTarget.dds'
DB.subscriber[3].client.multiple = true
DB.subscriber[3].client.name = Dummy()
DB.subscriber[3].client.name.locale = 'MEDAL_NAME_DANGEROUS_TARGET'
DB.subscriber[3].client.order = 3
DB.subscriber[3].client.page = 0
DB.subscriber[3].condition = []
DB.subscriber[3].count = []
DB.subscriber[3].event = []
DB.subscriber[3].event.insert(0, None)
DB.subscriber[3].event[0] = Dummy()
DB.subscriber[3].event[0].condition = []
DB.subscriber[3].event[0].condition.insert(0, None)
DB.subscriber[3].event[0].condition[0] = Dummy()
DB.subscriber[3].event[0].condition[0].and_ = []
DB.subscriber[3].event[0].condition[0].contains = []
DB.subscriber[3].event[0].condition[0].equal = []
DB.subscriber[3].event[0].condition[0].equal.insert(0, None)
DB.subscriber[3].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[3].event[0].condition[0].equal[0].context = []
DB.subscriber[3].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[3].event[0].condition[0].equal[0].context[0] = 'player.killed'
DB.subscriber[3].event[0].condition[0].equal[0].value_ = []
DB.subscriber[3].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[3].event[0].condition[0].equal[0].value_[0] = 'no'
DB.subscriber[3].event[0].condition[0].gt = []
DB.subscriber[3].event[0].condition[0].gte = []
DB.subscriber[3].event[0].condition[0].id = []
DB.subscriber[3].event[0].condition[0].in_ = []
DB.subscriber[3].event[0].condition[0].lt = []
DB.subscriber[3].event[0].condition[0].lte = []
DB.subscriber[3].event[0].condition[0].not_ = []
DB.subscriber[3].event[0].condition[0].or_ = []
DB.subscriber[3].event[0].context = 'player'
DB.subscriber[3].event[0].count = []
DB.subscriber[3].event[0].count.insert(0, None)
DB.subscriber[3].event[0].count[0] = Dummy()
DB.subscriber[3].event[0].count[0].id = 0
DB.subscriber[3].event[0].count[0].value_ = 3
DB.subscriber[3].event[0].name = 'kill'
DB.subscriber[3].event[0].operation = []
DB.subscriber[3].event[0].type = 'battle'
DB.subscriber[3].event.insert(1, None)
DB.subscriber[3].event[1] = Dummy()
DB.subscriber[3].event[1].condition = []
DB.subscriber[3].event[1].context = 'player'
DB.subscriber[3].event[1].count = []
DB.subscriber[3].event[1].name = 'death'
DB.subscriber[3].event[1].operation = []
DB.subscriber[3].event[1].operation.insert(0, None)
DB.subscriber[3].event[1].operation[0] = Dummy()
DB.subscriber[3].event[1].operation[0].event = []
DB.subscriber[3].event[1].operation[0].id = []
DB.subscriber[3].event[1].operation[0].reset_ = true
DB.subscriber[3].event[1].operation[0].self = true
DB.subscriber[3].event[1].type = 'battle'
DB.subscriber[3].event.insert(2, None)
DB.subscriber[3].event[2] = Dummy()
DB.subscriber[3].event[2].condition = []
DB.subscriber[3].event[2].context = 'player'
DB.subscriber[3].event[2].count = []
DB.subscriber[3].event[2].name = 'result'
DB.subscriber[3].event[2].operation = []
DB.subscriber[3].event[2].operation.insert(0, None)
DB.subscriber[3].event[2].operation[0] = Dummy()
DB.subscriber[3].event[2].operation[0].event = []
DB.subscriber[3].event[2].operation[0].id = []
DB.subscriber[3].event[2].operation[0].reset_ = true
DB.subscriber[3].event[2].operation[0].self = true
DB.subscriber[3].event[2].type = 'battle'
DB.subscriber[3].modify = []
DB.subscriber[3].name = 'dangeroustarget'
DB.subscriber[3].operation = []
DB.subscriber[3].send = []
DB.subscriber.insert(4, None)
DB.subscriber[4] = Dummy()
DB.subscriber[4].activity = []
DB.subscriber[4].client = Dummy()
DB.subscriber[4].client.description = Dummy()
DB.subscriber[4].client.description.locale = 'MEDAL_DESCRIPTION_AVALANCHE'
DB.subscriber[4].client.icon = Dummy()
DB.subscriber[4].client.icon.big = 'icons/awards/achievementsInfo/acSeriesAvalanche.dds'
DB.subscriber[4].client.icon.faded = 'icons/awards/achievements/acSeriesAvalanche_Outline.dds'
DB.subscriber[4].client.icon.small = 'icons/awards/achievements/acSeriesAvalanche.dds'
DB.subscriber[4].client.multiple = true
DB.subscriber[4].client.name = Dummy()
DB.subscriber[4].client.name.locale = 'MEDAL_NAME_AVALANCHE'
DB.subscriber[4].client.order = 4
DB.subscriber[4].client.page = 0
DB.subscriber[4].condition = []
DB.subscriber[4].count = []
DB.subscriber[4].event = []
DB.subscriber[4].event.insert(0, None)
DB.subscriber[4].event[0] = Dummy()
DB.subscriber[4].event[0].condition = []
DB.subscriber[4].event[0].condition.insert(0, None)
DB.subscriber[4].event[0].condition[0] = Dummy()
DB.subscriber[4].event[0].condition[0].and_ = []
DB.subscriber[4].event[0].condition[0].contains = []
DB.subscriber[4].event[0].condition[0].equal = []
DB.subscriber[4].event[0].condition[0].equal.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[4].event[0].condition[0].equal[0].context = []
DB.subscriber[4].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0].context[0] = 'player.killed'
DB.subscriber[4].event[0].condition[0].equal[0].value_ = []
DB.subscriber[4].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[4].event[0].condition[0].equal[0].value_[0] = 'no'
DB.subscriber[4].event[0].condition[0].gt = []
DB.subscriber[4].event[0].condition[0].gte = []
DB.subscriber[4].event[0].condition[0].id = []
DB.subscriber[4].event[0].condition[0].in_ = []
DB.subscriber[4].event[0].condition[0].lt = []
DB.subscriber[4].event[0].condition[0].lte = []
DB.subscriber[4].event[0].condition[0].not_ = []
DB.subscriber[4].event[0].condition[0].or_ = []
DB.subscriber[4].event[0].context = 'player'
DB.subscriber[4].event[0].count = []
DB.subscriber[4].event[0].count.insert(0, None)
DB.subscriber[4].event[0].count[0] = Dummy()
DB.subscriber[4].event[0].count[0].id = 0
DB.subscriber[4].event[0].count[0].value_ = 5
DB.subscriber[4].event[0].name = 'destroy'
DB.subscriber[4].event[0].operation = []
DB.subscriber[4].event[0].type = 'battle'
DB.subscriber[4].event.insert(1, None)
DB.subscriber[4].event[1] = Dummy()
DB.subscriber[4].event[1].condition = []
DB.subscriber[4].event[1].context = 'player'
DB.subscriber[4].event[1].count = []
DB.subscriber[4].event[1].name = 'death'
DB.subscriber[4].event[1].operation = []
DB.subscriber[4].event[1].operation.insert(0, None)
DB.subscriber[4].event[1].operation[0] = Dummy()
DB.subscriber[4].event[1].operation[0].event = []
DB.subscriber[4].event[1].operation[0].id = []
DB.subscriber[4].event[1].operation[0].reset_ = true
DB.subscriber[4].event[1].operation[0].self = true
DB.subscriber[4].event[1].type = 'battle'
DB.subscriber[4].event.insert(2, None)
DB.subscriber[4].event[2] = Dummy()
DB.subscriber[4].event[2].condition = []
DB.subscriber[4].event[2].context = 'player'
DB.subscriber[4].event[2].count = []
DB.subscriber[4].event[2].name = 'result'
DB.subscriber[4].event[2].operation = []
DB.subscriber[4].event[2].operation.insert(0, None)
DB.subscriber[4].event[2].operation[0] = Dummy()
DB.subscriber[4].event[2].operation[0].event = []
DB.subscriber[4].event[2].operation[0].id = []
DB.subscriber[4].event[2].operation[0].reset_ = true
DB.subscriber[4].event[2].operation[0].self = true
DB.subscriber[4].event[2].type = 'battle'
DB.subscriber[4].modify = []
DB.subscriber[4].name = 'avalanche'
DB.subscriber[4].operation = []
DB.subscriber[4].send = []
DB.subscriber.insert(5, None)
DB.subscriber[5] = Dummy()
DB.subscriber[5].activity = []
DB.subscriber[5].client = Dummy()
DB.subscriber[5].client.description = Dummy()
DB.subscriber[5].client.description.locale = 'MEDAL_DESCRIPTION_HUNTER'
DB.subscriber[5].client.icon = Dummy()
DB.subscriber[5].client.icon.big = 'icons/awards/achievementsInfo/acSeriesHunter.dds'
DB.subscriber[5].client.icon.faded = 'icons/awards/achievements/acSeriesHunter_Outline.dds'
DB.subscriber[5].client.icon.small = 'icons/awards/achievements/acSeriesHunter.dds'
DB.subscriber[5].client.multiple = true
DB.subscriber[5].client.name = Dummy()
DB.subscriber[5].client.name.locale = 'MEDAL_NAME_HUNTER'
DB.subscriber[5].client.order = 5
DB.subscriber[5].client.page = 0
DB.subscriber[5].client.show = Dummy()
DB.subscriber[5].client.show.whenDone = 2
DB.subscriber[5].condition = []
DB.subscriber[5].count = []
DB.subscriber[5].event = []
DB.subscriber[5].event.insert(0, None)
DB.subscriber[5].event[0] = Dummy()
DB.subscriber[5].event[0].condition = []
DB.subscriber[5].event[0].condition.insert(0, None)
DB.subscriber[5].event[0].condition[0] = Dummy()
DB.subscriber[5].event[0].condition[0].and_ = []
DB.subscriber[5].event[0].condition[0].contains = []
DB.subscriber[5].event[0].condition[0].equal = []
DB.subscriber[5].event[0].condition[0].equal.insert(0, None)
DB.subscriber[5].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[5].event[0].condition[0].equal[0].context = []
DB.subscriber[5].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[5].event[0].condition[0].equal[0].context[0] = 'victim.type'
DB.subscriber[5].event[0].condition[0].equal[0].value_ = []
DB.subscriber[5].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[5].event[0].condition[0].equal[0].value_[0] = 'defender'
DB.subscriber[5].event[0].condition[0].gt = []
DB.subscriber[5].event[0].condition[0].gte = []
DB.subscriber[5].event[0].condition[0].id = []
DB.subscriber[5].event[0].condition[0].in_ = []
DB.subscriber[5].event[0].condition[0].lt = []
DB.subscriber[5].event[0].condition[0].lte = []
DB.subscriber[5].event[0].condition[0].not_ = []
DB.subscriber[5].event[0].condition[0].or_ = []
DB.subscriber[5].event[0].context = 'player'
DB.subscriber[5].event[0].count = []
DB.subscriber[5].event[0].count.insert(0, None)
DB.subscriber[5].event[0].count[0] = Dummy()
DB.subscriber[5].event[0].count[0].id = 0
DB.subscriber[5].event[0].count[0].value_ = 6
DB.subscriber[5].event[0].name = 'kill'
DB.subscriber[5].event[0].operation = []
DB.subscriber[5].event[0].type = 'battle'
DB.subscriber[5].event.insert(1, None)
DB.subscriber[5].event[1] = Dummy()
DB.subscriber[5].event[1].condition = []
DB.subscriber[5].event[1].context = 'player'
DB.subscriber[5].event[1].count = []
DB.subscriber[5].event[1].name = 'result'
DB.subscriber[5].event[1].operation = []
DB.subscriber[5].event[1].operation.insert(0, None)
DB.subscriber[5].event[1].operation[0] = Dummy()
DB.subscriber[5].event[1].operation[0].event = []
DB.subscriber[5].event[1].operation[0].id = []
DB.subscriber[5].event[1].operation[0].reset_ = true
DB.subscriber[5].event[1].operation[0].self = true
DB.subscriber[5].event[1].type = 'battle'
DB.subscriber[5].modify = []
DB.subscriber[5].name = 'hunter'
DB.subscriber[5].operation = []
DB.subscriber[5].send = []
DB.subscriber.insert(6, None)
DB.subscriber[6] = Dummy()
DB.subscriber[6].activity = []
DB.subscriber[6].client = Dummy()
DB.subscriber[6].client.description = Dummy()
DB.subscriber[6].client.description.locale = 'MEDAL_DESCRIPTION_INVADER'
DB.subscriber[6].client.icon = Dummy()
DB.subscriber[6].client.icon.big = 'icons/awards/achievementsInfo/acSeriesInvader.dds'
DB.subscriber[6].client.icon.faded = 'icons/awards/achievements/acSeriesInvader_Outline.dds'
DB.subscriber[6].client.icon.small = 'icons/awards/achievements/acSeriesInvader.dds'
DB.subscriber[6].client.multiple = true
DB.subscriber[6].client.name = Dummy()
DB.subscriber[6].client.name.locale = 'MEDAL_NAME_INVADER'
DB.subscriber[6].client.order = 6
DB.subscriber[6].client.page = 0
DB.subscriber[6].client.show = Dummy()
DB.subscriber[6].client.show.whenDone = 2
DB.subscriber[6].condition = []
DB.subscriber[6].count = []
DB.subscriber[6].event = []
DB.subscriber[6].event.insert(0, None)
DB.subscriber[6].event[0] = Dummy()
DB.subscriber[6].event[0].condition = []
DB.subscriber[6].event[0].context = 'player'
DB.subscriber[6].event[0].count = []
DB.subscriber[6].event[0].count.insert(0, None)
DB.subscriber[6].event[0].count[0] = Dummy()
DB.subscriber[6].event[0].count[0].context = 'points.capture'
DB.subscriber[6].event[0].count[0].id = 0
DB.subscriber[6].event[0].count[0].value_ = 75
DB.subscriber[6].event[0].name = 'gain'
DB.subscriber[6].event[0].operation = []
DB.subscriber[6].event[0].type = 'battle'
DB.subscriber[6].event.insert(1, None)
DB.subscriber[6].event[1] = Dummy()
DB.subscriber[6].event[1].condition = []
DB.subscriber[6].event[1].context = 'player'
DB.subscriber[6].event[1].count = []
DB.subscriber[6].event[1].name = 'result'
DB.subscriber[6].event[1].operation = []
DB.subscriber[6].event[1].operation.insert(0, None)
DB.subscriber[6].event[1].operation[0] = Dummy()
DB.subscriber[6].event[1].operation[0].event = []
DB.subscriber[6].event[1].operation[0].id = []
DB.subscriber[6].event[1].operation[0].reset_ = true
DB.subscriber[6].event[1].operation[0].self = true
DB.subscriber[6].event[1].type = 'battle'
DB.subscriber[6].modify = []
DB.subscriber[6].name = 'invader'
DB.subscriber[6].operation = []
DB.subscriber[6].send = []
DB.subscriber.insert(7, None)
DB.subscriber[7] = Dummy()
DB.subscriber[7].activity = []
DB.subscriber[7].client = Dummy()
DB.subscriber[7].client.description = Dummy()
DB.subscriber[7].client.description.locale = 'MEDAL_DESCRIPTION_DANGER_TAIL'
DB.subscriber[7].client.icon = Dummy()
DB.subscriber[7].client.icon.big = 'icons/awards/achievementsInfo/acSeriesDangerTail.dds'
DB.subscriber[7].client.icon.faded = 'icons/awards/achievements/acSeriesDangerTail_Outline.dds'
DB.subscriber[7].client.icon.small = 'icons/awards/achievements/acSeriesDangerTail.dds'
DB.subscriber[7].client.multiple = true
DB.subscriber[7].client.name = Dummy()
DB.subscriber[7].client.name.locale = 'MEDAL_NAME_DANGER_TAIL'
DB.subscriber[7].client.order = 7
DB.subscriber[7].client.page = 0
DB.subscriber[7].condition = []
DB.subscriber[7].count = []
DB.subscriber[7].event = []
DB.subscriber[7].event.insert(0, None)
DB.subscriber[7].event[0] = Dummy()
DB.subscriber[7].event[0].condition = []
DB.subscriber[7].event[0].condition.insert(0, None)
DB.subscriber[7].event[0].condition[0] = Dummy()
DB.subscriber[7].event[0].condition[0].and_ = []
DB.subscriber[7].event[0].condition[0].contains = []
DB.subscriber[7].event[0].condition[0].equal = []
DB.subscriber[7].event[0].condition[0].equal.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0] = Dummy()
DB.subscriber[7].event[0].condition[0].equal[0].context = []
DB.subscriber[7].event[0].condition[0].equal[0].context.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].context[0] = 'by'
DB.subscriber[7].event[0].condition[0].equal[0].value_ = []
DB.subscriber[7].event[0].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[7].event[0].condition[0].equal[0].value_[0] = 'gunner'
DB.subscriber[7].event[0].condition[0].gt = []
DB.subscriber[7].event[0].condition[0].gte = []
DB.subscriber[7].event[0].condition[0].id = []
DB.subscriber[7].event[0].condition[0].in_ = []
DB.subscriber[7].event[0].condition[0].lt = []
DB.subscriber[7].event[0].condition[0].lte = []
DB.subscriber[7].event[0].condition[0].not_ = []
DB.subscriber[7].event[0].condition[0].or_ = []
DB.subscriber[7].event[0].context = 'player'
DB.subscriber[7].event[0].count = []
DB.subscriber[7].event[0].count.insert(0, None)
DB.subscriber[7].event[0].count[0] = Dummy()
DB.subscriber[7].event[0].count[0].id = 0
DB.subscriber[7].event[0].count[0].value_ = 1
DB.subscriber[7].event[0].name = 'kill'
DB.subscriber[7].event[0].operation = []
DB.subscriber[7].event[0].type = 'battle'
DB.subscriber[7].event.insert(1, None)
DB.subscriber[7].event[1] = Dummy()
DB.subscriber[7].event[1].condition = []
DB.subscriber[7].event[1].context = 'player'
DB.subscriber[7].event[1].count = []
DB.subscriber[7].event[1].name = 'death'
DB.subscriber[7].event[1].operation = []
DB.subscriber[7].event[1].operation.insert(0, None)
DB.subscriber[7].event[1].operation[0] = Dummy()
DB.subscriber[7].event[1].operation[0].event = []
DB.subscriber[7].event[1].operation[0].id = []
DB.subscriber[7].event[1].operation[0].reset_ = true
DB.subscriber[7].event[1].operation[0].self = true
DB.subscriber[7].event[1].type = 'battle'
DB.subscriber[7].modify = []
DB.subscriber[7].name = 'dangertail'
DB.subscriber[7].operation = []
DB.subscriber[7].send = []
DB.subscriber[7].server = Dummy()
DB.subscriber[7].server.repeat = true
DB.subscriber[7].server.scope = []
DB.subscriber[0].id = 1838357728
DB.subscriber[1].id = 216076994
DB.subscriber[2].id = 263203707
DB.subscriber[3].id = 1432053184
DB.subscriber[4].id = -1381471528
DB.subscriber[5].id = 743661357
DB.subscriber[6].id = -1655595659
DB.subscriber[7].id = -1515840094
DB.subscriber[0].eventIds = (761754430,)
DB.subscriber[1].eventIds = (771950333, 516184373)
DB.subscriber[6].eventIds = (771950333, 516184373)
DB.subscriber[2].eventIds = (-104890988, -1370837730, 516184373)
DB.subscriber[3].eventIds = (-104890988, 615894436, 516184373)
DB.subscriber[4].eventIds = (-1370837730, 615894436, 516184373)
DB.subscriber[5].eventIds = (-104890988, 516184373)
DB.subscriber[7].eventIds = (-104890988, 615894436)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {1838357728: (DB.subscriber[0],),
                                   216076994: (DB.subscriber[1],),
                                   263203707: (DB.subscriber[2],),
                                   1432053184: (DB.subscriber[3],),
                                   -1381471528: (DB.subscriber[4],),
                                   743661357: (DB.subscriber[5],),
                                   -1655595659: (DB.subscriber[6],),
                                   -1515840094: (DB.subscriber[7],)},
                            'name': {'reset': (DB.subscriber[0],),
                                     'effective': (DB.subscriber[1],),
                                     'groundandinthesky': (DB.subscriber[2],),
                                     'dangeroustarget': (DB.subscriber[3],),
                                     'avalanche': (DB.subscriber[4],),
                                     'hunter': (DB.subscriber[5],),
                                     'invader': (DB.subscriber[6],),
                                     'dangertail': (DB.subscriber[7],)},
                            'type': {'achievement.reset': (DB.subscriber[0],),
                                     'achievement': (DB.subscriber[1],
                                                     DB.subscriber[2],
                                                     DB.subscriber[3],
                                                     DB.subscriber[4],
                                                     DB.subscriber[5],
                                                     DB.subscriber[6],
                                                     DB.subscriber[7])},
                            'group': {'series': (DB.subscriber[0],
                                                 DB.subscriber[1],
                                                 DB.subscriber[2],
                                                 DB.subscriber[3],
                                                 DB.subscriber[4],
                                                 DB.subscriber[5],
                                                 DB.subscriber[6],
                                                 DB.subscriber[7])},
                            'eventIds': {(761754430,): (DB.subscriber[0],),
                                         (771950333, 516184373): (DB.subscriber[1], DB.subscriber[6]),
                                         (-104890988, -1370837730, 516184373): (DB.subscriber[2],),
                                         (-104890988, 615894436, 516184373): (DB.subscriber[3],),
                                         (-1370837730, 615894436, 516184373): (DB.subscriber[4],),
                                         (-104890988, 516184373): (DB.subscriber[5],),
                                         (-104890988, 615894436): (DB.subscriber[7],)},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}