# Embedded file name: scripts/client/GameEvents/features/modifiers/db/postbattle.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = False

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class OperationModifyBy:
    add = 0
    multiply = 1
    ALL_TYPES = (add, multiply)


class OperationModifyType:
    exp = 0
    freeExp = 1
    credits = 2
    crewExp = 3
    ALL_TYPES = (exp,
     freeExp,
     credits,
     crewExp)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


DB = Dummy()
DB.include = Dummy()
DB.include.condition = []
DB.include.count = []
DB.include.event = []
DB.include.group = 'postbattle'
DB.include.modify = []
DB.include.operation = []
DB.include.operation.insert(0, None)
DB.include.operation[0] = Dummy()
DB.include.operation[0].event = []
DB.include.operation[0].id = []
DB.include.operation[0].processors = []
DB.include.operation[0].self = true
DB.include.operation[0].set = Dummy()
DB.include.operation[0].set.active = false
DB.include.operation[0].set.completed = false
DB.include.send = []
DB.include.server = Dummy()
DB.include.server.enabled = false
DB.include.server.scope = []
DB.include.server.scope.insert(0, None)
DB.include.server.scope[0] = 'player'
DB.include.type = 'modifiers'
DB.subscriber = []
DB.subscriber.insert(0, None)
DB.subscriber[0] = Dummy()
DB.subscriber[0].client = Dummy()
DB.subscriber[0].client.description = Dummy()
DB.subscriber[0].client.description.locale = 'somelocale'
DB.subscriber[0].client.name = Dummy()
DB.subscriber[0].client.name.locale = 'somelocale'
DB.subscriber[0].client.tooltip = Dummy()
DB.subscriber[0].client.tooltip.locale = 'somelocale'
DB.subscriber[0].condition = []
DB.subscriber[0].count = []
DB.subscriber[0].event = []
DB.subscriber[0].event.insert(0, None)
DB.subscriber[0].event[0] = Dummy()
DB.subscriber[0].event[0].condition = []
DB.subscriber[0].event[0].context = 'player'
DB.subscriber[0].event[0].count = []
DB.subscriber[0].event[0].count.insert(0, None)
DB.subscriber[0].event[0].count[0] = Dummy()
DB.subscriber[0].event[0].count[0].event = []
DB.subscriber[0].event[0].count[0].value_ = 5
DB.subscriber[0].event[0].name = 'battle.result.processed'
DB.subscriber[0].event[0].operation = []
DB.subscriber[0].event[0].type = 'hangar'
DB.subscriber[0].modify = []
DB.subscriber[0].modify.insert(0, None)
DB.subscriber[0].modify[0] = Dummy()
DB.subscriber[0].modify[0].by = OperationModifyBy.multiply
DB.subscriber[0].modify[0].type = OperationModifyType.exp
DB.subscriber[0].modify[0].value_ = 5.0
DB.subscriber[0].name = 'x5_plane_experience_5_battles'
DB.subscriber[0].operation = []
DB.subscriber[0].send = []
DB.subscriber.insert(1, None)
DB.subscriber[1] = Dummy()
DB.subscriber[1].client = Dummy()
DB.subscriber[1].client.description = Dummy()
DB.subscriber[1].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_3'
DB.subscriber[1].client.name = Dummy()
DB.subscriber[1].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[1].client.tooltip = Dummy()
DB.subscriber[1].client.tooltip.locale = 'TOOLTIP_AIRPLANE_XP'
DB.subscriber[1].condition = []
DB.subscriber[1].count = []
DB.subscriber[1].event = []
DB.subscriber[1].event.insert(0, None)
DB.subscriber[1].event[0] = Dummy()
DB.subscriber[1].event[0].condition = []
DB.subscriber[1].event[0].context = 'player'
DB.subscriber[1].event[0].count = []
DB.subscriber[1].event[0].count.insert(0, None)
DB.subscriber[1].event[0].count[0] = Dummy()
DB.subscriber[1].event[0].count[0].event = []
DB.subscriber[1].event[0].count[0].value_ = 3
DB.subscriber[1].event[0].name = 'battle.result.processed'
DB.subscriber[1].event[0].operation = []
DB.subscriber[1].event[0].type = 'hangar'
DB.subscriber[1].modify = []
DB.subscriber[1].modify.insert(0, None)
DB.subscriber[1].modify[0] = Dummy()
DB.subscriber[1].modify[0].by = OperationModifyBy.multiply
DB.subscriber[1].modify[0].type = OperationModifyType.exp
DB.subscriber[1].modify[0].value_ = 1.5
DB.subscriber[1].name = 'x1.5_plane_experience_3_battles'
DB.subscriber[1].operation = []
DB.subscriber[1].send = []
DB.subscriber.insert(2, None)
DB.subscriber[2] = Dummy()
DB.subscriber[2].client = Dummy()
DB.subscriber[2].client.description = Dummy()
DB.subscriber[2].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_2'
DB.subscriber[2].client.name = Dummy()
DB.subscriber[2].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[2].client.tooltip = Dummy()
DB.subscriber[2].client.tooltip.locale = 'TOOLTIP_AIRPLANE_XP'
DB.subscriber[2].condition = []
DB.subscriber[2].count = []
DB.subscriber[2].event = []
DB.subscriber[2].group = 'postbattle'
DB.subscriber[2].modify = []
DB.subscriber[2].modify.insert(0, None)
DB.subscriber[2].modify[0] = Dummy()
DB.subscriber[2].modify[0].by = OperationModifyBy.multiply
DB.subscriber[2].modify[0].type = OperationModifyType.exp
DB.subscriber[2].modify[0].value_ = 1.5
DB.subscriber[2].name = 'x1.5_plane_experience_2_battles'
DB.subscriber[2].operation = []
DB.subscriber[2].send = []
DB.subscriber[2].type = 'modifiers'
DB.subscriber.insert(3, None)
DB.subscriber[3] = Dummy()
DB.subscriber[3].client = Dummy()
DB.subscriber[3].client.description = Dummy()
DB.subscriber[3].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_1'
DB.subscriber[3].client.name = Dummy()
DB.subscriber[3].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[3].client.tooltip = Dummy()
DB.subscriber[3].client.tooltip.locale = 'TOOLTIP_AIRPLANE_XP'
DB.subscriber[3].condition = []
DB.subscriber[3].count = []
DB.subscriber[3].event = []
DB.subscriber[3].modify = []
DB.subscriber[3].modify.insert(0, None)
DB.subscriber[3].modify[0] = Dummy()
DB.subscriber[3].modify[0].by = OperationModifyBy.multiply
DB.subscriber[3].modify[0].type = OperationModifyType.exp
DB.subscriber[3].modify[0].value_ = 2.0
DB.subscriber[3].name = 'x2_plane_experience_1_battle'
DB.subscriber[3].operation = []
DB.subscriber[3].send = []
DB.subscriber.insert(4, None)
DB.subscriber[4] = Dummy()
DB.subscriber[4].client = Dummy()
DB.subscriber[4].client.description = Dummy()
DB.subscriber[4].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_1'
DB.subscriber[4].client.name = Dummy()
DB.subscriber[4].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[4].client.tooltip = Dummy()
DB.subscriber[4].client.tooltip.locale = 'TOOLTIP_AIRPLANE_XP'
DB.subscriber[4].condition = []
DB.subscriber[4].count = []
DB.subscriber[4].event = []
DB.subscriber[4].modify = []
DB.subscriber[4].modify.insert(0, None)
DB.subscriber[4].modify[0] = Dummy()
DB.subscriber[4].modify[0].by = OperationModifyBy.multiply
DB.subscriber[4].modify[0].type = OperationModifyType.exp
DB.subscriber[4].modify[0].value_ = 1.5
DB.subscriber[4].name = 'x1.5_plane_experience_1_battle'
DB.subscriber[4].operation = []
DB.subscriber[4].send = []
DB.subscriber.insert(5, None)
DB.subscriber[5] = Dummy()
DB.subscriber[5].client = Dummy()
DB.subscriber[5].client.description = Dummy()
DB.subscriber[5].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_2'
DB.subscriber[5].client.name = Dummy()
DB.subscriber[5].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[5].client.tooltip = Dummy()
DB.subscriber[5].client.tooltip.locale = 'TOOLTIP_AIRPLANE_XP'
DB.subscriber[5].condition = []
DB.subscriber[5].count = []
DB.subscriber[5].event = []
DB.subscriber[5].modify = []
DB.subscriber[5].modify.insert(0, None)
DB.subscriber[5].modify[0] = Dummy()
DB.subscriber[5].modify[0].by = OperationModifyBy.multiply
DB.subscriber[5].modify[0].type = OperationModifyType.exp
DB.subscriber[5].modify[0].value_ = 2.0
DB.subscriber[5].name = 'x2_plane_experience_2_battles'
DB.subscriber[5].operation = []
DB.subscriber[5].send = []
DB.subscriber.insert(6, None)
DB.subscriber[6] = Dummy()
DB.subscriber[6].client = Dummy()
DB.subscriber[6].client.description = Dummy()
DB.subscriber[6].client.description.locale = 'LOBBY_REWARD_CREW_BONUS_EXP'
DB.subscriber[6].client.name = Dummy()
DB.subscriber[6].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[6].client.tooltip = Dummy()
DB.subscriber[6].client.tooltip.locale = 'LOBBY_CREW_EXP_DESCRIPTION'
DB.subscriber[6].condition = []
DB.subscriber[6].condition.insert(0, None)
DB.subscriber[6].condition[0] = Dummy()
DB.subscriber[6].condition[0].and_ = []
DB.subscriber[6].condition[0].equal = []
DB.subscriber[6].condition[0].equal.insert(0, None)
DB.subscriber[6].condition[0].equal[0] = Dummy()
DB.subscriber[6].condition[0].equal[0].context = []
DB.subscriber[6].condition[0].equal[0].context.insert(0, None)
DB.subscriber[6].condition[0].equal[0].context[0] = 'win'
DB.subscriber[6].condition[0].equal[0].value_ = []
DB.subscriber[6].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[6].condition[0].equal[0].value_[0] = 'true'
DB.subscriber[6].condition[0].event = []
DB.subscriber[6].condition[0].gt = []
DB.subscriber[6].condition[0].gte = []
DB.subscriber[6].condition[0].in_ = []
DB.subscriber[6].condition[0].lt = []
DB.subscriber[6].condition[0].lte = []
DB.subscriber[6].condition[0].not_ = []
DB.subscriber[6].condition[0].or_ = []
DB.subscriber[6].count = []
DB.subscriber[6].count.insert(0, None)
DB.subscriber[6].count[0] = Dummy()
DB.subscriber[6].count[0].event = []
DB.subscriber[6].count[0].value_ = 3
DB.subscriber[6].event = []
DB.subscriber[6].event.insert(0, None)
DB.subscriber[6].event[0] = Dummy()
DB.subscriber[6].event[0].condition = []
DB.subscriber[6].event[0].context = 'player'
DB.subscriber[6].event[0].count = []
DB.subscriber[6].event[0].name = 'battle.result.processed'
DB.subscriber[6].event[0].operation = []
DB.subscriber[6].event[0].type = 'hangar'
DB.subscriber[6].modify = []
DB.subscriber[6].modify.insert(0, None)
DB.subscriber[6].modify[0] = Dummy()
DB.subscriber[6].modify[0].by = OperationModifyBy.multiply
DB.subscriber[6].modify[0].type = OperationModifyType.crewExp
DB.subscriber[6].modify[0].value_ = 1.5
DB.subscriber[6].name = 'x1.5_plane_experience_2_wins'
DB.subscriber[6].operation = []
DB.subscriber[6].send = []
DB.subscriber.insert(7, None)
DB.subscriber[7] = Dummy()
DB.subscriber[7].client = Dummy()
DB.subscriber[7].client.description = Dummy()
DB.subscriber[7].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_CREDIT'
DB.subscriber[7].client.name = Dummy()
DB.subscriber[7].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[7].condition = []
DB.subscriber[7].count = []
DB.subscriber[7].event = []
DB.subscriber[7].event.insert(0, None)
DB.subscriber[7].event[0] = Dummy()
DB.subscriber[7].event[0].condition = []
DB.subscriber[7].event[0].context = 'player'
DB.subscriber[7].event[0].count = []
DB.subscriber[7].event[0].count.insert(0, None)
DB.subscriber[7].event[0].count[0] = Dummy()
DB.subscriber[7].event[0].count[0].event = []
DB.subscriber[7].event[0].count[0].value_ = 1
DB.subscriber[7].event[0].name = 'battle.result.processed'
DB.subscriber[7].event[0].operation = []
DB.subscriber[7].event[0].type = 'hangar'
DB.subscriber[7].modify = []
DB.subscriber[7].modify.insert(0, None)
DB.subscriber[7].modify[0] = Dummy()
DB.subscriber[7].modify[0].by = OperationModifyBy.multiply
DB.subscriber[7].modify[0].type = OperationModifyType.exp
DB.subscriber[7].modify[0].value_ = 1.5
DB.subscriber[7].modify.insert(1, None)
DB.subscriber[7].modify[1] = Dummy()
DB.subscriber[7].modify[1].by = OperationModifyBy.multiply
DB.subscriber[7].modify[1].type = OperationModifyType.credits
DB.subscriber[7].modify[1].value_ = 1.5
DB.subscriber[7].name = 'x1.5_experience_credits_1_win'
DB.subscriber[7].operation = []
DB.subscriber[7].send = []
DB.subscriber.insert(8, None)
DB.subscriber[8] = Dummy()
DB.subscriber[8].client = Dummy()
DB.subscriber[8].client.description = Dummy()
DB.subscriber[8].client.description.locale = 'LOBBY_REWARD_PLANE_BONUS_EXP_CREDIT'
DB.subscriber[8].client.name = Dummy()
DB.subscriber[8].client.name.locale = 'LOBBY_MSG_DAILY_WIN'
DB.subscriber[8].condition = []
DB.subscriber[8].condition.insert(0, None)
DB.subscriber[8].condition[0] = Dummy()
DB.subscriber[8].condition[0].and_ = []
DB.subscriber[8].condition[0].equal = []
DB.subscriber[8].condition[0].equal.insert(0, None)
DB.subscriber[8].condition[0].equal[0] = Dummy()
DB.subscriber[8].condition[0].equal[0].context = []
DB.subscriber[8].condition[0].equal[0].context.insert(0, None)
DB.subscriber[8].condition[0].equal[0].context[0] = 'win'
DB.subscriber[8].condition[0].equal[0].value_ = []
DB.subscriber[8].condition[0].equal[0].value_.insert(0, None)
DB.subscriber[8].condition[0].equal[0].value_[0] = 'true'
DB.subscriber[8].condition[0].event = []
DB.subscriber[8].condition[0].gt = []
DB.subscriber[8].condition[0].gte = []
DB.subscriber[8].condition[0].in_ = []
DB.subscriber[8].condition[0].lt = []
DB.subscriber[8].condition[0].lte = []
DB.subscriber[8].condition[0].not_ = []
DB.subscriber[8].condition[0].or_ = []
DB.subscriber[8].count = []
DB.subscriber[8].event = []
DB.subscriber[8].event.insert(0, None)
DB.subscriber[8].event[0] = Dummy()
DB.subscriber[8].event[0].condition = []
DB.subscriber[8].event[0].context = 'player'
DB.subscriber[8].event[0].count = []
DB.subscriber[8].event[0].count.insert(0, None)
DB.subscriber[8].event[0].count[0] = Dummy()
DB.subscriber[8].event[0].count[0].event = []
DB.subscriber[8].event[0].count[0].value_ = 2
DB.subscriber[8].event[0].name = 'battle.result.processed'
DB.subscriber[8].event[0].operation = []
DB.subscriber[8].event[0].type = 'hangar'
DB.subscriber[8].modify = []
DB.subscriber[8].modify.insert(0, None)
DB.subscriber[8].modify[0] = Dummy()
DB.subscriber[8].modify[0].by = OperationModifyBy.multiply
DB.subscriber[8].modify[0].type = OperationModifyType.exp
DB.subscriber[8].modify[0].value_ = 1.5
DB.subscriber[8].name = 'x1.5_experience_2_wins'
DB.subscriber[8].operation = []
DB.subscriber[8].send = []
DB.subscriber[0].id = -1987745971
DB.subscriber[1].id = -1427497974
DB.subscriber[2].id = -643428506
DB.subscriber[3].id = 840635228
DB.subscriber[4].id = -216768142
DB.subscriber[5].id = -1723894391
DB.subscriber[6].id = -1355967849
DB.subscriber[7].id = -1334212796
DB.subscriber[8].id = 1132349929
DB.subscriber[0].eventIds = (219609818,)
DB.subscriber[1].eventIds = (219609818,)
DB.subscriber[6].eventIds = (219609818,)
DB.subscriber[7].eventIds = (219609818,)
DB.subscriber[8].eventIds = (219609818,)
mapping = {'db': DB,
 'indexes': {'subscriber': {'id': {-1987745971: (DB.subscriber[0],),
                                   -1427497974: (DB.subscriber[1],),
                                   -643428506: (DB.subscriber[2],),
                                   840635228: (DB.subscriber[3],),
                                   -216768142: (DB.subscriber[4],),
                                   -1723894391: (DB.subscriber[5],),
                                   -1355967849: (DB.subscriber[6],),
                                   -1334212796: (DB.subscriber[7],),
                                   1132349929: (DB.subscriber[8],)},
                            'name': {'x5_plane_experience_5_battles': (DB.subscriber[0],),
                                     'x1.5_plane_experience_3_battles': (DB.subscriber[1],),
                                     'x1.5_plane_experience_2_battles': (DB.subscriber[2],),
                                     'x2_plane_experience_1_battle': (DB.subscriber[3],),
                                     'x1.5_plane_experience_1_battle': (DB.subscriber[4],),
                                     'x2_plane_experience_2_battles': (DB.subscriber[5],),
                                     'x1.5_plane_experience_2_wins': (DB.subscriber[6],),
                                     'x1.5_experience_credits_1_win': (DB.subscriber[7],),
                                     'x1.5_experience_2_wins': (DB.subscriber[8],)},
                            'type': {'modifiers': (DB.subscriber[2],)},
                            'group': {'postbattle': (DB.subscriber[2],)},
                            'eventIds': {(219609818,): (DB.subscriber[0],
                                                        DB.subscriber[1],
                                                        DB.subscriber[6],
                                                        DB.subscriber[7],
                                                        DB.subscriber[8])},
                            'parent': {}}},
 'nested': ('subscriber.nested',),
 'type': {'default': 'subscriber',
          'all': ['subscriber']}}