# Embedded file name: scripts/common/_specializations_data.py
"""
This module is autogenerated don't modify any params,
after bundling they will be lost
"""
import Math
import math
import consts
import datetime
true = True
false = False

class Dummy:
    pass


isServerDatabase = True

class AMMO_TYPE:
    BALL = 0
    AP = 1
    APC = 2
    I = 3
    APHC = 4
    API = 5
    HEI = 6
    APHE = 7
    ALL_TYPES = (BALL,
     AP,
     APC,
     I,
     APHC,
     API,
     HEI,
     APHE)


class SHELL_TYPE:
    BOMBS = 0
    ROCKETS = 1
    ALL_TYPES = (BOMBS, ROCKETS)


class SpecializationEnum:
    PILOT = 0
    GUNNER = 1
    NAVIGATOR = 2
    ALL_TYPES = (PILOT, GUNNER, NAVIGATOR)


class WEAPON_AIM_TYPE:
    empty = 0
    smg = 1
    assault = 2
    shotgun = 3
    sniper = 4
    ALL_TYPES = (empty,
     smg,
     assault,
     shotgun,
     sniper)


Specializations = Dummy()
Specializations.specialization = []
Specializations.specialization.insert(0, None)
Specializations.specialization[0] = Dummy()
Specializations.specialization[0].id = SpecializationEnum.PILOT
Specializations.specialization[0].startRank = 1
Specializations.specialization.insert(1, None)
Specializations.specialization[1] = Dummy()
Specializations.specialization[1].id = SpecializationEnum.GUNNER
Specializations.specialization[1].startRank = 1
Specializations.specialization.insert(2, None)
Specializations.specialization[2] = Dummy()
Specializations.specialization[2].id = SpecializationEnum.NAVIGATOR
Specializations.specialization[2].startRank = 1
SpecializationsDB = None

def initDB():
    global SpecializationsDB
    if SpecializationsDB is None:
        SpecializationsDB = {}
        for specialization in Specializations.specialization:
            SpecializationsDB[specialization.id] = specialization

    return


initDB()