# Embedded file name: scripts/common/MapEffectsSettings.py
from collections import namedtuple
MAX_DIST_TO_TERRAIN = 20

class Material:
    WATER = 'water'
    GROUND = 'ground'
    SAND = 'sand'
    ROCK = 'rock'
    SNOW = 'snow'
    GRASS = 'grass'


class Groups:
    GROUND = 'ground'
    SPEED = 'speedwise'


class SpeedWiseEffects:
    FORSAGE = 'forsageScreenEffect'
    FORSAGE_SNIPER = 'sniperForsageScreenEffect'


EXCLUDED_PLANES_WITH_2_ENGINES = ['me-p1102b, il-40, il-40p, mig-9, f7u, f90, f2h, gloster-javelin, attacker, westland-p-1056']
Effect = namedtuple('Effect', ['maxDistance',
 'airEffect',
 'groundParticle',
 'screenParticle'])
EFFECTS = {'55_el_hallouf_5': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                     Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                     Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                     Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                    SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '69_ocean': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                              Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                              Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand_yellow'),
                              Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass')},
              Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                             SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '05_lighthouse': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                   Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                   Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                   Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                   Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                  SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '07_bay': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                            Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                            Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                            Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
            Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                           SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '62_asian_border_7': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                       Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                       Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                       Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                       Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                       Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                      SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '09_arctic': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                               Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                               Material.SNOW: Effect(maxDistance=200, airEffect='', groundParticle='', screenParticle='screen_effect_snow_with_snowflakes')},
               Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                              SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '10_eastern_front': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                      Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                      Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                      Material.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
                      Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                     SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '76_plateau_5': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                  Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                                  Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                                  Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                                  Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                  Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                 SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '12_fjords': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                               Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                               Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                               Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
               Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                              SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '12_fjords_2': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '12_fjords_3': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '13_harbor': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                               Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                               Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                               Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                               Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
               Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                              SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '13_harbor_3': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                 Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '13_harbor_4': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                 Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '14_adriatic': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                 Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '75_fortress_3': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                   Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                   Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                   Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                   Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                  SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '17_winter_war': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water_dark', screenParticle=''),
                                   Material.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow_dark', screenParticle='screen_effects_snow_dark')},
                   Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                  SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '18_convoy': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                               Material.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
               Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                              SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '20_canyon_': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                               SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '23_province': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                 Material.GROUND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_ground', screenParticle='screen_effect_ground'),
                                 Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                 Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                 Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                 Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '73_observatory': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                    Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                    Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                    Material.SNOW: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_snow', screenParticle='screen_effect_snow')},
                    Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                   SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '26_national_park_2': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                        Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                        Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                        Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                        Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                       SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}},
 '27_giant_dam': {Groups.GROUND: {Material.WATER: Effect(maxDistance=20, airEffect='over_water', groundParticle='airplane_over_water', screenParticle=''),
                                  Material.ROCK: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_rock', screenParticle='screen_effect_rock'),
                                  Material.GRASS: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_grass', screenParticle='screen_effect_grass'),
                                  Material.SAND: Effect(maxDistance=20, airEffect='', groundParticle='airplane_over_sand', screenParticle='screen_effect_sand')},
                  Groups.SPEED: {SpeedWiseEffects.FORSAGE: 'forsage_tunnel_middle',
                                 SpeedWiseEffects.FORSAGE_SNIPER: 'forsage_tunnel_sniper'}}}